### ISSUE TITLE
Is worker mode broken???

### ISSUE THREAD

**Issue by withinboredom** [dunglas/frankenphp#100]
PHP file

```php
// public/worker.php
<?php

do {
	$running = frankenphp_handle_request(
		function () {
			echo "hello world";
		}
	);
} while ($running);

```

Then:

```
docker run --rm -e FRANKENPHP_CONFIG="worker ./public/worker.php" -p 80:80 -p 443:443 -v $(pwd):/app -w /app dunglas/frankenphp
```

When I curl localhost, it just hangs forever. @dunglas, can you reproduce this or am I doing something wrong?

**Comment by dunglas** [comment]
No issue on my side with the latest version of the image:

```
docker pull dunglas/frankenphp
docker run --rm -e FRANKENPHP_CONFIG="worker ./public/worker.php" -p 80:80 -p 443:443 -v $(pwd):/app -w /app dunglas/frankenphp
```

<img width="743" alt="image" src="https://user-images.githubusercontent.com/57224/201332996-24808f51-b28f-4584-ae05-2c66fc7561c7.png">

**Comment by withinboredom** [comment]
aha, I was missing the `worker.php` part. I thought `worker ./public/worker.php` implied it was to run `worker.php` for every request.

**Comment by dunglas** [comment]
Ok got it! So there is a bug: a 404 should be thrown, the server should not hang.
