### ISSUE TITLE
Missing space on webpage

### ISSUE THREAD

**Issue by DubbleClick** [dunglas/frankenphp#1003]
### What happened?

https://frankenphp.dev/help/

Just missing two spaces. I couldn't find the place where the website other than the docs were hosted, so this is the only place I could think of to bring it to attention.
![image](https://github.com/user-attachments/assets/7901fbe3-7a77-41b9-84ff-5fbf31b7a473)

**Comment by dunglas** [comment]
Hi, thanks for the report!

The website code is here, but we'll fix this fix you don't have time to do it :) https://github.com/dunglas/frankenphp-website

**Comment by DubbleClick** [comment]
I'll create a PR, no worries.
