### ISSUE TITLE
Invalid post type. error when I click on "POSTS" in teh Wordpress admin menu

### ISSUE THREAD

**Issue by Kkeller83** [dunglas/frankenphp#1009]
### What happened?

When running Wordpress with the standard frankenphp on ubuntu and you go and click on "POSTS" in the Wordpress admin menu you get the error invalid post type. If I run the same wordpress installation with NGINX all is ok. 

### Build Type

Official static build

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
Latest unmodified frankenphp version from releases
```

**Comment by Kkeller83** [comment]
And when I want to print the PHP info I get this:

 ./frankenphp-linux-x86_64.1 php-cli -i

Warning: Unknown: Failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Failed opening required '-i' (include_path='.:') in Unknown on line 0

**Comment by dunglas** [comment]
You must retrieve the `phpinfo()` from a web context (call the function in a webpage). The `-i` option isn't implemented yet on CLI.

Could you also copy the entire request and response (headers and body), please? You can copy them from the Network tab of the browser DevTools.

**Comment by Kkeller83** [comment]
curl 'https://keller-wptest110.dev.fineupp.com/wp-admin/edit.php' 

-H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0'
 
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8' 

-H 'Accept-Language: en-GB,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br, zstd' 

-H 'Referer: https://keller-wptest110.dev.fineupp.com/wp-login.php?redirect_to=https%3A%2F%2Fkeller-wptest110.dev.fineupp.com%2Fwp-admin%2Fedit.php&reauth=1'

 -H 'Connection: keep-alive' 

-H 'Cookie: wordpress_sec_8e7d0ba7079d245c81c16dfb819750b8=admin%7C1725123961%7Cfwj8PxZWwv5TlluLCqmpmtLW8s0QcwreIedyhb6gBZp%7C8abf7e01e53630042471215cb5c741011506e51c235b2ecd74144f7f0f7d39db; ajs_anonymous_id=7f1f0e39-383c-4bba-9de0-2247ea04fdce; wordpress_test_cookie=WP%20Cookie%20check; wp-settings-time-1=1724948820; wordpress_logged_in_8e7d0ba7079d245c81c16dfb819750b8=admin%7C1725123961%7Cfwj8PxZWwv5TlluLCqmpmtLW8s0QcwreIedyhb6gBZp%7C0c0ab99ff74816d59cab4b9bd67395e8836dbc778790ce0838378361e52e1899'

 -H 'Upgrade-Insecure-Requests: 1' -H 'Sec-Fetch-Dest: document'

 -H 'Sec-Fetch-Mode: navigate' 

-H 'Sec-Fetch-Site: same-origin' -H 'Sec-Fetch-User: ?1' 

-H 'Priority: u=0, i' 

-H 'Pragma: no-cache' 

-H 'Cache-Control: no-cache' -H 'TE: trailers'

**Comment by Kkeller83** [comment]
This is the get request from the browser copied as CURL. Response is just the "Invalid post type" 
![image](https://github.com/user-attachments/assets/1655696e-2ead-474f-b78b-b58dc6ae097e)

**Comment by Kkeller83** [comment]
this btw works: https://keller-wptest110.dev.fineupp.com/wp-admin/edit.php?post_type=post

**Comment by Kkeller83** [comment]
This is the CaddyFile: 

{
        admin off
        auto_https disable_redirects

        frankenphp
        order php_server before file_server
        order php before file_server
}

:80  {
        @static {
                file
                path *.ico *.css *.js *.gif *.jpg *.jpeg *.png *.svg *.woff
        }

        root * .
        encode zstd br gzip
        php_server
}

**Comment by Kkeller83** [comment]
Issue is pretty similiar here for a user using nginx.. just in case it helps:  https://wordpress.stackexchange.com/questions/125985/nginx-wordpress-subdirectory-invalid-post-type

**Comment by Kkeller83** [comment]
This is the CURL request when using NGINX with PHP-FPM : 

curl 'https://keller-wptest110.dev.fineupp.com/wp-admin/edit.php' 

-H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0' 

-H 'Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8' -H 'Accept-Language: en-GB,en;q=0.5' 

-H 'Accept-Encoding: gzip, deflate, br, zstd' 

-H 'Referer: https://keller-wptest110.dev.fineupp.com/wp-admin/' -H 'DNT: 1' -H 'Sec-GPC: 1'

 -H 'Connection: keep-alive' -H 'Cookie: wordpress_sec_8e7d0ba7079d245c81c16dfb819750b8=admin%7C1725023729%7C69VVunWLGcJeLaI5dXAgjzmuvdgvr4pk9x9h6UqCuPG%7Ce89ff9a6408cab784492205fcd6e39ba4064526a74b996cb5742b9c9411faace; wordpress_test_cookie=WP%20Cookie%20check; wordpress_logged_in_8e7d0ba7079d245c81c16dfb819750b8=admin%7C1725023729%7C69VVunWLGcJeLaI5dXAgjzmuvdgvr4pk9x9h6UqCuPG%7C2cc6d4a902687261dbe8bfc37ae8b769d1cac4584be027fe75fe4d1bed82bec7; wp-settings-time-1=1724951623' 
-H 'Upgrade-Insecure-Requests: 1' 

-H 'Sec-Fetch-Dest: document'

 -H 'Sec-Fetch-Mode: navigate' 

-H 'Sec-Fetch-Site: same-origin'

 -H 'Priority: u=0, i' 

-H 'Pragma: no-cache'

 -H 'Cache-Control: no-cache' 

-H 'TE: trailers'


This works

**Comment by Kkeller83** [comment]
Searching for Plugins on the Plugins page also doesn't work for me with frankenphp. Seems like this is a Javascript / Ajax not getting through thing.

**Comment by AlliBalliBaba** [comment]
Can you also share your ngxinx config? Maybe there's some special routing

**Comment by withinboredom** [comment]
@Kkeller83 in case you are not aware, you just posted your login cookies publicly on the internet and anyone/bot can now gain access to your server as an administrator. You may want to immediately change your salts in `wp-config.php` to invalidate your session cookies.

**Comment by withinboredom** [comment]
According to `admin.php` the post type is set:

```php
if ( isset( $_REQUEST['post_type'] ) && post_type_exists( $_REQUEST['post_type'] ) ) {
	$typenow = $_REQUEST['post_type'];
} else {
	$typenow = '';
}
```

and then the error is shown in `edit.php`:

```php
global $typenow;

if ( ! $typenow ) {
	wp_die( __( 'Invalid post type.' ) );
}
```

So, the question here would be: how does this request variable get set in nginx?

**Comment by Kkeller83** [comment]
Thanks @withinboredom . 

I removed the secrets and changed the salts.

Its a throw away WP instance anyway, but thanks for pointing it out. 
Always better to remove that stuff and change the salts. 

Yes, so this wordpress installation is running in caprover with nginx in front of it as reverse proxy offloading the SSL stuff and then connecting to frankenkphp in the backend. 

I have also deployed FRANKENWP (https://github.com/StephenMiracle/frankenwp) @StephenMiracle using the same caprover instance with the same nginx config as reverse proxy there it all works. 

I have also used the frankenkphp compiled version from that container and have transferred it to my wordpress instance with the issue inclujding the WP config, PHP configs and all the libraries and that also did not help. 

I have attached the NGINX config here though just in case. 

I enabled debug in wordpress and frankenphp, but the debug log looked the same in all instances, no errors and no differences in request and rewrites. 

It just seems that HTTP API requests (JS. AJAX stuff) is are either missing headers (POST TYPE ?) or are not properly routed. 
But I could not see any differences in the HTTP API payloads in the working setups (WP + NGINX or FrankenWP) vs my custom wordpress cotnainer where I have the issue running vanilla frankenphp (latest)







    server {

        listen       80;

        server_name  <%-s.publicDomain%>;

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }

        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        location / {
            return 302 https://$http_host$request_uri;
        }
    }



server {

   
        listen       80;
   
        listen              443 ssl http2;
        ssl_certificate     /nginx-shared/fullchain.pem;
        ssl_certificate_key /nginx-shared/privkey.pem;
   

        client_max_body_size 500m;

        server_name  <%-s.publicDomain%>;

        # 127.0.0.11 is DNS set up by Docker, see:
        # https://docs.docker.com/engine/userguide/networking/configure-dns/
        # https://github.com/moby/moby/issues/20026
        resolver 127.0.0.11 valid=10s;
        # IMPORTANT!! If you are here from an old thread to set a custom port, you do not need to modify this port manually here!!
        # Simply change the Container HTTP Port from the dashboard HTTP panel
        set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;

        location = / {

    <%
    if (s.httpBasicAuthPath) {
    %>
            auth_basic           "Restricted Access";
            auth_basic_user_file <%-s.httpBasicAuthPath%>; 
    <%
    }
    %>

            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header X-Forwarded-Proto $scheme;
            
            proxy_pass $upstream;
            #return 301 https://$host/todo/$1$is_args$args;
            

    <%
    if (s.websocketSupport) {
    %>
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
    <%
    }
    %>
        }


   location ~ ^\/(.*) {

    <%
    if (s.httpBasicAuthPath) {
    %>
            auth_basic           "Restricted Access";
            auth_basic_user_file <%-s.httpBasicAuthPath%>; 
    <%
    }
    %>

            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            rewrite ^\/(.*) /$1 break;
            proxy_pass $upstream;
            #return 301 https://$host/$args;
            

    <%
    if (s.websocketSupport) {
    %>
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
    <%
    }
    %>
        }

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }
        
        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        error_page 502 /error.html;
        location = /error.html {
                root /nginx-shared/catchall;
                internal;
        }
}

**Comment by withinboredom** [comment]
Hey @Kkeller83, it looks like you are missing the most important config from nginx. It's called `fastcgi.conf` or `fastcgi_params` and describes how to pass things from the request into php.

**Comment by Kkeller83** [comment]
The NGINX config you see here is just for the reverse proxy in front of frankenPHP, so it does not handle FCGI or PHP, it just passes request through. 

so the the low is currently NGINX --> FRANKENPHP

If I use the setup with NGINX --> NGINX+PHP-FPM it works (basically 2 NGINX.. one reverse proxy and the other one handling FCGI and PHP-FPM) it works and the NGINX config for the NGINX in the backend has the FCGI things setup: 

error_log /home/websson/nginx/logs/error.log;
    pid       /home/websson/nginx/pid/nginx.pid;

    events {
      # No special events for this simple setup
    }

    http {
        include /home/websson/nginx/nginx_configs/mime.types;
        include /home/websson/nginx/nginx_configs/fastcgi.conf;

server {
    listen 80;

    root /home/websson/nginx/www/wordpress;

     access_log /home/websson/nginx/logs/nginx_host.access.log;
     client_body_temp_path /home/websson/nginx/client_body;
     fastcgi_temp_path /home/websson/nginx/fastcgi_temp;
     proxy_temp_path /home/websson/nginx/proxy_temp;
     scgi_temp_path /home/websson/nginx/scgi_temp;
     uwsgi_temp_path /home/websson/nginx/uwsgi_temp;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.html index.htm index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/home/websson/.phpbrew/php/8.3.10/var/run/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include /home/websson/nginx/nginx_configs/fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }


        location ~ /\.ht {
    deny all;
  }

**Comment by Kkeller83** [comment]
Also just did an exact replay of the same request using CURL. FrankenPHP gives the Invalid Content error and NGINX + PHP-FPM gives the correct answer. Both use PHP 8.3.10 and the same PHP.INI

**Comment by Kkeller83** [comment]
Found something.. the URL rewriting does not work properly.. 

1. line request (my wordpress that does not work)
2. line request frankenWP which works.. 

![image](https://github.com/user-attachments/assets/687a353c-445d-4589-b64a-1c0a697b00f4)

**Comment by Kkeller83** [comment]
url re-writing was also not the issue
