### ISSUE TITLE
1.2.5 Not expanding (some?) Caddy's variables

### ISSUE THREAD

**Issue by Simbiat** [dunglas/frankenphp#1016]
### What happened?

[Updated](https://github.com/Simbiat/simbiat.ru/commit/ee70d73856973b674327a48e5e813a2aab96e796) to 1.2.5, and now looks like Caddy variables from config are not being expanded. Or at least some of them are not.
I am using this [dockerfile](https://github.com/Simbiat/simbiat.ru/blob/master/docker-compose.yml) with these [Caddy settings](https://github.com/Simbiat/simbiat.ru/blob/master/config/frankenphp/caddy.json5), which should result in `CADDY_HTTP_ERROR` (and `CADDY_HTTP_ERROR_MSG`) variables sent to PHP to be 403 (and `interruption triggered`) when accessing `.htaccess` (as example), but on 1.2.5 I am getting `{http.error.status_code}` (and `{http.error.message}`) instead. Revert back to 1.2.4 - works as expected.

### Build Type

Docker (Debian Bookworm)

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
N/A (or refer https://github.com/Simbiat/simbiat.ru/blob/master/config/frankenphp/php.ini)
```

**Comment by dunglas** [comment]
I optimized this part in https://github.com/dunglas/frankenphp/pull/1002. I probably introduced a bug in this patch. I'll take a look when I'll be back from vacation (if someone find and solve the issue before, don't hesitate to open a PR).
