### ISSUE TITLE
Server hangs forever

### ISSUE THREAD

**Issue by ricardoboss** [dunglas/frankenphp#104]
I am using the same setup as described in #100 and the request just hangs indefinitely. Any idea what I can do?

Also, but unrelated to this issue: is it possible to stop the server using ctrl+c? I always have to delete the container through Docker Desktop...

**Comment by ricardoboss** [comment]
PS: it gives me 404 when I access `https://localhost/` and hangs when I access `https://localhost/index.php`.

In the server log, only the request to `https://localhost/` is logged.

**Comment by dunglas** [comment]
Can you try `https://localhost/worker.php`?

**Comment by ricardoboss** [comment]
Still hangs. Errata: my file was named `index.php` (and also the command used `index.php` instead of `worker.php`). Same with `worker.php` as filename.

**Comment by ricardoboss** [comment]
Am I as the user supposed to rewrite all requests to the `worker.php` in production? Or does frankenphp do this automatically?
