### ISSUE TITLE
Question: Laravel Feature `defer()` Which Relies on FastCGI - How Does FrankenPHP Handle This?

### ISSUE THREAD

**Issue by MarkusJLechner** [dunglas/frankenphp#1046]
### Question:
We do not use worker mode (laravel octane).  
Since FrankenPHP does not rely on FastCGI, does Laravel’s `defer()` function, which depends on FastCGI, still work correctly?  
**In my local testing, it seems that `defer()` sends the response to the client as expected, and runs the deferred code afterward. However, subsequent requests to the server are delayed until the deferred functions from the first request are fully processed.**  
Is there a way to get this or a similar feature working properly in FrankenPHP?

### Background Information:
As mentioned in this [comment](https://github.com/dunglas/frankenphp/issues/570#issuecomment-1937854708) by @dunglas:

> FrankenPHP doesn't rely on or use FastCGI.

It's clear that FrankenPHP is independent of FastCGI.

Laravel introduced a new function `defer()` (see [Laravel documentation](https://laravel.com/docs/11.x/helpers#deferred-functions)), which relies on FastCGI (see articles [1](https://codecourse.com/articles/dive-into-laravels-new-defer-helper) and [2](https://www.amitmerchant.com/the-magic-behind-laravels-new-defer-helper/#the-real-magic)). This function allows the PHP process to stay open after the response has been sent to the user.

I'm aware that Caddyserver has a [directive](https://caddyserver.com/docs/caddyfile/directives/php_fastcgi) for FastCGI, but this may not be related to FrankenPHP.  
I must admit, I don’t have much experience with this topic.

**Comment by dunglas** [comment]
Defer uses `fastcgi_finish_request()` under the hood. FrankenPHP implements this function (even if we don't rely on FastCGI/FPM at all, we can, and do emulate this function).

So `defer()` works as expected.
