### ISSUE TITLE
Docker image latest-php8.3 should contain the latest php version 8.3.12

### ISSUE THREAD

**Issue by jduan00** [dunglas/frankenphp#1063]
### What happened?

Hi there,

For docker image: `latest-php8.3`, I am getting `php 8.3.7`. Should it be the latest `php 8.3.12` instead?

Thanks,

### Build Type

Docker (Debian Bookworm)

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
Hi there,

For docker image: latest-php8.3, I am getting php 8.3.7. Should it be the latest php 8.3.12 instead?

Thanks,
```

**Comment by dunglas** [comment]
We deprecated the `latest-` part. Use `dunglas/frankenphp:php8.3`, this should fix the problem.

**Comment by jduan00** [comment]
Thank you @dunglas for the prompt help. Confirmed it is working as expected!
