### ISSUE TITLE
Worker mode uses wrong path

### ISSUE THREAD

**Issue by ricardoboss** [dunglas/frankenphp#107]
Hi, thanks for the quick fix for #104!

I am now one step further, as in: the server now redirects and responds correctly, but it doesn't serve the file I gave it in the command line.

Running this command with the latest ([sha-878a30d](https://hub.docker.com/layers/dunglas/frankenphp/sha-878a30d/images/sha256-d2b348824b1fe159dcdd4c7c5b51e44d8adb1385e9d027c56be5ba4febaaa206?context=explore)) image:

```bash
docker run --rm -e FRANKENPHP_CONFIG="worker ./example/worker.php" -p 80:80 -p 443:443 -v $pwd:/app -w /app dunglas/frankenphp
```

and this `worker.php` file:

```php
<?php
// ./example/worker.php

do {
    $running = frankenphp_handle_request(
        function () {
            echo "hello world";
        }
    );
} while ($running);
```
Results in this output:

```

Warning: Unknown: Failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Failed opening required '/app/public/worker.php' (include_path='.:/usr/local/lib/php') in Unknown on line 0
```

So I assume the `public` path is hardcoded somehow? Which path do I need to give it in the `FRANKENPHP_CONFIG` value for the worker mode?

**Comment by ricardoboss** [comment]
This line is probably responsible: https://github.com/dunglas/frankenphp/blob/878a30d92fcdde90d8be161b0d3f4078fae2c15d/caddy/frankenphp/Caddyfile#L15

If I use

```bash
docker run --rm -e FRANKENPHP_CONFIG="worker /app/public/example/worker.php" -p 80:80 -p 443:443 -v $pwd:/app/public -w /app dunglas/frankenphp
```

and then access `https://localhost/example/worker.php`, I get the expected `hello world`.

I'll leave this issue open for you to review. Feel free to close it.

**Comment by dunglas** [comment]
This is intended, the path of the URL must exactly match the path of the worker script from the document root (usually, you'll want to use `index.php`).

You can use the `rewrite` Caddy directive to rewrite the path if needed:

```Caddyfile
	# If the requested file does not exist, try index files
	@indexFiles file {
		try_files {path} worker.php
		split_path .php
	}
	rewrite @indexFiles {http.matchers.file.relative}
```

**Comment by f3l1x** [comment]
Thanks @dunglas. I've made a little frameworkless demo with this setup.

https://github.com/f00b4r/2023-10-frankenphp
