### ISSUE TITLE
Flaky TestConnectionAbortFinish test

### ISSUE THREAD

**Issue by dunglas** [dunglas/frankenphp#109]
It looks like we have a flaky test @withinboredom:

```
=== RUN   TestConnectionAbortFinish_module
    frankenphp_test.go:505: 
        	Error Trace:	/go/src/app/frankenphp_test.go:505
        	            				/go/src/app/frankenphp_test.go:80
        	            				/go/src/app/asm_amd64.s:1594
        	Error:      	Should be true
        	Test:       	TestConnectionAbortFinish_module
```

https://github.com/dunglas/frankenphp/actions/runs/3480116840/jobs/5819499909#step:5:4347

I also (rarely) get this error locally.

**Comment by withinboredom** [comment]
I think I might have a solution to get rid of the wall clock dependency... I'll get a PR together early next week.

**Comment by dunglas** [comment]
This happened again: https://github.com/dunglas/frankenphp/actions/runs/3609227709/jobs/6082289299

**Comment by withinboredom** [comment]
It's on my todo list! I've been super busy the last couple of weeks and barely written any code. I should hopefully have more time in the next few days!

**Comment by dunglas** [comment]
No worry, it's not urgent at all.
