### ISSUE TITLE
Go's garbage collector and load (benchmarks)

### ISSUE THREAD

**Issue by withinboredom** [dunglas/frankenphp#111]
While doing some load testing and comparing frankenphp to apache and fpm, I noticed that a single gc cycle from golang can screw up everything.

Here's apache:

<img width="1280" alt="Apache 200rps" src="https://user-images.githubusercontent.com/1883296/202555889-fd5aa4b1-3301-4996-b527-d2d155bb75a3.png">

Here's fpm:

<img width="1280" alt="Screenshot_20221117_212927" src="https://user-images.githubusercontent.com/1883296/202555987-a4743639-d523-47af-96a0-06e808a48806.png">

And here's frankenphp:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/1883296/202556922-95da713a-baf0-4303-bb12-40c46d5e8e32.png">

and the average graph to show the gc:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/1883296/202556963-3544dc0a-ed21-4268-8e9a-1903135c2b60.png">

This is mostly to document this behavior and if benchmarking is desired, take note to tune two environment variables:

- `GOGC`: "a parameter that picks a point in the GC CPU and memory trade-off. The key takeaway is that doubling GOGC will double heap memory overheads and roughly halve GC CPU cost, and vice versa." A value of `512` will get you approx 2-3 minutes @ 200 rps before running into 2-3s stop-the-world gc pauses. If you're doing benchmarks, and not considering memory usage, setting it "off" might be worth considering, with a noted caveat that "memory/gc tuning will be required to achieve these values long-term."
- `GOMEMLIMIT`: the maximum amount of memory to use. Due to the overhead of caddy, Go VM, and frankenphp, it should be larger than the PHP memory limit. 

Setting `GOGC=off GOMEMLIMIT=4096` gives me nearly 8 minutes at full load before a GC pause. Take note that this is mostly an issue when load testing specifically. During normal usage, it is unlikely for _every single thread_ to be in use and Go will coordinate these threads to perform a GC. When under load, there is no choice but to affect every request. In the "real world" if every server is running at 100%, there are bigger problems to worry about, so please ensure to remove these pauses from your benchmark to reflect real-world maximums in a perfectly tuned or bursty environment.

See [this guide](https://tip.golang.org/doc/gc-guide) for more information about how these parameters work.

**Comment by dunglas** [comment]
Great summary, thanks!

Is your benchmark code available somewhere or is it internal?
We should create our official benchmarks IMHO.

**Comment by withinboredom** [comment]
Here it is. It's pretty simple and nothing fancy: https://github.com/withinboredom/wp-frankenphp-load-test

Probably the most valuable bits are the kubenetes manifests.
