### ISSUE TITLE
Request path issue

### ISSUE THREAD

**Issue by lwlwilliam** [dunglas/frankenphp#1125]
### What happened?

Start the service with the command: 

```bash
frankenphp php-server -l :10000 -r /Users/wu/www
```

If the request path contains `php` words that do not represent file suffixes, a warning and fatal error will be generated. For example:

```bash
curl http://localhost:10000/php/xxx/yyy.php
```

The response is as follows:

```html
<br/>

<b>Warning</b>: Unknown: Failed to open stream: Undefined error: 0 in <b>Unknown</b> on line <b>0</b><br />

<br />

<b>Fatal error</b>: Failed opening required '/Users/wu/www/php' (include_path='.:') in <b>Unknown</b> on line <b>0</b><br />
```

If you change the request path from `/php/xxx/yyy.php` to `/phq/xxx/yyy.php` or any path that does not contain `php` words other than `yyy.php`, everything is fine.

### Build Type

Official static build

### Worker Mode

No

### Operating System

macOS

### CPU Architecture

aarch64

### PHP configuration

```shell
FrankenPHP v1.2.5 PHP 8.3.11 Caddy v2.8.4
```

**Comment by AlliBalliBaba** [comment]
You are right, this seems to be specific to the `php-server` command. @dunglas would it be fine to just change [this](https://github.com/dunglas/frankenphp/blob/dad858b69762e1f7ab7ed6d31d4db616939e35d9/caddy/php-server.go#L131) from `php` to `.php`?
