### ISSUE TITLE
Random PHP errors when in worker mode (extremely rare)

### ISSUE THREAD

**Issue by withinboredom** [dunglas/frankenphp#114]
I'm seeing random (but extremely rare: <0.5% of requests) fatal PHP errors in worker mode:

- `Cannot instantiate interface from`
- `Cannot instantiate trait from`
- `Cannot instantiate enum`
- `Cannot instantiate abstract class`

There's no interface or trait specified in the error, just to be clear, those errors are the literal messages given. The error occurs on random lines/files.

This never happens outside of worker mode and I cannot reproduce it in a smaller sample.

The relevant error messages are coming from [these lines](https://github.com/php/php-src/blob/master/Zend/zend_API.c#L1672-L1680) in php-src. It smells like some memory shenanigans but it isn't clear if it is a frankenphp bug or a PHP/extension bug.

**Comment by dunglas** [comment]
Could you try running PHP with the debug mode and core dumps enabled, and crash in the function you pointed out so we can get a stack trace?

**Comment by danilopolani** [comment]
Hey, this was a bug from PHP 8.2.1 and fixed in 8.2.2: https://github.com/php/php-src/issues/9675#issuecomment-1385057885

**Comment by withinboredom** [comment]
Nice! Frankenphp is currently on 8.2.2, so closing!
