### ISSUE TITLE
Install PHP 8.4

### ISSUE THREAD

**Issue by stephanvierkant** [dunglas/frankenphp#1161]
### Describe you feature request

**Is your feature request related to a problem? Please describe.**
PHP 8.4 will be released this month. I'd like to test my application against this version. 

**Describe the solution you'd like**
I'd like to know how I can install a new version of PHP until a new frankenphp image is released.

**Describe alternatives you've considered**
-

**Comment by dunglas** [comment]
PHP 8.4 is already tested with PHP 8.4 in the CI and supports it. For now, you have to compile PHP 8.4 manually to use it with FrankenPHP: https://frankenphp.dev/docs/compile/#compile-from-sources

We'll add an official image as soon as the stable version of 8.4 is marked.
