### ISSUE TITLE
FrankenPHP 1.3.2 images for PHP 8.3 are missing

### ISSUE THREAD

**Issue by lermontex** [dunglas/frankenphp#1194]
### What happened?

It seems that something went wrong during the last release. The images FrankenPHP 1.3.2 for PHP 8.3.* are missing on Docker Hub

![Screenshot 2024-11-24 at 00-36-36 dunglas_frankenphp Tags Docker Hub](https://github.com/user-attachments/assets/cc3586bc-1b08-4572-9c9c-59d86218e33a)

### Build Type

Custom (tell us more in the description)

### Worker Mode

Yes

### Operating System

Other (tell us more in the description)

### CPU Architecture

Other (tell us more in the description)

### PHP configuration

```shell
-
```

**Comment by lermontex** [comment]
Also, please note that PHP 8.2 images are only available with Alpine.

**Comment by withinboredom** [comment]
It looks like it reached the rate limit during the build-and-push actions: https://github.com/dunglas/frankenphp/actions/runs/11987316006/job/33422201979

**Comment by dunglas** [comment]
Fixed, thanks!
