### ISSUE TITLE
Undefined constant "GLOB_BRACE"

### ISSUE THREAD

**Issue by arnolem** [dunglas/frankenphp#1195]
### What happened?

![image](https://github.com/user-attachments/assets/c8661454-a7fd-4f00-9520-b87b2c9dfd88)

### Build Type

Standalone / Binary

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
PHP 8.3
```

**Comment by withinboredom** [comment]
This is due to using alpine/musl (standalone builds use musl), in which this constant isn't defined: https://bugs.php.net/bug.php?id=72095

This isn't a Frankenphp bug.

**Comment by arnolem** [comment]
Ok but i'm not on Alpine.
I use https://frankenphp.dev/install.sh on Ubuntu 24.04

**Comment by dunglas** [comment]
This script downloads the static binary, which is compiled with musl. Try to use the Debian-based Docker image or to compile from sources.
