### ISSUE TITLE
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:0A000086:SSL routines::certificate verify failed

### ISSUE THREAD

**Issue by arnolem** [dunglas/frankenphp#1196]
### What happened?

![image](https://github.com/user-attachments/assets/40481444-deae-4423-86a2-641596e29260)

### Build Type

Standalone binary

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
PHP 8.3
```

**Comment by withinboredom** [comment]
This is a known issue: https://frankenphp.dev/docs/known-issues/#troubleshooting-tlsssl-issues-with-static-binaries. You need to configure your binary to point to the appropriate CA certificate bundle.
