### ISSUE TITLE
Documentation: how to build static binaries with caddy modules included

### ISSUE THREAD

**Issue by vittodevit** [dunglas/frankenphp#1208]
The script to build static binaries builds frankenphp directly. 
Is there any way to build it with caddy modules included?

**Comment by dunglas** [comment]
This is doable but we need to modify https://github.com/dunglas/frankenphp/blob/main/build-static.sh to use xcaddy (PR welcome!)

**Comment by PhilETaylor** [comment]
Apple "Intelligence" ... 
I would love to see the PR to convert github.com to caddy ;-) 

![ScreenShot-2024-11-26-15 30 00](https://github.com/user-attachments/assets/d2234e0c-1775-4eb3-abac-fe07026777f3)
