### ISSUE TITLE
1.3.2 vs Coraza

### ISSUE THREAD

**Issue by Simbiat** [dunglas/frankenphp#1211]
### What happened?

Looks like something happened in 1.3.2 (compared to 1.2.4) and now it won't load a file included in CRS config. [Caddy config](https://github.com/Simbiat/simbiat.ru/blob/master/config/frankenphp/caddy.json5) (note that it's JSON5, not JSON) has `Coraza WAF` section, which has `Include /usr/local/php/config/crs-setup.conf`. File exists, has proper permissions, but on 1.3.2 Franken/Caddy fail to load it:
```
2024-11-26 19:12:40 Error: loading initial config: loading new config: loading http app module: provision http: server server_0: setting up route handlers: route 1: loading handler modules: position 0: loading module 'waf': provision http.handlers.waf: invalid WAF config from string: failed to readfile: read /usr/local/php/config/crs-setup.conf: invalid argument
```
Change it back to Franken 1.2.4 (and PHP to 8.3.10, as latest available) - loads totally fine. Same with 1.2.5 (but that one has the issue with expanding error macros #1016).
On 1.3.2 it fails even if the file is empty, which I tried to rule out some issue in the [CRS config](https://github.com/Simbiat/simbiat.ru/blob/master/config/frankenphp/crs-setup.conf). But comment out the line - loads fine (CRS will fail, though due to lack of config).

Any ideas, what it may not like?

[Docker compose](https://github.com/Simbiat/simbiat.ru/blob/master/docker-compose.yml)
[Docker file](https://github.com/Simbiat/simbiat.ru/blob/master/config/frankenphp/Dockerfile) (with 1.32 build)

### Build Type

Docker (Debian Bookworm)

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
Not relevant
```

**Comment by Simbiat** [comment]
Don't know if it's relevant but, I am also getting these errors:
```
2024-11-26 19:39:16 2024-11-26 17:39:16.105872583 +0000 UTC m=+9.070091925 write error: can't open new logfile: open /app/logs/access.log: no such file or directory
```
even the directory exists. File does not. And I can't touch it from under container for some reason, although caddy.log in the same folder is being created and updated totally fine

**Comment by Simbiat** [comment]
It looks exactly the same, only the FrankenPHP version is different, that's why I created the issue in this repo. I have no idea why there is a difference in behavior, but my guess is that it may be related to some dependencies that differ between the versions. Have not tried a wildcard as suggested for Traefik, since I have only 1 file, but I will try that later today and let you know if that helps.

**Comment by rse173** [comment]
Hey, I had the same issue, take a look at this issue from Coraza :

[https://github.com/corazawaf/coraza/issues/1208](url)

It's fixed on the main branch, you can build caddy adding the branch name on coraza-caddy module :
`--with github.com/corazawaf/coraza-caddy/v2@main`

**Comment by Simbiat** [comment]
Yup, using `v2@main` works. I guess it stops working in FrankenPHP 1.3.2 because it's using newer version of Go, then?

**Comment by dunglas** [comment]
Closing as fixed upstream and not FrankenPHP-related. Thanks for sharing the fix @rse173!
