### ISSUE TITLE
Looping restarting worker on laravel

### ISSUE THREAD

**Issue by rymesaint** [dunglas/frankenphp#1251]
### What happened?
I got a restarting worker looping when i access the app

```
{
    servers {
    	enable_full_duplex
    }

	auto_https off

	frankenphp {
		num_threads 6
		worker {
			file public/index.php
			num 2
			watch .env
			watch app/*.php
			watch app/**/*.php
			watch app/**/**/*.php
		}
	}
}
```
```
localhost {
	# Set the webroot to the public/ directory
	root * public/

	# Enable compression (optional)
	encode zstd br gzip

    # Enable static file serving for assets
    file_server

	php_server

	log {
        output file /var/log/localhost/access.log
        level INFO
    }
}
```

![image](https://github.com/user-attachments/assets/983cf6d9-86ba-41fe-9583-901633647432)

![image](https://github.com/user-attachments/assets/323df2bc-c51d-4044-9985-a67ca714f87b)

### Build Type

Custom (tell us more in the description)

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
i use default php configuration from frankenphp
```

**Comment by dunglas** [comment]
You need to use the worker script provided by Octane when using Laravel. Using `index.php` will not work.
