### ISSUE TITLE
HTTP placeholder inside php_server block not being populated

### ISSUE THREAD

**Issue by AirBair** [dunglas/frankenphp#1267]
Hello,

Sorry to repost here, i've originally posted that in the discussions section last September but without answers and still encountering the behavior to this day it might worth it.

Feel free to close here or there.

### Discussed in https://github.com/dunglas/frankenphp/discussions/1057

<div type='discussions-op-text'>

<sup>Originally posted by **AirBair** September 30, 2024</sup>
Hi,

Motivated by the API-Platform Conference, I'm trying to configure FrankenPHP behind an apache reverse proxy which has Kerberos authentication. To do so, I forward the authenticated user with the following directive: `RequestHeader set X-Proxy-Remote-User %{REMOTE_USER}`

In NGINX in place of FrankenPHP, this works with the following configuration:

```
fastcgi_param REMOTE_USER $http_x_proxy_remote_user;
```

To replicate this in FrankenPHP/Caddy, I modified the Caddyfile like this:

```
{$SERVER_NAME:localhost} {
        # ...
        php_server {
            env REMOTE_USER {http.request.header.X-Proxy-Remote-User}
        }
}
```

But the variable is not being populated with the actual value of the header:

![image](https://github.com/user-attachments/assets/90944cf9-8819-4cf1-b934-f7130f139a53)

If I move the variable assignment outside of the php_server block, the actual value is passed correct, but i also got an HTTP_ prefix as expected

```
{$SERVER_NAME:localhost} {
        # ...
        php_server
        request_header +REMOTE_USER {http.request.header.X-Proxy-Remote-User}
}
```

![Capture d'écran 2024-09-30 173519](https://github.com/user-attachments/assets/7953bc6c-5362-48fe-94d7-5f619b1acf16)

It seems that placeholders (e.g., {http.request.header.X-Proxy-Remote-User}) don't work inside the php_server block, but I couldn't find any documentation stating whether this is intended behavior or if it's a misconfiguration on my part.

I can work around by using the HTTP_REMOTE_USER header, but I’d appreciate any insights to confirm or help me understand.

Thanks for your feedback.</div>

**Comment by AlliBalliBaba** [comment]
Which version of FrankenPHP are you using? This seems to work on version 1.3.3 at least:


![image](https://github.com/user-attachments/assets/2f6bd9b6-91b4-47cc-9e18-35681470fb09)
![image](https://github.com/user-attachments/assets/fdf51955-584d-43a6-a2fb-6394d201c0fc)
![image](https://github.com/user-attachments/assets/646c259b-ea12-4c0c-bc70-ff73cf9d678d)

**Comment by AirBair** [comment]
Damn, I was still using an old tag on my testing environment (1.2.5) 😓

Indeed it works since v1.3.0, thanks probably to your PR #1018 !

Sorry for the oversight and thank you for pointing it out.
