### ISSUE TITLE
 ERROR  FrankenPHP asset not found.  

### ISSUE THREAD

**Issue by pushpak1300** [dunglas/frankenphp#1276]
### What happened?

https://github.com/laravel/octane/blob/2.x/src/Commands/Concerns/InstallsFrankenPhpDependencies.php#L64

is breaking octane install command

Because of the latest [version release](https://github.com/dunglas/frankenphp/releases/tag/v1.3.4) and missing x86_64 build

### Build Type

Standalone binary

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
php8.3
```

**Comment by amermchaudhary** [comment]
I can verify the bug. Facing the same problem. Laravel Octane expects an asset with the exact name `frankenphp-linux-x86_64`. 

For anyone who needs a quick immediate workaround for laravel octane modify the following 
**File:** `vendor/laravel/octane/src/Commands/Concerns/InstallsFrankenPhpDependencies.php`
**Line number:** `81`
Change the ending of the url from `latest` to `187816876`

**Comment by brunostalo** [comment]
I'm still getting the error

RuntimeException
FrankenPHP asset not found.
at vendor/laravel/octane/src/Commands/Concerns/InstallsFrankenPhpDependencies.php:125
121▕
122▕ return $path;
123▕}
124▕
➜ 125▕ throw new RuntimeException('FrankenPHP asset not found.');
126▕}
127▕
128▕ /**
129▕ * Ensure the installed FrankenPHP binary meets Octane's requirements.
+15 vendor frames
16 artisan:13
Illuminate\Foundation\Application::handleCommand()

Have you found any solution?

My application runs on laravel.

A while ago I even managed to upload the binary but now it gives this error again.

**Comment by pushpak1300** [comment]
The build is still failing. @dunglas

**Comment by vipex** [comment]
Again, in the release `v1.11.2` the `frankenphp-linux-aarch64-gnu` is missing!

@dunglas can the pipeline be re-ran?

**Comment by henderkes** [comment]
@vipex the php CDN in the US is down so we can't get php source so we can't compile (in CI as GitHub uses US infrastructure).
