### ISSUE TITLE
http.encoders.br missing error on 1.3.4

### ISSUE THREAD

**Issue by haringsrob** [dunglas/frankenphp#1279]
### What happened?

Note: Working with laravel octane.

Laravel octane downloads the latest binary by default. **1.3.4**

However, on startup (all default config no changes) it throws:

`Error: adapting config using caddyfile: parsing caddyfile tokens for 'route': parsing caddyfile tokens for 'encode': finding encoder module '': module not registered: http.encoders.br, at vendor/laravel/octane/src/Commands/stubs/Caddyfile:28, at vendor/laravel/octane/src/Commands/stubs/Caddyfile:38.`

```
	route {
		root * "{$APP_PUBLIC_PATH}"
		encode zstd br gzip <----------- THIS LINE ERRORS

		# Mercure configuration is injected here...
		{$CADDY_SERVER_EXTRA_DIRECTIVES}

		php_server {
			index frankenphp-worker.php
			# Required for the public/storage/ directory...
			resolve_root_symlink
		}
	}
```

Rolling back to 1.3.3 everything works fine.

### Build Type

Standalone binary

### Worker Mode

Yes

### Operating System

macOS

### CPU Architecture

Apple Silicon

### PHP configuration

```shell
-
```

**Comment by agusmaulanayusufnoor** [comment]
try frankenphp php-server -r test/ display error : 
Error: module not registered: http.encoders.br

**Comment by dunglas** [comment]
@agusmaulanayusufnoor this has been fixed in `main`. I'm working on a new release that will include this fix.

**Comment by pushpak1300** [comment]
I think build is still not completed.

**Comment by MSayib** [comment]
> @agusmaulanayusufnoor this has been fixed in `main`. I'm working on a new release that will include this fix.

cant wait, thanks

**Comment by haringsrob** [comment]
You can pin it to an older version for now to mitigate.
