### ISSUE TITLE
error starting server

### ISSUE THREAD

**Issue by agusmaulanayusufnoor** [dunglas/frankenphp#1283]
i just try frankenphp with laravel app in ubuntu server 22.04
php artisan octane:frankenphp => show error :
   INFO  Error: adapting config using caddyfile: parsing caddyfile tokens for 'route': parsing caddyfile tokens for 'encode': finding encoder module '': module not registered: http.encoders.br, at vendor/laravel/octane/src/Commands/stubs/Caddyfile:28, at vendor/laravel/octane/src/Commands/stubs/Caddyfile:38.  

frankenphp php-start show error :
Error: module not registered: http.encoders.b

any missing config?

**Comment by zhanang19** [comment]
See #1279 #1280
