### ISSUE TITLE
[QUESTION] IS LARAVEL OCTANE NEED NGINX?

### ISSUE THREAD

**Issue by ezhasyafaat** [dunglas/frankenphp#1292]
Hi all, i hope someone will reply this

i need to deploy laravel apps in production, but i want to use frankenphp, but the issue is i dont want to use NGINX anymore. If i see at the documentaion laravel there still use NGINX with laravel octane, so i decide to use only frankenphp.

what i want to ask is
can you give me step by step how to run frankenphp worker mode + laravel in production server without laravel octane

because i already try it with only frankenphp, first time i try i can access the apps with the server ip, and i stop it then i run it again, suddenly i cant access the apps anymore, also if i try to use worker mode i got error like this

```bash
PANIC	too many consecutive worker failures
```

**Comment by dunglas** [comment]
You don't need NGINX with Octane+FrankenPHP. FrankenPHP is built on top of Caddy, which is a production-ready web server.

No need to put NGINX in front of it.

**Comment by ezhasyafaat** [comment]
so i just need to run octane:start in production?

**Comment by dunglas** [comment]
Yes, or `frankenphp run` with your own Caddyfile.
