### ISSUE TITLE
How to use this outside of docker?

### ISSUE THREAD

**Issue by hj-collab** [dunglas/frankenphp#130]
Hi,

Thank you very much for the amazing work done.  I really wanted to use Nginx Unit but lack of gzip compression prevents me from using it. I have no complaint with Caddy as it supports all the features I need. Now I can use FrankenPHP to enjoy faster performance like Nginx unit because of vertical integration with PHP without missing the features and ease of Caddy.

I am using Caddy compiled with Cloudflare DNS Module right now with PHP-FPM. I am not using Docker. How do I use this without docker? Will there be any performance improvement for wordpress websites? I understand they won't run in worker mode and only benefit I'll get is easy integration here. Please let me know. Thanks again!

**Comment by dunglas** [comment]
You can try this to run it without Docker: https://github.com/dunglas/frankenphp/blob/main/docs/compile.md

Including the extra Caddy module is possible with `xcaddy` (as usual), just add the `github.com/frankenphp/caddy` module (you'll need a local installation of PHP as described in the source).

The main performance gains for Wordpress silk probably be related to Caddy (HTTP3 etc). Benchmarks welcome!
