### ISSUE TITLE
PHPStorm cannot use xdebug

### ISSUE THREAD

**Issue by withinboredom** [dunglas/frankenphp#141]
This is probably on PHPStorm, but it fails to do remote step debugging because `$_SERVER['SERVER_PORT']` is unset.

From looking at the code around https://github.com/dunglas/frankenphp/blob/main/cgi.go#L126, it looks like it should be set, but a simple `var_dump($_SERVER)` shows that it is indeed, not set.

**Comment by withinboredom** [comment]
I filed https://youtrack.jetbrains.com/issue/WI-71443 with them as well.

**Comment by dunglas** [comment]
We should also fix it on our side, we can easily set this variable.

**Comment by withinboredom** [comment]
It works fine when it is truly remote (like running on a server). I only get this error when running on `localhost` or with a wildcard SERVER_NAME, like `:80`. Seems to be set properly when `SERVER_NAME` is an actual domain.

**Comment by francislavoie** [comment]
FWIW, in Caddy's fastcgi transport, we made a change to ensure a default of `80` or `443` is set for `SERVER_PORT` in https://github.com/caddyserver/caddy/pull/4572 based on the incoming request's scheme. It looks like that code was copied from Caddy (identical comment) so I suggest it can be updated to match.

**Comment by dunglas** [comment]
Yes it was. Maybe could we share it in some way btw.

**Comment by francislavoie** [comment]
We have https://github.com/caddyserver/caddy/issues/4378 which is related to that, i.e. splitting out the fastcgi transport to its own package. If you'd like to help with that, that'd be cool.
