### ISSUE TITLE
Version Number for Frankenphp (frankenphp version cmd)

### ISSUE THREAD

**Issue by DracoBlue** [dunglas/frankenphp#143]
Hello,

I would like to work on e.g. an alpine package for a testing build for frankenphp. But this requires a version number for frankenphp.

Edit:
```
/usr/src/app $ frankenphp version
v2.6.2 h1:wKoFIxpmOJLGl3QXoo6PNbYvGW4xLEgo32GPBEjWL8o=
```

This looks like the caddy version https://github.com/caddyserver/caddy/releases/tag/v2.6.2 . Can I use this? Or will there be specific git tags on frankenphp available?

Best regards

**Comment by en-jschuetze** [comment]
any opinion on this @dunglas?

**Comment by DracoBlue** [comment]
any opinion on this @dunglas?

**Comment by withinboredom** [comment]
There's already an issue open for it: See #112

**Comment by DracoBlue** [comment]
I don’t think this is the same topic.

i would like to have a franken php 0.1.x or something to properly tag frankenphp itself for packaging it in e.g. alpine.

The ticket #112  is on tagging a docker tag with the php verison it was built for - IMHO a different matter.

**Comment by DracoBlue** [comment]
If I execute:

```
$ frankenphp version
v2.6.2 h1:wKoFIxpmOJLGl3QXoo6PNbYvGW4xLEgo32GPBEjWL8o=
```

it looks like I get the Caddy Version. I can take this version number if it makes sense.
