### ISSUE TITLE
ssl

### ISSUE THREAD

**Issue by rafalohaki** [dunglas/frankenphp#149]
im getting ERR_SSL_PROTOCOL_ERROR
is there a way to server files with working ssl?
i want to use public ip or able to link it behind cloudflare with domain
is there env for custom crt?

**Comment by dunglas** [comment]
Could you tell us a bit more about your config (domain name or IP you use, real or self-signed cert...)?
FrankenPHP uses Caddy under the hood, refer to its documentation regarding TLS: https://caddyserver.com/docs/automatic-https

**Comment by rafalohaki** [comment]
I used default command ```docker run -v $PWD:/app/public \
    -p 80:80 -p 443:443 \
    dunglas/frankenphp```
    and tried to access with public ip and domain name behind cloudflare. both with ssl error

**Comment by dunglas** [comment]
As stated in the readme, using IPs requires additional configuration: https://caddyserver.com/docs/automatic-https#hostname-requirements

**Comment by rafalohaki** [comment]
ok, i edited and binded new config. seems Automatic HTTPS is working and website working too. great project

**Comment by rafalohaki** [comment]
btw there is no php.ini in /usr/local/lib/php.ini in docker
root@b44674c5bdca:/app# cat /usr/local/lib/php.ini
cat: /usr/local/lib/php.ini: No such file or directory

**Comment by withinboredom** [comment]
You need to copy one (from [https://hub.docker.com/_/php](https://hub.docker.com/_/php#Configuration:~:text=It%20is%20strongly%20recommended%20to%20use%20the%20production%20config%20for%20images%20used%20in%20production%20environments!)):

```
mv $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini
# or
mv $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini
```

**Comment by keskinonur** [comment]
I solve similar problem with these configurations:

- Enable Cloudflare DNS proxy for SSL
- Leave your server name as a domain name (**example.com**) without adding **http://** or **:80**
- Inject global configuration for Frank / Caddy

    `CADDY_GLOBAL_OPTIONS="local_certs"`

- Restart your server
- Enjoy your SSL managed by Cloudflare
