### ISSUE TITLE
Can frankenphp be embedded in another Go app

### ISSUE THREAD

**Issue by lonnietc** [dunglas/frankenphp#150]
Hello,

A bit new here, but I am wondering if Frankenphp can be embedded inside another Go app that is being developed to have its own PHP server running as well?

Thanks

**Comment by dunglas** [comment]
Definitely: https://pkg.go.dev/github.com/dunglas/frankenphp

**Comment by lonnietc** [comment]
That's wonderful to hear and I am looking for other components for the project of which one will probably be an eCommerce store as the frontend that will talk to a backend via an API. 

Thanks again and have a great day

**Comment by lonnietc** [comment]
Hello,  

The project that I am working to evaluate for development could have PHP 7.4 embedded in a Golang application. I am also wondering if the Frankenphp can allow for embedding the extensions that may be needed as well?

My guess would be that the security level of using Frankenphp would be about the same as embedding any other web -based application that you might have in some other languages or web servers as well, right?

Thanks again and have a good day

**Comment by lonnietc** [comment]
Hello,

I have found a new PHP eCommerce framework that I might try to use with FrankenPHP but it required:

PHP>8.0
sylius/sylius 1.11.x

Can this work with FrankenPHP?

Thanks in advance

**Comment by dunglas** [comment]
As long as it supports PHP 8.2, yes.
