### ISSUE TITLE
Bug: Request data truncated > 3963 bytes

### ISSUE THREAD

**Issue by dennisoehme** [dunglas/frankenphp#182]
Hey guys,

I'm just using frankenphp for a simple Symfony-based API application. One of these REST endpoints receives _larger_ JSON data as POST request.

Unfortunately the 3964. and all following characters are truncated from the `php://input` which results into an invalid JSON string.

By using the Symfony CLI web-server / `php -s` I don't see that strange behavior. I ported the application from Nginx/PHP-FPM to frankenphp. The previous setup works as expected, too.

So, not sure, if this is a issue in caddy and/or frankenphp implementation or some strange configuration fuckup.

To reproduce this issue I created a small repo: https://github.com/dennisoehme/caddy-frankenphp-issue

Any idea?

**Comment by dunglas** [comment]
I'm able to reproduce the problem with Caddy. I added a test in #185 proving that it's not related to the FrankenPHP library itself. It's either a bug in the Caddy module or in Caddy itself.
