### ISSUE TITLE
ARM64 container image

### ISSUE THREAD

**Issue by jasonmccallister** [dunglas/frankenphp#19]
Running this on an Apple M1 chip give the following warning:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Would be useful to have ARM variants of the container image.

**Comment by dunglas** [comment]
We need to set up a proper CI/CD pipeline (likely using [GoReleaser](https://goreleaser.com/)).

**Comment by dunglas** [comment]
ARM images are now available!
