### ISSUE TITLE
Adjust --help

### ISSUE THREAD

**Issue by Chris53897** [dunglas/frankenphp#192]
Hi. The command `frankenphp --help` in the docker container, look like an (extended) `caddy --help` call.

It would be better to have replace almost all occurrences of `caddy` with `frankenphp` in the output.
There are probably a lot more places, where this needs to be replaced.

Or create an alias for caddy an call frankenphp. But this could lead to conflicts and unexpected behaviour.

**Comment by dunglas** [comment]
I don't think that it's currently possible, and it's probably not desirable. The FrankenPHP binary is Caddy with the FrankenPHP module pre-loaded. For all web server related use cases (and all CLI options), you must refer to Caddy's documentation, not ours.

**Comment by Chris53897** [comment]
ok. I will close this
