### ISSUE TITLE
Symfony integration with stateful services

### ISSUE THREAD

**Issue by DubbleClick** [dunglas/frankenphp#207]
Since FrankenPHP keeps everything loaded in memory between requests, it can lead to unexpected behaviour for stateful services. As a general rule of thumb it's a good idea to handle resetting of stateful services in the service itself, however that's out of our control for things like Doctrine's UOW/EntityManager and might require refactoring.

What's the recommended strategy for this - should users implement a middleware of their own (and a compiler pass in case of symfony), or is a bundle planned (could scan for the existence of entity managers and reset them and maybe reset classes tagged with an attribute too)?

I'm aware this repository isn't the correct place for the implementation. If it's generally appreciated I'll be happy to create a bundle for it.

Attribute I'm thinking about: https://github.com/symfony/symfony/blob/6.4/src/Symfony/Contracts/Service/ResetInterface.php

**Comment by dunglas** [comment]
Symfony already handles this, thanks to this interface and the runtime component. All you have to do is to install `runtime/frankenphp-symfony`.

Suppose you have problems with native Symfony services. Please report it to the Symfony GitHub repository.

**Comment by DubbleClick** [comment]
Yep, unfortunately doctrines EntityManager does not properly continue working between requests with the frankenphp runtime. Every ~6th page visit with ~100 entities loaded crashes and leads to a reload. This problem exists with both swoole and frankenphp - a roadrunner bundle fixes it with middleware: https://github.com/Baldinof/roadrunner-bundle/blob/3.x/src/Integration/Doctrine/DoctrineORMMiddleware.php#L22

What's the correct place to bring this up then? It's obviously not an issue with php-fpm which the symfony officially supports.

**Comment by dunglas** [comment]
To me this should be reported to Symfony (Symfony tried to officially support FrankenPHP/Swoole/RoadRunner etc in addition to FPM) and probably fixed in https://github.com/php-runtime/runtime using a workaround similar to what is done in the middleware.

**Comment by DubbleClick** [comment]
Thank you, will do.
