### ISSUE TITLE
Fail in the last run in Techempower benchmark

### ISSUE THREAD

**Issue by joanhey** [dunglas/frankenphp#218]
In the last run of the bench, Franken failed in php and worker mode. Nothing changed in the code or dockerfile.

Dockerfile: https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/php/php-franken.dockerfile

**Docker build and run log.**
Last run with the problem:
https://tfb-status.techempower.com/unzip/results.2023-09-19-12-56-11-847.zip/php-franken

Run before without problem:
https://tfb-status.techempower.com/unzip/results.2023-09-12-22-11-01-684.zip/results/20230906143924/php-franken

If you need more information, only ask me for it.

PD: also fail the tests locally.
`./tfb --mode verify --test php-franken`

**Comment by joanhey** [comment]
Fixed moving the `Caddyfile` from `/etc/` to `/etc/caddy/`.
I don't understand how was working before.

https://github.com/TechEmpower/FrameworkBenchmarks/pull/8440

Now we can check the results with the beta1

**Comment by dunglas** [comment]
Thanks @joanhey! The path changed recently to be consistent with official Caddy images.
