### ISSUE TITLE
Multi tenancy in worker mode

### ISSUE THREAD

**Issue by DubbleClick** [dunglas/frankenphp#219]
In the documentation it's specified that you can pass env variables to the worker. Is it also possible to spawn workers per-vhost? E.g.

```
frankenphp {
        # num_threads 4
        worker {
            file /var/www/app/public/index.php
            num {{ half num of cpu cores }}
            env APP_ENV {{ depends-on-the-host }}
        }
    }

staging.example.com {
    route {
        php {
            root /var/www/app/public
            env APP_ENV staging
        }
    }
}

prod.example.com {
    route {
        php {
            root /var/www/app/public
            env APP_ENV prod
        }
    }
}
```

Or even spawn two entirely different workers?

```
app.example.com {
    route {
        php {
            root /var/www/app/public
            # spawn worker for this?
        }
    }
}

otherapp.example.com {
    route {
        php {
            root /var/www/otherapp/public
            # spawn different workers for this?
        }
    }
}
```

**Comment by francislavoie** [comment]
One way to do this would be to have "named workers" so you can have more than one worker configured in global options, then refer to a specific one in the site block.

**Comment by DubbleClick** [comment]
> One way to do this would be to have "named workers" so you can have more than one worker configured in global options, then refer to a specific one in the site block.

Thank you for the answer, the documentation doesn't seem to mention named workers, though.

I can't seem to find it in the source either, looking at https://github.com/dunglas/frankenphp/blob/eca8cc735064fe5c56fcb10694c9ee3726acc32d/caddy/caddy.go#L41-L48

So I take it this has to be implemented first?

**Comment by dunglas** [comment]
Multi-workers is already supported, but not @francislavoie proposal. It would be nice to add it!

**Comment by DubbleClick** [comment]
Okay, I'll see if I can implement it when I'm done with ext-imap and ext-ldap in spc. The option to run multiple sites is crucial - luckily it's possible without workers for now so the switch will be easy later.

**Comment by dunglas** [comment]
This hack should also do the trick (as a workaround):

```Caddyfile
{
    frankenphp {
        worker /var/www/staging/public/index.php
        worker /var/www/prod/public/index.php
    }
}

staging.example.com {
    root /var/www/staging/public/
    // ...
}

prod.example.com {
    root /var/www/prod/public/
    // ...
}
```

And if you need to share some files between prod and staging, use symlinks. WDYT?

**Comment by DubbleClick** [comment]
Oh that's smart, thank you. Will definitely add it to the documentation later.

I've got php-imap and php-ldap to compile now so they should be ready for the static binaries soon, but I'm not sure what the best place is to enquire whether php-imap is thread safe or not. The GitHub repository or a mailing list?

**Comment by terefang** [comment]
is there a timeframe for ldap ?

**Comment by DubbleClick** [comment]
It's already merged.

**Comment by francislavoie** [comment]
For reference: https://github.com/dunglas/frankenphp/pull/203

**Comment by terefang** [comment]
so it will be in the next rc and/or in 1.0 final ?

**Comment by DubbleClick** [comment]
it's already in the current rd...?

**Comment by terefang** [comment]
i am using the 1.0.0.rc2 static musl version from the release page.

the phpinfo() page does not show a ldap section

**Comment by DubbleClick** [comment]
https://github.com/dunglas/frankenphp/compare/v1.0.0-rc.2...main

You're right, it's not in current RC yet. Sorry for the confusion.

You can fork this repo and manually build it with docker, or trigger a workflow. I'd upload you a binary, but I'm not sure if that's discouraged here since authenticity couldn't be verified.

**Comment by terefang** [comment]
no problem, i can wait to official release
