### ISSUE TITLE
php-imap alternative

### ISSUE THREAD

**Issue by DubbleClick** [dunglas/frankenphp#226]
I am working on adding ext-imap to static-php-cli and discovered that it's not thread safe and shouldn't be compiled with --enable-zts.

In other words, ext-imap won't be compatible with FrankenPHP. For one, that should be documented and second, maybe we should recommend an alternative.

There's [php-imap2](https://github.com/javanile/php-imap2) which is barely maintained and [php-imap](https://github.com/Webklex/php-imap) which appears maintained, but requires a complete rewrite of application code.

**Comment by dunglas** [comment]
Maybe can we add a list of supported and unsupported extensions in the documentation? But maybe a list of extensions supporting ZTS exists?

This isn't very related to FrankenPHP, any thread-safe extension should work with FrankenPHP (as well as with the other SAPIs needing ZTS).

**Comment by DubbleClick** [comment]
I think this is definitely FrankenPHP related as it directly affects compatibility with existing code bases. Or is ZTS only a requirement for worker mode?

**Comment by dunglas** [comment]
ZTS is a requirement for FrankenPHP, as well as for several other SAPIs. But the problem is in php-imap code base and should fixed there

**Comment by dunglas** [comment]
I cannot find an issue about that in the official PHP bug tracker by the way. Do you know if it has been reported?

**Comment by DubbleClick** [comment]
Yes, it's known: https://www.php.net/manual/en/imap.installation.php

Unfortunately the imap extension is code from the University of Washington - the author died in 2007 and the extension hasn't been maintained since. There are two patches from 2007 and 2p14 to make it compatible with OpenSSL 1.1.1/3.0, but that's it.

**Comment by DubbleClick** [comment]
https://github.com/php/php-src/issues/12322#issuecomment-1741265826

PHP considers unbundling the extension entirely, so it's probably best to recommend an alternative anyhow.

**Comment by ThomasLandauer** [comment]
[`javanile/php-imap2`](https://github.com/javanile/php-imap2) works for me.
