### ISSUE TITLE
segfault after upgrading to latest symfony docker example

### ISSUE THREAD

**Issue by wizhippo** [dunglas/frankenphp#227]
I noticed changes in the symfony docker example and upgraded a project accordingly.

It segfaults and I have attached the log file.
[segfault.log](https://github.com/dunglas/frankenphp/files/12731961/segfault.log)

Not sure if it is of interest to you or not or related to the segfault branch I see in the repo.

**Comment by dunglas** [comment]
Thanks for the report.

Could you try to pull the latest version of the Alpine image to see if it helps?

Also, does the problem occurs when building the Symfony cache?

If possible, it would be great to have access to the project (privately) to debug and fix the issue.

**Comment by wizhippo** [comment]
This is using the latest image dunglas/frankenphp:latest-alpine that was just pulled today.

The issue does not happen when building the cache.  Also does not happen on all requests.

You are welcome to have access to the repo.  i sent you an invite it's in the franckenphp branch if you want to take a looks.  Nothing really private there, just have not made it public as just a testing project.

**Comment by dunglas** [comment]
Thank you! I'll take a look tomorrow.

**Comment by wizhippo** [comment]
just to follow-up I rebuilt today and found:

dunglas/frankenphp:latest works without segfault
dunglas/frankenphp:latest-alpine segfaults

Not sure if that helps at all

**Comment by dunglas** [comment]
It does. It's maybe again related to https://github.com/dunglas/frankenphp/pull/223. Could you try to increase again the thread stack size to see if this still segfault?

**Comment by wizhippo** [comment]
That looks like it was it.  Changing stack-size=0x80000 to stack-size=0x90000 looks to have fixed my issue.

**Comment by wizhippo** [comment]
I have removed my project, pull my repo an rebuilt.  It is now working without a segfault so I will close for now. If they return I will reopen
