### ISSUE TITLE
[Feature request] Ability to periodically ping TCP connections in worker mode

### ISSUE THREAD

**Issue by bpolaszek** [dunglas/frankenphp#233]
Hey there,

I tried playing with FrankenPHP a little (in worker mode) and I was wondering if it exposes some PHP API to hook into the worker process.

My main concern is that in worker mode, FrankenPHP receives a first request which performs some DB queries, thus opening a DB connection which will be reused for further requests. Except, no traffic occurs for a while, and when comes the time for the worker to process another request, the DB connection is gone, resulting in the app throwing an exception (it may reconnect at this moment of course, but it has a cost).

In ReactPHP world, this could be easily handled by some snippet like this:

```php
use React\EventLoop\Loop;

// Ensure connection remains open
Loop::addPeriodicTimer(10, fn () => $db->query('SELECT 1'));
```

Is there something similar in FrankenPHP? Or is there something planned about this in the near future?

_(Side note: it's not really an "issue", maybe you could enable Discussions on this repository ?)_

**Comment by DubbleClick** [comment]
I think it's acceptable to handle this at the start of a request. If the connection has gone stale, you could recreate it. Shouldn't happen during active hours and if it were to happen once every thousand requests, it wouldn't be perceptible anyway.

**Comment by bpolaszek** [comment]
Yes, probably - maybe that's something that documentation should tell, because PHP developers are rarely faced with that kind of issues, and with FrankenPhp this is likely to happen. By default Doctrine just crashes and no requests can be served anymore.

**Comment by DubbleClick** [comment]
> PHP developers are rarely faced with that kind of issues

Hah, imagine my confusion when I took over a php project and realised that a third party server is firing up my code and killing the process after! Definitely the biggest contrast to every other language I've been using.

**Comment by dunglas** [comment]
We definitely need to fix this Doctrine behavior at least in Symfony (work in progress) and to improve the documentation to make it clear that similar issues can happen if devs aren't careful.

**Comment by dunglas** [comment]
The DB problem has been fixed by Symfony in https://github.com/symfony/symfony/pull/53214.

It's now possible to handle this kind of use case userland in the worker script it self by following @DubbleClick's strategy.
