### ISSUE TITLE
Seeing "maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined" when starting frankenphp

### ISSUE THREAD

**Issue by ruudk** [dunglas/frankenphp#251]
Using v1.0.0-beta.1 on MacOS Sanoma I'm getting this when starting frankenphp:
```console
$ frankenphp run
2023/10/09 09:10:24 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
```

**Comment by dunglas** [comment]
This is normal of you aren't running FrankenPHP in a constrained container, but yes we could hide this log, or at least log with Uber Zap to have a structured entry.

We use this package, which supports custom logging: https://github.com/uber-go/automaxprocs
