### ISSUE TITLE
How to install php extensions?

### ISSUE THREAD

**Issue by dylanblokhuis** [dunglas/frankenphp#26]
Installing a php8.2-{extension} and moving the `.so` into `/usr/local/lib/php/extensions/no-debug-zts-20220829` will end up with a `core_symbols` error.

**Comment by dunglas** [comment]
Your extensions must be compiled with ZTS enabled.

**Comment by dylanblokhuis** [comment]
Thanks, got it. I managed to add extensions by adding ``--with-{extension}`` flags while building the frankenphp branch of php-src.

**Comment by Pierstoval** [comment]
Shouldn't we compile all extensions in the docker image and allow users to use "extension=..." in their custom php.ini conf?

**Comment by dunglas** [comment]
This could indeed be a good idea. How does the official PHP image? The Docker image needs to be entirely revamped anyway, it could be improved a lot.

**Comment by Pierstoval** [comment]
I'm working right now on allowing to customize php.ini in a more common way, but if we want to compile everything, I guess we can add `--enable-all` in the "configure" call, add the missing phpize dependencies, and it should be doable.

**Comment by withinboredom** [comment]
Is there any way to allow it to "just work" with https://github.com/mlocati/docker-php-extension-installer?

**Comment by dunglas** [comment]
See https://github.com/dunglas/frankenphp/pull/29#issuecomment-1280549452

**Comment by dunglas** [comment]
Fixed by #33
