### ISSUE TITLE
feat: an easy way to add caddy module

### ISSUE THREAD

**Issue by divine** [dunglas/frankenphp#267]
Hello,

There is should be an easy way to add additional caddy modules to the build process.

Currently:

1. Fork
2. cd caddy && go get caddy module
3. Modify main.go and add module

Always trying to sync the forked repository is indeed pain.

Basically, I'd like something like `xcaddy` builder:

`xfrankenphp build  --with github.com/caddyserver/ntlm-transport --php mongodb` ?

Thanks!

**Comment by dunglas** [comment]
Hi! Using `xcaddy` should work (but to be tested). I'll try to add some docs about that.

**Comment by Kamleshpaul** [comment]
@dunglas  i tried 

```sh
CGO_ENABLED=1 \
XCADDY_GO_BUILD_FLAGS="-ldflags '-w -s'" \
xcaddy build \
    --output frankenphp \
    --with github.com/dunglas/frankenphp/caddy \
    --with github.com/dunglas/caddy-cbrotli \
    --with github.com/dunglas/mercure/caddy \
    --with github.com/dunglas/vulcain/caddy \
    --with github.com/caddy-dns/cloudflare
```
and getting 
<img width="956" alt="Screenshot 2024-10-01 at 4 53 22 PM" src="https://github.com/user-attachments/assets/860538a9-2d94-4908-aced-3f92b60cd859">

**Comment by dunglas** [comment]
You must use the "builder" Docker image we provide or compile PHP locally as instructed in the docs. A source version of PHP is missing, it's why you get this error.

**Comment by Kamleshpaul** [comment]
@dunglas Can I have a Dockerfile where I can include all PHP modules and Caddy modules? I just need to edit it and get the binary.

i m not able to understand doc

i just want a frankenphp binary with `github.com/caddy-dns/cloudflare` this module added

thanks

**Comment by Kamleshpaul** [comment]
i found https://frankenphp.dev/docs/static/#custom-extensions this but it only accept php extension how about  `Caddy modules` ?

**Comment by webagil-kevin** [comment]
See section "How to install More Caddy Module" :
https://github.com/dunglas/frankenphp/blob/main/docs/docker.md
