### ISSUE TITLE
Deteriorating get_browser() calls

### ISSUE THREAD

**Issue by mathieudz** [dunglas/frankenphp#270]
I have migrated a php pm project to frankenphp. I had a big performance issue with get_browser() that was called for every request. It uses a version of browscap that is 22 MB.
In php pm this wasn't an issue, but in frankenphp after a while these calls got very slow, grinding the website to a halt. I saw the functions calling get_browser() often hit my 30 s max duration limit in the logs. My workaround was to cache these function calls with APCU and now performance is normal.

**Comment by dunglas** [comment]
Thanks for the report. Would you mind adding this tip in the "known issues" section? https://github.com/dunglas/frankenphp/blob/main/docs/known-issues.md
