### ISSUE TITLE
how use work mode without docker

### ISSUE THREAD

**Issue by xywf221** [dunglas/frankenphp#274]
i download binary file macos x86
use `export FRANKENPHP_CONFIG="worker index.php"`
exec `./frankenphp php-server`

curl 'http://localhost/index.php'

Fatal error: Uncaught RuntimeException: frankenphp_handle_request() called while not in worker mode

**Comment by dunglas** [comment]
The `php-server` shortcut command doesn't support workers (yet).

To use a worker, create a Caddyfile with the proper config and run `./frankenphp run`
