### ISSUE TITLE
[Question] How to install this module for caddy

### ISSUE THREAD

**Issue by Rishang** [dunglas/frankenphp#279]
How to install this module for caddy
I am trying 

```
caddy add-package https://github.com/dunglas/frankenphp/caddy

also

caddy add-package https://github.com/dunglas/frankenphp
```
```
Output:
Error: download failed: download failed: HTTP 400: https://github.com/dunglas/frankenphp/caddy is not a registered Caddy module package path (id=6229a763-4f7d-4658-90f6-758078b7b95b)
```

**Comment by dunglas** [comment]
Currently, the easiest way is to follow these steps: https://github.com/dunglas/frankenphp/blob/main/docs/compile.md

Using `xcaddy` may also work if you correctly installed libphp locally.

We're are working with the Caddy team to allow using `add-package`, but it's not ready yet.

**Comment by Sjoerd** [comment]
> Currently, the easiest way is to follow these steps: https://github.com/dunglas/frankenphp/blob/main/docs/compile.md
> 
> Using `xcaddy` may also work if you correctly installed libphp locally.
> 
> We're are working with the Caddy team to allow using `add-package`, but it's not ready yet.

Has any progress been made with this?
