### ISSUE TITLE
Arm MacOS Binary does not work

### ISSUE THREAD

**Issue by ChrisRiddell** [dunglas/frankenphp#307]
When following the Laravel guide [Local Installation](https://github.com/dunglas/frankenphp/blob/main/docs/laravel.md#local-installation)

I get the following errors when trying to run the binary on a MacBook Pro with a M1 Pro chip.

```
➜ ./frankenphp-mac-arm64 run
zsh: permission denied: ./frankenphp-mac-arm64
➜  sudo ./frankenphp-mac-arm64 run
sudo: ./frankenphp-mac-arm64: command not found
➜  chmod +x frankenphp-mac-arm64
➜  ./frankenphp-mac-arm64 run     
zsh: bad CPU type in executable: ./frankenphp-mac-arm64
```

**Comment by dunglas** [comment]
Could you try with RC2 to see if something changed recently? It used to work (I use a Mac M1 myself).

**Comment by ChrisRiddell** [comment]
> Could you try with RC2 to see if something changed recently? It used to work (I use a Mac M1 myself).

Just tried RC2 same issue.

**Comment by dunglas** [comment]
I investigated a bit and indeed we have a problem with the CircleCI pipeline. The produced binary is not an ARM.

```
file ./frankenphp-mac-arm64
./frankenphp-mac-arm64: Mach-O 64-bit executable x86_64
```

On my computer, this works anyway, but maybe because I have Rosetta 2 installed.
We need to fix the CircleCI pipeline.
