### ISSUE TITLE
is this a problem? ERROR   unexpected termination, restarting      {"worker": "/app/public/index.php"}

### ISSUE THREAD

**Issue by jorismak** [dunglas/frankenphp#310]
This is an honest question, because I can't really tell if something is wrong or not.

When starting my reproducer for another issue (https://github.com/jorismak/franken-segfault), I notice something:
If I start the container and then load up the page (you'll get the prod-mode  Symfony default 404 page).

If I open the network-tab in the devtools, and press-and-hold ctrl-r (refresh the page), or press-and-hold f5 (the same, refresh the page),
my browser will keep on refresh as fast as possible. Basically a poor-mans benchmark.

![image](https://github.com/dunglas/frankenphp/assets/47725838/e4d6da04-6a3b-49bd-bb5b-6a5c37c85855)

But every once in a while you'll get something like:
```
2023/11/17 21:54:04.320 ERROR   unexpected termination, restarting      {"worker": "/app/public/index.php"}
```
in the logs.

If I start the docker container grepping the output:
```
./start-container.sh | grep -i unexpected
```

you'll only get the termination messages and it makes it clear how often it happens.
Jit, no jit, 1 worker or 20, it seems to always happen.

-----
maybe related, maybe not:

I also tried putting a simple 'max requests' check in the Symfony Frankenphp runtime class.
Something like `if ($nbRequests >= 10) { break }`.

That works, but when the worker stops (with a neat `return 0`) you also get a 'unexpected termination' error in the logs. Is there a way to 'cleanly' exit a worker without causing errors in the logs? Because maybe the termination messages I get once in a while is expected behaviour because frankenphp decides to cycle a worker for whatever reason?

**Comment by dunglas** [comment]
Thanks for the report. FrankenPHP now detects if the worker exited cleanly or not. If it exited cleanly, an info message instead of an error will be logged.

Regarding the worker termination, I wonder if this fixes the issue or not.

**Comment by dunglas** [comment]
Regarding the fast refresh problem, I suspect that the browser aborts the connection and that PHP terminates the worker, as it's the default behavior: https://www.php.net/manual/en/features.connection-handling.php

We should probably disable this behavior in worker mode and just make the closure returns.

**Comment by dunglas** [comment]
I confirmed that's the issue. See #316 and php-runtime/runtime#155.

**Comment by jorismak** [comment]
You work faster than I can reply (with a sick infant at home ) :). I'll
read up tomorrow if I manage! Bit your descriptions actually make sense.
