### ISSUE TITLE
Docker image quite heavy : remove build deps ?

### ISSUE THREAD

**Issue by husimo-tilleuls** [dunglas/frankenphp#32]
Hello,

It seems that Docker image is quite heavy (around 700MB).

I looked at the `Dockerfile` ([https://github.com/dunglas/frankenphp/blob/main/Dockerfile](here)) and it seems that `$PHPIZE_DEPS` are never removed where as in think they are not needed after PHP and go compilation ?

I built the image removing these deps for testing but I have a problem with composer (I'll fill an issue about that too!)

++

**Comment by husimo-tilleuls** [comment]
Actually on an empty project I've been able to test it and it's working properly.

I guess these build packages are not needed even for worker mode, are they ?

**Comment by dunglas** [comment]
Indeed! See https://github.com/dunglas/frankenphp/pull/29#issuecomment-1280549452

**Comment by dunglas** [comment]
Fixed by #33
