### ISSUE TITLE
question: running worker as different user

### ISSUE THREAD

**Issue by jorismak** [dunglas/frankenphp#320]
Hi,

What's the recommended method of getting the frankenphp workers to run as different users?

I figure if running from a Docker container, the userid can be configured in the Dockerfile or the container creation.

But if running caddy 'locally' with the Frankenphp module enabled, is there a way to specify the effective userid/groupid? Caddy is normally run as root, and I believe now php is running as root, instead of falling down to something like 'www-data' or similar.

Is there a general Caddy directive for this that would work, or is there a Frankenphp-specific method?

**Comment by withinboredom** [comment]
I could be wrong, but the only reason Caddy runs as root is to use port 80 and 443, which you can give permission to do that: 

```sh
sudo setcap CAP_NET_BIND_SERVICE=+eip /path/to/binary
```

Other than that, you can use something like `authbind` to handle that in a more fine-grained way: https://manpages.ubuntu.com/manpages/mantic/en/man1/authbind.1.html

Ultimately, you probably shouldn't be running any network services as root, but instead grant those services specific privileges and run them as a restricted user.

**Comment by jorismak** [comment]
Almost every service in an Ubuntu / Debian system starts at root, then
drops privileges when running. So it isn't an unsecure or weird thing to do.

But I do seem to read up that forking itself is not really a thing in most
Go programs, so it seems even Caddy itself doesn't have a feature for this.

setcap is a nice way to overcome this and run the entire daemon as the
correct user from the start, thanks!
I also might just use sysctl to change the privileged ports.
