### ISSUE TITLE
Issue when releasing do Render.com

### ISSUE THREAD

**Issue by hpatoio** [dunglas/frankenphp#335]
Note: I know that this is problaby not directly related to Franken but maybe someone can help.

I'm testing Franken and I'm trying to release it to Render.com

I've checked out the demo Symfony app https://github.com/dunglas/frankenphp-demo and added this `Dockerfile`

```
FROM php:8.3-fpm-alpine as composer_deps
COPY --from=composer:2.6 /usr/bin/composer /usr/bin/composer
WORKDIR /app
COPY src/Kernel.php /app/src/Kernel.php
COPY composer.json /app/
COPY composer.lock /app/
COPY symfony.lock /app/
RUN composer install --no-dev --optimize-autoloader --no-interaction --no-scripts

FROM dunglas/frankenphp
WORKDIR /app
COPY . /app
COPY --from=composer_deps /app/vendor /app/vendor
EXPOSE 443
EXPOSE 80
```

I can build and run it locally. 

When I release it to Render.com I get this error at the end of the build/deploy process

```
/usr/local/bin/docker-php-entrypoint: 9: exec: frankenphp: Operation not permitted
```

Any idea of what can I do ?

**Comment by withinboredom** [comment]
It looks like perhaps frankenphp isn't executable or allowed to execute? It's also worth pointing out that perhaps render.com doesn't allow binding to port 443/80?

According to [their documentation](https://render.com/docs/web-services):

> A PORT environment variable is available by default and set to 10000. It is recommended that you reference the PORT environment variable in your code to set the port of your HTTP process.

You can do that by updating the Caddyfile to use the `PORT` environment variable.

Maybe something like this in the docker file (untested):

sed -i '/\{\$SERVER_NAME\}/:\{\$PORT\}' /etc/Caddyfile

(replaces `{$SERVER_NAME}` with `:{$PORT}` so if the port to serve on is 10000 it becomes `:10000` in the caddyfile when running.
