### ISSUE TITLE
Laravel Local Installation doc

### ISSUE THREAD

**Issue by Kamleshpaul** [dunglas/frankenphp#347]
#### Issue Description:

In the documentation at [https://frankenphp.dev/docs/laravel/](https://frankenphp.dev/docs/laravel/), there is an error in steps 2 and 3. The original instructions are as follows:

**Old:**
```sh 
2. Add the following configuration to a file named Caddyfile in the root directory of your Laravel project:
3. Start FrankenPHP from the root directory of your Laravel project: `./frankenphp run`
```

**Fixed:**
```sh
2. Add the following configuration to a file named Caddyfile in the public directory of your Laravel project:
3. Start FrankenPHP from the public directory of your Laravel project: `./frankenphp run`
```

**Comment by francislavoie** [comment]
You should not put your Caddyfile in `public/` because it risks your Caddyfile config being leaked, which can be a problem if there's any secrets in the file (which shouldn't be the case, but still, it's a risk).

You should instead add `root * public/` to your Caddyfile and run it from the root.

**Comment by dunglas** [comment]
Thank you both for reporting and the fix!
