### ISSUE TITLE
Use different port when running locally with the Binary Version

### ISSUE THREAD

**Issue by nlvedwin** [dunglas/frankenphp#349]
I'm in a mac and trying to use the binary version but I have my port 80 used by my other PHP server. Is there a way to run the franken server in a different port like `8080` or something.

![image](https://github.com/dunglas/frankenphp/assets/78135357/8e0894f7-6a88-4db0-99f1-6a00e056c219)

Also is there a way to use just HTTP with the binary?

**Comment by handydba** [comment]
You can change the port in your configuration file which will automatically disable https
e.g. something like the below works for me
```
{
        # Enable FrankenPHP
        frankenphp
        # Configure when the directive must be executed
        order php_server before file_server
}

:8080 {
        root * /your/document/root

        encode gzip

        php_server
        file_server

        encode zstd gzip

       # rest of your config
```

**Comment by dunglas** [comment]
In addition to what @handydba proposed, you can use the `--listen` parameter to change the port:

```console
frankenphp php-server --listen=:8080
```

By default, only HTTP will be used. To enable HTTPS you have to specify explicitly a domain with `--domain`.
