### ISSUE TITLE
Cannot disable auto HTTPS via Caddyfile when using the official docker image

### ISSUE THREAD

**Issue by jimen0** [dunglas/frankenphp#353]
I'm facing an issue when trying to disable HTTPS on FrankenPHP's official Docker image. I'm using the current latest image so that should be https://hub.docker.com/layers/dunglas/frankenphp/latest/images/sha256-6d437b48fdaf1ef6e606eaf0ca034965232f732bf675b21c6d2314d73fdbe70d?context=explore.

My Caddyfile looks as follows. The app is just a `phpinfo` call at the moment.

```
{
  debug
}

{
  frankenphp
  order php_server before file_server
  auto_https off
}

http://:80 {
  root * /app/public/
  php_server
  encode gzip
}
```

```console
$ tree
.
└── app
    └── public
        ├── Caddyfile
        └── index.php
```

I'm running this via the official Docker image on an ephemeral VM:

```console
$ docker container run --rm -v $PWD/app:/app -p 80:80 dunglas/frankenphp
```

This results in the following log lines being emmitted:

```json
{"level":"info","ts":1702127151.2289443,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
{"level":"info","ts":1702127151.2289834,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
```

Checking the caddy configuration shows the same:

```console
$ curl "http://localhost:2019/config/" -s | jq
{
  "apps": {
    "frankenphp": {},
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":443"    <--- should be :80 instead, right?
          ],
          "logs": {
            "logger_names": {
              "localhost": "log0"
            }
          },
          "routes": [
 ...
```

As expected requesting a page on the host (outside of the Docker container) leads to a 308 redirection to HTTPS.

```console
$ curl http://localhost/index.php -i
HTTP/1.1 308 Permanent Redirect
Connection: close
Location: https://localhost/index.php
Server: Caddy
Date: Sat, 09 Dec 2023 13:09:37 GMT
Content-Length: 0
```

The way I'm currently fixing this is by patching the Caddy configuration via its API but I guess this should be patched in FrankenPHP so it respects my Caddyfile.

```console
$ curl -X PATCH --json '[":80"]'  "http://localhost:2019/config/apps/http/servers/srv0/listen"
```

This results in the expected behavior:

```console
$ curl "http://localhost:2019/config/" -s | jq
{
  "apps": {
    "frankenphp": {},
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":80"
          ],
```

```console
curl http://localhost/index.php -I
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Server: Caddy
X-Powered-By: PHP/8.3.0
Date: Sat, 09 Dec 2023 13:14:28 GMT
```

Apologies if I'm missing something obvious or FrankenPHP isn't intended  to support plain HTTP. Thank you!

Best regards,

**Comment by dunglas** [comment]
Hi,

Support for plain HTTP should work. Can you tell me how you copy your custom Caddyfile in the container?

**Comment by jimen0** [comment]
Hi @dunglas,

Indeed that was the issue. And it was documented on the official docs. My apologies!

<img width="985" alt="image" src="https://github.com/dunglas/frankenphp/assets/6826244/15ef7af3-f186-45df-b7cf-a33c287eb943">


Adding this Caddyfile to `/etc/caddy/Caddyfile` made it work.
```
{
  debug

  frankenphp
  order php_server before file_server
  auto_https off
}

http://:80 {
  root * /app/public/
  php_server
  encode gzip
}
```

I believe this can now be closed as a false positive.

Best regards

**Comment by dunglas** [comment]
Thanks for the feedback.
