### ISSUE TITLE
Any tour or doc for building self-contained binary with Laravel?

### ISSUE THREAD

**Issue by celaraze** [dunglas/frankenphp#356]
Hi Dunglas,

Thanks for making this great work.
I try to build Laravel project with [https://frankenphp.dev/docs/embed/](https://frankenphp.dev/docs/embed/), yes successfully.
But with run with `frankenphp` it looks like no autoload contained.

error below:
```
Warning: require(/tmp/frankenphp_6be55dc617d9634694a208aa60b95635/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /tmp/frankenphp_6be55dc617d9634694a208aa60b95635/public/index.php on line 34
```

**Comment by dunglas** [comment]
It's likely because you didn't run `composer install --no-dev -a` before embedding the app.

I'll write a guide for Laravel ASAP.

**Comment by celaraze** [comment]
Thanks, Dunglas.

Follow your guild I have built and ran it successfully.
Take your time.

Thanks again.
