### ISSUE TITLE
Query Regarding Worker Mode Integration with Laravel Octane

### ISSUE THREAD

**Issue by yihong1120** [dunglas/frankenphp#357]
Dear FrankenPHP Maintainers,

I hope this message finds you well. I am writing to inquire about the current status of the integration between FrankenPHP's worker mode and Laravel Octane. As an avid user of Laravel, I am keenly interested in leveraging FrankenPHP's capabilities to enhance the performance of my applications.

From the README.md documentation on the GitHub repository, I understand that support for Laravel Octane is forthcoming. Could you kindly provide an update on the progress of this feature? Additionally, I would appreciate any insights into the potential timeline for its release and whether there are any opportunities for the community to contribute to its development.

Furthermore, I am curious about the technical details of how FrankenPHP's worker mode will interact with Laravel Octane's server lifecycle and whether there will be any specific considerations or best practices to follow when deploying Laravel applications using FrankenPHP.

Thank you for your dedication to creating a modern application server for PHP, and I look forward to your response.

Best regards,
yihong1120

**Comment by dunglas** [comment]
Hi!

Thank you for your interest in FrankenPHP. Octane integration is being reviewed by the Laravel team. The code is ready.

You can test the integration, track the progress and see how it's done in this PR: https://github.com/laravel/octane/pull/764
