### ISSUE TITLE
Intercept responses for nginx-like X-Accel-Redirect handling

### ISSUE THREAD

**Issue by aleho** [dunglas/frankenphp#365]
Caddy allows the responses in reverse_proxy to be intercepted via [handle_response](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#handle_response) like so:

```
php_fastcgi unix//run/php/fpm.sock {
    # FPM needs full application root
    root /application/public

    @accel header X-Accel-Redirect *
    handle_response @accel {
        root * /files
        rewrite * {rp.header.X-Accel-Redirect}
        file_server
    }
}
```

This allows us to send a "private" file from backend that is available locally without having to stream it through PHP.

I haven't found it in the docs (but maybe didn't look carefully enough), can this be done in FrankenPHP?

**Comment by withinboredom** [comment]
That is a really good suggestion. I've never used this feature but I'm aware of it. I guess the question is, should this be enabled by default or require extra configuration like the fastcgi plugin?

I'd be more than happy to pick this one up @dunglas.

**Comment by aleho** [comment]
I myself am not a fan of implicitly copying Nginx specifiy syntax (and I don't think any of the other X-Accel stuff matters for or even applies to Caddy/FrankenPHP). X-Accel-Redirect being the exception, maybe something configurable might do the trick?

A repeatable option with a simple combination of `header_name` and `file_lookup_root` should be enough, or do you see anything else that would be required?

Like:

```
php_server {
    handle_file_response X-Accel-Redirect /app/var/storage/files
    handle_file_response X-File-Response /files
}
```

Of course,  `I-None-Match` or `If-Not-Modified` might be a good thing to support too. My knowledge of Caddy internals is very limited, maybe that's already implicitly handled by Caddy if you tell it to serve a file?

**Comment by aleho** [comment]
> The downside to something like this is that it won't be compatible with most libraries that take advantage of X-Accel-Redirect.

Yes, exactly my opinion too. I experimented with FrankenPHP yesterday and found out that we can easily use it as a drop-in replacement (we're already using Caddy too), so I'd always vote for compatibility with existing setups.

I understand that using headers to tell the downstream what to do with a response is somewhat strange design but very flexible as well (see caches).

Keeping X-Accel-Redirect in applications allows the Caddy setup to either use it or even pass it to the next downstream that might be a reverse-proxy doing load-balancing and streaming files from an S3 storage.

**Comment by dunglas** [comment]
Symfony HttpFoundation (so also Laravel, Drupal etc) have native support for `X-Accel-Redirect`: https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php

So I'll go the header way too, this will allow all these existing apps to leverage this feature.

**Comment by aleho** [comment]
Is this how it's supposed to be working now (config taken from the official Caddy docs)?

```
{
	debug

	frankenphp {
	}

	local_certs
	ocsp_stapling off
}

https://test.localhost {
	encode gzip zstd
	root * /application/public

	php_server {
		@accel header X-Accel-Redirect *
		handle_response @accel {
			root	* /files
			rewrite * {rp.header.X-Accel-Redirect}
			method  * GET
			file_server
		}
	}
}
```

Because with this config (everything exactly the same except for `php_server`) I get an error on requests.
Funny enough not even `php_server` with only `root` works.

```
php_server {
	root * /application/public
}
```


The error I get:
```
{
  "level": "error",
  "logger": "http.log.error",
  "msg": "lstat /application/*: no such file or directory",
  "request": {
    "remote_ip": "172.27.0.1",
    "remote_port": "33652",
    "client_ip": "172.27.0.1",
    "proto": "HTTP/2.0",
    "method": "GET",
    "host": "test.localhost",
    "uri": "/",
    "headers": {
      "Te": [
        "trailers"
      ],
      "Accept": [
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
      ],
      "Accept-Language": [
        "de,en-US;q=0.7,en;q=0.3"
      ],
      "Cookie": [
        "REDACTED"
      ],
      "Upgrade-Insecure-Requests": [
        "1"
      ],
      "Sec-Fetch-Mode": [
        "navigate"
      ],
      "Sec-Fetch-User": [
        "?1"
      ],
      "User-Agent": [
        "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0"
      ],
      "Accept-Encoding": [
        "gzip, deflate, br, zstd"
      ],
      "Sec-Fetch-Dest": [
        "document"
      ],
      "Sec-Fetch-Site": [
        "none"
      ],
      "Priority": [
        "u=1"
      ]
    },
    "tls": {
      "resumed": false,
      "version": 772,
      "cipher_suite": 4865,
      "proto": "h2",
      "server_name": "test.localhost"
    }
  },
  "duration": 0.000242527
}
```
