### ISSUE TITLE
Disable HTTPS for Kubernetes Environment

### ISSUE THREAD

**Issue by chrispage1** [dunglas/frankenphp#370]
Hi,

I'm trying to disable HTTPS on Caddy so that Kubernetes can route to port 80 and Nginx can negotiate SSL.

https://caddyserver.com/docs/caddyfile/options#auto-https

I'm adding this to the environment variables - `CADDY_GLOBAL_OPTIONS="auto_https off"`

But I'm getting:

```
Error: adapting config using caddyfile: /etc/caddy/Caddyfile:2: unrecognized global option: auto_https off
```

It seems this is a valid global option. Any ideas?

Thanks,
Chris.

**Comment by withinboredom** [comment]
Does #353 help?

**Comment by dunglas** [comment]
To disable HTTPS, set `SERVER_NAME` to `http://`.

**Comment by chrispage1** [comment]
> Does #353 help?

This helped, thank you! I managed to get it up and running on Kubernetes. On a test vs Octane it ran quite significantly slower (to be expected), but 7 req/s vs 140 kind of slow.

Running nginx/php-fpm is actually more performant at the minute, not too sure why..

Perhaps some tuning on the Caddyfile required. Any other suggestions on how I can improve this? I'm running Laravel and have run the optimize command. Thanks!

**Comment by dunglas** [comment]
Did you check https://github.com/laravel/octane/pull/764?

**Comment by chrispage1** [comment]
> Did you check [laravel/octane#764](https://github.com/laravel/octane/pull/764)?

Very nice! I'll take a look at that.

The main reason for looking into FrankenPHP was to try and cut the memory overhead that Octane gives. For example, my application at idle is using ~400Mb RAM.

Most of our applications run NGINX/PHP-FPM but it'd be great to have a single container that does both (FrankenPHP!)

Thanks,
Chris.

**Comment by keskinonur** [comment]
I solve similar problem with these configurations:

- Enable Cloudflare DNS proxy for SSL
- Leave your server name as a domain name (**example.com**) without adding **http://** or **:80**
- Inject global configuration for Frank / Caddy

    `CADDY_GLOBAL_OPTIONS="local_certs"`

- Restart your server
- Enjoy your SSL managed by Cloudflare
