### ISSUE TITLE
Error when running symfony app from static build

### ISSUE THREAD

**Issue by aszenz** [dunglas/frankenphp#378]
I managed to build the app using the instructions at https://frankenphp.dev/docs/static/

when running it with `sudo ./my-app php-server`, i got this error:

Fatal error: Maximum call stack size of 84400 bytes reached during compilation. Try splitting expression in /tmp/frankenphp_6244750a1f25b8649db5888cd52cecb1/vendor/symfony/framework-bundle/DependencyInjection/Configuration.php on line 355

What could be going wrong here, any idea?

**Comment by dunglas** [comment]
Have you warmed the cache before embedding the app?

**Comment by aszenz** [comment]
Thanks I followed this document now: 
https://frankenphp.dev/docs/embed/
and was able to get it running
