### ISSUE TITLE
Issue with PostgreSQL Driver Missing in Laravel App

### ISSUE THREAD

**Issue by askdkc** [dunglas/frankenphp#388]
I encountered an issue while running my Laravel app using frankenphp. 

The application works seamlessly with SQLite and MySQL, but when attempting to use PostgreSQL, I'm encountering the following error:

`Illuminate \ Database \ QueryException`
`could not find driver`

It appears that the PostgreSQL driver is missing in the setup.

Are there plans to add support for the PostgreSQL driver in the near future?

**Comment by dunglas** [comment]
How did you install FrankenPHP? Using Docker images or using the static binary?

**Comment by askdkc** [comment]
@dunglas 

I used the static binary downloaded from 

https://github.com/dunglas/frankenphp/releases/download/v1.0.0/frankenphp-mac-arm64

**Comment by dunglas** [comment]
Thanks, I'll take a look.

In the meantime, as a workaround, you can use using the Docker image and install the extension with the provided script. I'm sure this works because I use Postgres with FrankenPHP 😀

**Comment by kiwina** [comment]
Same issue with mysql and the docker image trying to run laravel

`
FROM dunglas/frankenphp

# add additional extensions here:
RUN install-php-extensions zip pdo-mysql`

**Comment by kiwina** [comment]
> install-php-extensions

well what was missing was the default-mysql-client in the image got the hint from https://github.com/tyamahori/LaravelOrbStack

**Comment by dunglas** [comment]
Actually, this is a known issue tracked here: https://github.com/crazywhalecc/static-php-cli/issues/278
It only affects macOS. Closing as tracked by the upstream project.

**Comment by askdkc** [comment]
@dunglas 

Thank you for your quick fix!
I'll check it again when the fixed version gets released!
