### ISSUE TITLE
Release changelogs seem to be broken 

### ISSUE THREAD

**Issue by nickchomey** [dunglas/frankenphp#409]
Each release seems to just have an ever-growing log of PRs that have have commited since the beginning, rather than what has changed since the prior release.

It would be useful if it could just show what is new so that we can easily track changes from version to version.

I thought it was just a beta thing, but it persists with v1.x so I'm reporting it now.

**Comment by dunglas** [comment]
I thought the same, but indeed we have a problem 😅

I'm on it, but if somebody knows what's going on, please let me know!

**Comment by dunglas** [comment]
I think I'll manage to find the solution without it 😅
