### ISSUE TITLE
Why's the docker image so large?

### ISSUE THREAD

**Issue by foremtehan** [dunglas/frankenphp#412]
Newbie here, just noticed the size of this docker image on the hub. Care to explain why's it so big? I'm thinking it'll eat up more than 2GB in production. I imagine even if it included php itself, it shouldn't be this large

**Comment by Javdu10** [comment]
Hello @foremtehan, did you try to use the search filter of the available images/tags on docker hub?

**Comment by foremtehan** [comment]
sorry i did not scroll to the end of page:

![image](https://github.com/dunglas/frankenphp/assets/53290883/067642f1-42a8-48e9-9e14-d09b321724f0)
