### ISSUE TITLE
Alpine image

### ISSUE THREAD

**Issue by back-2-95** [dunglas/frankenphp#42]
I just re-did `Dockerfile` with alpine images:

<img width="1023" alt="CleanShot 2022-10-19 at 23 25 27@2x" src="https://user-images.githubusercontent.com/1140272/196796694-d93c9e35-24a2-4f56-b421-a413ef64a2c8.png">

From 2.51 Gb (Bullseye) to 256 Mb (Alpine)

I need to cleanup my work and create PR.

**Comment by back-2-95** [comment]
PR added for test & review.

**Comment by back-2-95** [comment]
Weirdly Bullseye image went to 757Mb when building with Docker Bake.

![CleanShot 2022-10-20 at 00 04 50@2x](https://user-images.githubusercontent.com/1140272/196804205-4d230b98-d1d3-48bc-a84a-ff29609b4b94.png)

**Comment by dunglas** [comment]
> Weirdly Bullseye image went to 757Mb when building with Docker Bake.

It's because #33 has been merged but I haven't pushed the new images yet.
