### ISSUE TITLE
perf: consider switching from cgo to purego

### ISSUE THREAD

**Issue by dunglas** [dunglas/frankenphp#464]
@Mohammed90 shared this library with me: https://github.com/ebitengine/purego

This looks very interesting. I wonder it this could brings significant performance benefits to FrankenPHP.

**Comment by withinboredom** [comment]
Prior to 1.0.2, you could build FrankenPHP with tinygo and perf was a bit better.

**Comment by dunglas** [comment]
Using purego may not improve performance. According to their docs, it only helps for cross-compilation, and we already support cross-compilation.
