### ISSUE TITLE
Strange behavior with Enum (nested directories + duplicate names)

### ISSUE THREAD

**Issue by lermontex** [dunglas/frankenphp#467]
I'm using Symfony 7 (PHP 8.3) + ApiPlatform 3.2 (GraphQL) + FrankenPHP 1.0.3

I recently updated my `dunglas/symfony-docker` configuration to work with FrankenPHP and encountered a very strange error

I'm using a nested structure for Entity + Enum, here's a simple example:

```
User (entity)
	Status (enum)
	Gender (enum)
	Invoice (entity)
		Status (enum)
	Report (entity)
		Type (enum)
		Status (enum)
```

As you can see, there are several Enums with the same name, but in different directories

```php
// Entity/User.php
namespace App\Entity\User;

use App\Entity\User\Status;

class User
{
// ..
	private Status $status;
	#[ORM\Column(type: "integer", enumType: Status::class)]
}
```

```php
// Entity/User/Status.php
namespace App\Entity\User;

enum Status: int
{
    case ONLINE = 1;
    case OFFLINE = 2;
}
```

```php
// Entity/User/Report.php
namespace App\Entity\User\Report;

use App\Entity\User\Report\Status;

class Report
{
// ..
	private Status $status;
	#[ORM\Column(type: "integer", enumType: Status::class)]
}
```

```php
// Entity/User/Report/Status.php
namespace App\Entity\User\Report;

enum Status: int
{
    case SUBMITTED = 1;
    case ACCEPTED = 2;
}
```

When working in a production environment, I noticed that after some time of operation the server begins to return the wrong status for entities where there is an associated property (Enum) whose name is duplicated in another folder. For example, the API can return SUBMITTED status for a User entity while it is in ONLINE status (this is just an example)

If Enum has the same name, but a different type (int/string), the server returns an Internal Server Error (this happens every other time) but unfortunately, detailed errors are not visible in the production environment.

The problem is solved by restarting FrankenPHP, but after some time (especially after actively working with entities (inserting/editing) the errors return

The first thing I did was turn off the Worker mode - it didn't work
Next I disabled Opcache - it didn't work
I tried renaming the Enum so that the names are unique - it worked

I can't say that this error is 100% related to FrankenPHP, but I haven't noticed such oddities before.
I don’t quite understand how it works, but perhaps FrankenPHP is trying to cache Enum, but doing it incorrectly?

**Comment by withinboredom** [comment]
If I understand the issue correctly, it smells like PHP's object table is getting corrupted somehow. Have you tried using the FQN of the objects in your code instead of using `use` statements? 

That might help us determine whether it is on the compile or runtime stage.

**Comment by dunglas** [comment]
This smells more like an upstream bug than a FrankenPHP bug (especially because it's not related to worker mode). Maybe should you report upstream?

**Comment by withinboredom** [comment]
That's what I was thinking, too, @dunglas; I don't see us doing anything that would cause this unless it has something to do with how we are setting up the SAPI or is related to some shenanigans in ZTS builds.

**Comment by withinboredom** [comment]
@lermontex it would be good to see if you can create a simple reproduction in a public repository. If you can create one and it only happens in frankenphp, then it would be our bug. Otherwise if it happens in cli, fpm, or apache, it would be a [php-src](https://github.com/php/php-src/issues) bug.

**Comment by lermontex** [comment]
@withinboredom, @dunglas, Thanks for answers! At the moment we were forced to use unique names for Enum. I will definitely report the results of the test if I manage to reproduce this error in the development environment
