### ISSUE TITLE
ENV variables for static binary

### ISSUE THREAD

**Issue by Ferikl** [dunglas/frankenphp#468]
Hi guys, thanks for great project!

I dont know where I can ask this question so sorry if its not the right place.

I want to use static binary of my PHP|Laravel app inside alpine image in my CD process (k8, etc). 

I`ve read https://frankenphp.dev/docs/config but still have an issue with env vars: My PHP application doesnt see env vars from alpine image.

Dockerfile:

```
FROM --platform=linux/amd64 dunglas/frankenphp:static-builder AS builder


WORKDIR /go/src/app/dist/app
COPY . .

//custom php.ini with variables_order = EGPCS 
COPY config/app.ini /etc/php83/conf.d/custom_php.ini

RUN composer install --ignore-platform-reqs --no-dev -a


WORKDIR /go/src/app/
RUN EMBED=dist/app/ \
    PHP_EXTENSIONS=apcu,intl,opcache,zip,rdkafka,redis,bcmath,pdo_mysql,pcntl \
    ./build-static.sh

FROM alpine:3.19.0

WORKDIR /app

COPY --from=builder /go/src/app/dist/frankenphp-linux-x86_64 lara-app

EXPOSE 80

CMD ["./lara-app", "php-server"]
```

in the alpine container:
```
/app # env
HOSTNAME=c6b6a517dc1d
SHLVL=1
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/app
USER_NAME=ClarkKent
```

in the PHP code:
```
var_dump(getenv('USER_NAME'));
die();
```
I get NULL

Can you point me where I am wrong?

**Comment by withinboredom** [comment]
What is the contents of `$_ENV`? This might be a bug, but it would be good to check that in your entrypoint (before loading any other files), that it is empty. Sometimes frameworks will clear out the environment based on a whitelist (**cough**, Symfony).

**Comment by Ferikl** [comment]
@withinboredom thanks! You point me in the right way.

My flow was wrong:
- build image `docker build -f Dockerfile-static -t frankenapp .`
- run container `docker run -d -p 8888:80 frankenapp`
- add env by `export USER_NAME=ClarkKent` inside running container <------ wrong
- check http://localhost:8888 with var_dump

Correct flow:
- build image `docker build -f Dockerfile-static -t frankenapp .`
- run container with correct env var `docker run -e USER_NAME=ClarkKent -d -p 8888:80 frankenapp` <---- correct
- check http://localhost:8888 with var_dump
