### ISSUE TITLE
Feature request: include composer to complement built-in php

### ISSUE THREAD

**Issue by ARehmanMahi** [dunglas/frankenphp#470]
https://github.com/laravel/octane/pull/764#issuecomment-1883914525

As FrankenPHP has its own PHP, We can discard system level PHP install.
And start the app using`./frankenphp php-cli artisan octane:start` which will use Franky's built-in PHP to run the app.

But doing `composer install` requires PHP binary, so you still need a globally accessible PHP binary.
How about including composer to complement built-in php so doing `./frankenphp php-cli composer install` would work seamlessly?

**Comment by withinboredom** [comment]
If you are using the docker image, you can just do `install-php-extensions @composer` when installing your extensions.

**Comment by ARehmanMahi** [comment]
Hi appreciate the fast reply, should have included it before, not using docker. Using standalone binary. Any suggestion for this? Sorry for noob questions.

If difficult then maybe I should use docker instead, but that would be another dependency for me to manage on the server.

**Comment by withinboredom** [comment]
If you are using the standalone binary, why not have `composer.phar` in a directory of your project, then add:

```bash
#!/bin/bash

exec ./frankenphp-linux-x86_64 php-cli ./composer.phar $@
```

Then you just call `./composer install` like ye old days before we did globally installed composers.

**Comment by ARehmanMahi** [comment]
I was just trying the same with a custom alias, but this is very neat. Thank you. Loving how Franky is headed.
Thank you for the reply and all the efforts you have put into the project.

**Comment by dunglas** [comment]
This could be nice to add these tricks to the docs.

**Comment by ARehmanMahi** [comment]
Definitely would be helpful. One time I was curious which PHP packages were included in Franky's PHP & couldn't find in docs. Some fellow pointed a hint towards the build process of Franky and I got it from there.

So maybe include the hint for packages and pointing to:
https://github.com/dunglas/frankenphp/blob/d4c313f3db04165b70ccce34d085559a949b379e/build-static.sh#L21

**Comment by dunglas** [comment]
Passing flags such as `-c` or `-d` isn't supported yet, but could be nice to support.

**Comment by ARehmanMahi** [comment]
Ameen to that :)

**Comment by rodrigopedra** [comment]
@dunglas running a shell script like you suggested here: https://github.com/dunglas/frankenphp/issues/470#issuecomment-1886638757 fails with Laravel post install script

Specifically, when running the package auto-discover.

Here is the relevant output:

```shell
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Application.php line 430:
                                                                          
  Invalid working directory specified, allow_url_fopen=1 does not exist.  
                                                                          

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

Steps to reproduce:

- `cd` into a Laravel project
- run `./composer install`  where `composer` is the shell script suggested by you on the referenced comment
- *also remember to have a `composer.phar` file in the same directory*

**Comment by ARehmanMahi** [comment]
Ok, just ran a test and got this error.
Inside new `test` added frankenphp, compser.phar & composer.sh with the code snipper provided above.

Ran `./composer create-project laravel/laravel example-app`

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

Fatal error: Uncaught ReflectionException: Class "config" does not exist in /var/www/html/test/example-app/vendor/laravel/framework/src/Illuminate/Container/Container.php:912
Stack trace:
```

Tried to google, but all suggestions were for an existing project the above is new laravel install.
Someone said it's related to mbstring when compiling php, but mbstring is added in the build script I reckon.
So not really sure. mybe someone can test it? WIll look into it again later. Google GPT stuff.

**Comment by withinboredom** [comment]
It would be great if you could share the actual code causing the error instead of entire frameworks so that we can reproduce with a minimal example. In that error message, it looks like the project needs to be configured. For laravel help, I recommend going to the laravel repo or forums.

**Comment by ARehmanMahi** [comment]
@withinboredom Hi, there was no code & no project.

I just ran `./composer create-project laravel/laravel example-app` which is a composer command to install laravel project.
I'm trying to use frankenphp php-cli to run composer commands.

I just used your suggested `.sh` script and frankenphp & it's built-in php.

composer
```
#!/bin/bash

exec ./frankenphp php-cli ./composer.phar $@
```

composer.phar
```
Downloaded from the site directly.
```

frankenphp v1.0.3
```
Downloaded from the git directly.
```

Commands
```
$ mkdir test
$ cd test
# copy all three files here
$ ls > composer composer.phar frankenphp
$ ./composer create-project laravel/laravel example-app
```

Laravel installer runs fine untill it reaches pro-install script and error outs
```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

Fatal error: Uncaught ReflectionException: Class "config" does not exist in /var/www/html/test/example-app/vendor/laravel/framework/src/Illuminate/Container/Container.php:912
Stack trace:
```
This also happens on an existing project.
Using system-level php with composer works fine so it seems to be frankenphp php-cli's issue.
I'm not very technical in this stuff, but using the franky and the tips, I found this problem and wanted to test & share as someone above had issue with the same approach.

I don't have any urgent usage for this, but just for the info. And would be good if this would work with this scenario.

**Comment by withinboredom** [comment]
I'd recommend creating a new issue to investigate it properly and it would get more eyes on it. We would need to dig into composer/laravel and figure out what it is doing and whether it is due to them doing something weird/unexpected or FrankenPHP not setting something up properly.

This issue seems more about using composer and less about setting up a laravel project.

**Comment by rodrigopedra** [comment]
@withinboredom I'll keep the discussion on the new issue, but as I couldn't reply to you before, I just wanted to give you feedback.

I tested on a fresh Laravel app, created using `laravel new franken` (which used my system PHP and composer to bootstrap)

Thank I followed the suggestion on creating a local shell script and using a local `composer.phar`

Laravel doesn't have a class named `Application.php`, you are right about that.

But composer does:

https://github.com/composer/composer/blob/4e5be9ee7d924d8efc58d676439b0c7bd18a9ce4/src/Composer/Console/Application.php
