### ISSUE TITLE
CADDY_GLOBAL_OPTIONS env var with multiple options

### ISSUE THREAD

**Issue by michaelaguiar** [dunglas/frankenphp#482]
Is there a way to define CADDY_GLOBAL_OPTIONS with multiple values?

For example:

`http_port 8080`
`auto_https off`

I am preparing a container for Google Cloud Run, and I would love to just set these env vars instead of using `sed` to edit the Caddyfile on the fly.

**Comment by ochorocho** [comment]
Well, you can use multiline in `.env`:
```
CADDY_GLOBAL_OPTIONS="http_port 8787
https_port 8788
debug"
```

**Comment by michaelaguiar** [comment]
Do you know of anyway to do multiline in a `Dockerfile`?

For example:

```
ENV CADDY_GLOBAL_OPTIONS="http_port 8080
auto_ssl off
debug"
```

Seems Docker doesn't allow multi-line env vars.

**Comment by ochorocho** [comment]
Maybe something like? (untested, just a thought) 
```
ENV CADDY_GLOBAL_OPTIONS="http_port 8787 \
    https_port 8788 \
    debug"
```

A possible alternative could be to copy and source .env file or pass in the as ARG to the Dockerfile

**Comment by michaelaguiar** [comment]
Escaping the line break did the trick! I also like the idea of passing as ARG too.

Appreciate the help! This will help cleanup my Dockerfile and remove some of these sed commands.

**Comment by ochorocho** [comment]
yw

**Comment by wilmardo** [comment]
Just to add to this since the solution proposed by @ochorocho wasn't working for me.

If anyone needs this, you could use some clever heredoc and sed for this:

```Dockerfile
RUN <<EOF sed -i -e '/{$CADDY_GLOBAL_OPTIONS}/{r /dev/stdin' -e 'd;}' /etc/caddy/Caddyfile
admin off
auto_https off
servers {
    enable_full_duplex
}
EOF
```
