### ISSUE TITLE
`Undefined constant "GLOB_BRACE"` with standalone server

### ISSUE THREAD

**Issue by hockdudu** [dunglas/frankenphp#484]
When using the standalone binary server (https://github.com/dunglas/frankenphp/releases/tag/v1.0.3), I get the following error when using the `GLOB_BRACE` constsant:

```
Fatal error: Uncaught Error: Undefined constant "GLOB_BRACE" in /tmp/test-frankenphp/index.php:3 Stack trace: #0 {main} thrown in /tmp/test-frankenphp/index.php on line 3
```

My example script:
```php
<?php

$files = glob('{a,b,c}.txt', GLOB_BRACE);
var_dump($files);
```

Command:
```shell
frankenphp php-server --listen 127.0.0.1:8080
```

This error does not occur when using the Docker image `dunglas/frankenphp:latest`.

**Comment by hockdudu** [comment]
The PHP documentation states that `GLOB_BRACE` isn't available in some Linux systems like Alpine Linux.

I tried, and I'm able to reproduce this with the Docker image `dunglas/frankenphp:latest-alpine`.

Does that mean the server binary is based on Alpine Linux in some way?

**Comment by dunglas** [comment]
@hockdudu yes, the static binary is using the musl libc (as Alpine), which is known not to support `GLOB_BRACE`.

**Comment by hockdudu** [comment]
Thanks for the swift answer :smile: 

I may have missed it, but is this documented somewhere?

**Comment by dunglas** [comment]
In the musl docs IIRC, but it could be nice to add it in the "known issues" section of FrankenPHP docs! Would you mind to open a PR?
