### ISSUE TITLE
Cleanup docker tags

### ISSUE THREAD

**Issue by shyim** [dunglas/frankenphp#491]
Frankenphp docs are saying:
> Variants for PHP 8.2 and PHP 8.3 are provided. [Browse tags](https://hub.docker.com/r/dunglas/frankenphp/tags).

Me going to Docker Hub:

![image](https://github.com/dunglas/frankenphp/assets/6224096/2163a863-2be7-4a0e-976c-2e2739bde0b0)

wtf? what is the structure of the tags? After a few minutes, I finally understood the structure when I searched for `latest` or `1.0.3`.

My idea to improve this would be to move all non-production relevant docker images to a different image like `frankenphp-nightly`, in that case, when you open docker hub you directly see how the naming is 😂 

Another improvement could be to use tagged versions in the examples in the docs, so you don't have to browse the tags

**Comment by dunglas** [comment]
Good idea to create a nightly image!

**Comment by shinsenter** [comment]
BTW, the `dunglas/frankenphp:latest` tag was updated a month ago 😂 

<img width="588" alt="Screenshot 2024-01-29 at 18 32 26" src="https://github.com/dunglas/frankenphp/assets/2082119/ae956982-755e-49da-add0-311099ef0a35">

https://hub.docker.com/r/dunglas/frankenphp/tags?page=1&name=latest
