### ISSUE TITLE
Hide X-Powered-By for security

### ISSUE THREAD

**Issue by binaryfire** [dunglas/frankenphp#496]
Hi guys

Is there a way to disable the X-Powered-By header? Normally this is done using the `expose_php` flag in php.ini but I'm not sure how to do it for the FrankenPHP binaries (or if it's possible atm). I'm using Laravel Octane.

Exposing this info is a security issue because it provides hackers with additional server info they can use to tailor attacks:
<img width="211" alt="image" src="https://github.com/dunglas/frankenphp/assets/5361908/8b7bb7f4-2dcd-42cc-bb42-91e59204657d">

**Comment by dunglas** [comment]
This directive is supported, you can set it in `php.ini` or using `ini_set()`, as usual!

**Comment by binaryfire** [comment]
@dunglas Great thanks! But does that include the standalone binary that Octane uses? I assumed from [this issue](https://github.com/dunglas/frankenphp/issues/472) that it wasn’t possible to use a custom php.ini file.

**Comment by dunglas** [comment]
@binaryfire it is possible to use a `php.ini` file by placing it at the default path, or by changing `PHP_INI_SCAN_DIR`.

**Comment by milewski** [comment]
I manually remove it from my Caddy file config like this:

```Caddy
{
    frankenphp
    order php_server before file_server
}

:80 {
    root * /srv/public
    encode zstd gzip
    php_server

    header -X-Powered-By
}
```

**Comment by ruudk** [comment]
It would be great if FrankenPHP disabled this by default.

**Comment by binaryfire** [comment]
@ruudk I agree. That makes the most sense from a security point of view.

**Comment by milewski** [comment]
Don't you guys have a config where you could also remove it? Nor do you have another reverse proxy in front of it that could do the same? I don't feel like it is FrankenPHP's responsibility to remove headers, neither-less do it automatically....

**Comment by binaryfire** [comment]
@milewski That's what I'm doing - stripping the header at the load balancer. But why not implement best-practice defaults in FrankenPHP as well? Because it most definitely is best-practice as far as security analysts and pen testers are concerned. Only a small percentage of regular users would check for unwanted server headers.

**Comment by dunglas** [comment]
I agree with @milewski, this should be changed in PHP directly.
