### ISSUE TITLE
FrankenPHP on Laravel with Multiple Domain

### ISSUE THREAD

**Issue by JohnDotOwl** [dunglas/frankenphp#504]
### Setup Method
```
php artisan octane:install --server=frankenphp
php artisan octane:start  --caddyfile /var/www/project/Caddyfile
```

What if i have multiple projects , do i need to setup multiple Caddyfile in the root of the project folder? Im getting the impression that there should be 1 main caddyfile to handle all domains from multiple projects

**Comment by favianriyanto** [comment]
in caddyfile

domain1.com {
	root * /www/wwwroot/domain1/public/
	encode zstd gzip
	php_server {
		resolve_root_symlink
	}
}

domain2.com {
	root * /www/wwwroot/domain2/public/
	encode zstd gzip
	php_server {
		resolve_root_symlink
	}
}
