### ISSUE TITLE
Updating configuration files on startup

### ISSUE THREAD

**Issue by michaelaguiar** [dunglas/frankenphp#508]
This is a _best practice_ question.

I have a Dockerfile that uses `dunglas/frankenphp:sha-7454826-php8.2.15-alpine` as the base image, installs all of the PHP extensions I need, and installs the email server `MSMTP`.

I have to add a configuration file for MSMTP (/etc/msmtp) that has a few details like host / user / password. These values are being passed to my service in ENV vars, as they are dynamic depending on the service that is using this container.

It seems I can't use ENV vars in my `/etc/msmtp` config file like '{$MSMTP_RELAY_SERVER_HOST}` - PLEASE CORRECT ME IF I AM WRONG - this is the ideal solution.

So now I am including a `docker-configure` file, using it as the `ENTRYPOINT`, then calling the parent containers ENTRYPOINT at the end via `exec /usr/local/bin/docker-php-entrypoint "@"`. I am also including the CMD below my ENTRYPOINT in my Dockerfile like `CMD [ "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]`.

Is this the best way to handle injecting ENV vars into config files? Should I be able to drop ENV vars in the config file directly, like `{$FRANKENPHP_CONFIG}` for example in the base Caddfile?

Here is my Dockerfile for reference. Any recommendations to improve are welcome!

```dockerfile
FROM dunglas/frankenphp:sha-7454826-php8.2.15-alpine

ENV MSMTP_RELAY_SERVER_HOST= \
    MSMTP_RELAY_SERVER_PORT= \
    MSMTP_RELAY_SERVER_AUTH= \
    MSMTP_RELAY_SERVER_USER= \
    MSMTP_RELAY_SERVER_PASSWORD= \
    MSMTP_RELAY_SERVER_FROM=

COPY /etc/msmtprc /etc/msmtprc
COPY docker-configure /usr/local/bin/docker-configure

# Copy php.ini and Install Extensions
RUN chmod +x /usr/local/bin/docker-configure && \
    apk add --update --no-cache msmtp && \
    cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini && \
    install-php-extensions \
    json \
    mysqli \
    curl \
    dom \
    exif \
    fileinfo \
    hash \
    igbinary \
    imagick \
    intl \
    mbstring \
    openssl \
    pcre \
    xml \
    zip

ENTRYPOINT ["docker-configure"]
CMD [ "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
```

**Comment by withinboredom** [comment]
> Is this the best way to handle injecting ENV vars into config files?

Ultimately, it is up to you as to how the environment gets configured. You can use environment variables, mount a configuration file, or whatever makes the most sense for your application.
