### ISSUE TITLE
[OFF-TOPIC] Nginx/Apache Reverse Proxy

### ISSUE THREAD

**Issue by bashman** [dunglas/frankenphp#509]
I have deployed several applications like odoo, node.... But Laravel I have always put it to work directly with nginx. 

Now using frankenphp for Laravel, in a production environment you can use it directly or you need a reverse proxy?.

**Comment by withinboredom** [comment]
I have a TCP/UDP load balancer in front of caddy, using s3 caddy module for certificate sharing. The reason I do this is because nginx (at least the one I have access to) doesn't support http3.

**Comment by dunglas** [comment]
Quick answer: you can use it directly.
