### ISSUE TITLE
Managing Memory Leaks

### ISSUE THREAD

**Issue by vahidalvandi** [dunglas/frankenphp#512]
Hi . Do this project  Managing Memory Leaks or we need to control source code ?

**Comment by withinboredom** [comment]
Can you clarify what you are asking?

**Comment by vahidalvandi** [comment]
In laravel document octane talk about it
https://laravel.com/docs/10.x/octane#managing-memory-leaks

**Comment by dunglas** [comment]
This is handled directly by Octane (and yes, this works with FrankenPHP as engine).

Symfony Runtime has a similar feature that also works with FrankenPHP, and our documentation explain how to deal with memory usage in a similar way for custom apps: https://frankenphp.dev/docs/worker/#custom-apps
