### ISSUE TITLE
Add support for Concurrent Tasks (Laravel Octane)

### ISSUE THREAD

**Issue by erfansahaf** [dunglas/frankenphp#535]
### Describe you feature request

It would be very nice to support the [Octane Concurrent Task](https://laravel.com/docs/10.x/octane#concurrent-tasks) feature in the FrankenPHP driver. Currently, only Swoole supports this feature and that's why some people (including me) prefer to keep using Swoole while the FrankenPHP has shown a better benchmark result.

**Describe the solution you'd like**
I want to set my Octane's driver to FrankenPHP and still be able to write concurrent tasks in a Laravel application:

```php
[$users, $servers] = Octane::concurrently([
    fn () => User::all(),
    fn () => Server::all(),
]);
```

And I think such behavior can be accomplished using Go's Goroutines and WaitGroup features.

**Describe alternatives you've considered**
Currently, I'm using [Swoole](https://laravel.com/docs/10.x/octane#swoole) driver in my Laravel application.

**Comment by dunglas** [comment]
In my opinion, this would be better to delegate this to the parallel extension or to Swoole (the extension) itself.
Actually, this should already work as long as they extension are built with FrankenPHP.

This may be possible to implement a similar feature in  Go using Goroutines, but I think that it isn't worth it as the current solutions work with FrankenPHP (and they already have large ecosystems), and we'll likely have no performance gain compared to them.

WDYT?
