### ISSUE TITLE
php.ini problem in Laravel Octane

### ISSUE THREAD

**Issue by rafailml** [dunglas/frankenphp#541]
I'm trying to run FrankenPHP with Laravel Octane in Docker.  When it starts, in log I'm getting lots of:
```bash
ERROR  PHP Fatal error:  Uncaught Error: Class "Laravel\Octane\Octane" not found in /app/vendor/laravel/octane/bin/bootstrap.php:24
Stack trace:
#0 /app/vendor/laravel/octane/bin/frankenphp-worker.php(19): require()
#1 /app/public/frankenphp-worker.php(3): require('...')
#2 {main}
  thrown in /app/vendor/laravel/octane/bin/bootstrap.php on line 24
```

I checked that file is where it should be.  
```bash
sudo docker exec app_1 ls -l /app/vendor/laravel/octane/src/Octane.php
```

My Dockerfile:
```
FROM dunglas/frankenphp

RUN install-php-extensions pcntl

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

RUN docker-php-ext-install pdo pdo_mysql \
    && rm -rf /var/lib/apt/lists/*

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

COPY . /app

ENTRYPOINT ["php", "artisan", "octane:frankenphp"]
```

I found out that this problem is caused by this line in my Dockerfile:
```
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
```
I find that line in FrankenPHP documentation. If I remove it, everything runs perfect. 
The php.ini.development gives me the same errors. 

I'm trying to find out which php.ini file is used when I remove that line.
In phpinfo(); I see:
```
Loaded Configuration File	(none)
```
In /usr/local/etc/php there is no php.ini file. Only php.ini.production and php.ini.development

How can I found out where is that php.ini file to modify it? Because it is for development.

BTW running FrankenPHP without Laravel Octane works as it should.

**Comment by rafailml** [comment]
I investigated further the problem and found out that **variables_order** in php.ini causes the problem. In production and development php.inis are set to:
```
variables_order="GPCS"; 
```

If I set 
```
variables_order="EGPCS";
```
this error is gone

**Comment by dunglas** [comment]
Good catch!
We should fix this at the Octane level. I'll do a PR.

Another option would be to change the default in FrankenPHP, but I'm not sure if it is a good idea.
