### ISSUE TITLE
Include FFI extension in binary build

### ISSUE THREAD

**Issue by binaryfire** [dunglas/frankenphp#547]
### Describe you feature request

Hi guys,

I'm unable to use packages that use FFI (eg. [jcupitt/vips](https://github.com/libvips/php-vips)) because the FFI extension isn't included in the binary build.

```
FFI extension not loaded
{
 "userId": 1,
 "exception": {
  "class": "Jcupitt\\Vips\\Exception",
  "message": "FFI extension not loaded",
  "code": 0,
  "file": "/workdir/vendor/jcupitt/vips/src/FFI.php:241"
 }
}
```

Would it be possible to add this please?

Thanks!

**Comment by dunglas** [comment]
Unfortunately, FFI is currently not supported by static-php-cli: https://static-php.dev/en/guide/extension-notes.html#ffi

You'll have to use the Docker image or compile FrankenPHP manually to use it.
