### ISSUE TITLE
PHP server runtime cannot access paths outside the specified directory

### ISSUE THREAD

**Issue by fcwys** [dunglas/frankenphp#552]
### Describe you feature request

**Is your feature request related to a problem? Please describe.**
For security reasons, it is hoped that the PHP server runtime cannot access paths outside the specified directory.

**Describe the solution you'd like**
For example, when running `frankenphp php-server -r /www`, the PHP program can only access files within the `/www` directory.

**Comment by shyim** [comment]
Isn't this just setting `open_basedir` in your php.ini?

**Comment by fcwys** [comment]
Yes.
