### ISSUE TITLE
Building static binary broken on Linux

### ISSUE THREAD

**Issue by HolgerDoerner** [dunglas/frankenphp#559]
https://github.com/dunglas/frankenphp/blob/5da805d9ee28d8124c6f83ce2b82c08bdfa920a2/build-static.sh#L126

When executing `build-static.sh` an error occours saying `md5` could not be found. The error also appears when using the Docker image.

Could be a typo or even MacOS specific. The standard util to generate/check md5 hashes on linux is `md5sum`, but that doesn't support the `-q` flag.

**Comment by dunglas** [comment]
Good catch, that's a BSD/Mac command. Don't hesitate to open a PR. I'll do it ASAP otherwise.

**Comment by HolgerDoerner** [comment]
Hi Kevin, I opened a PR to address this issue.

**Comment by dunglas** [comment]
Thank you Holger!

**Comment by alexhackney** [comment]
@HolgerDoerner I'm running in to this as well trying to build on a m3 mac. Is there a way around it for now un til this is merged? Trying to get my buiild process done.

**Comment by alexhackney** [comment]
Actually this seems to work ok

```
# Install sed
RUN apk add --no-cache sed

# Modify the build-static.sh script
RUN sed -i 's/md5 -q/md5sum/' /go/src/app/build-static.sh
```

**Comment by HolgerDoerner** [comment]
@alexhackney This would also break the build script when run on Your local machine, this will ONLY work in inside of the Docker Container.

Besides that, installing software/packages should not be done in scripts, only in Dockerfiles.

**Comment by dunglas** [comment]
Fixed by https://github.com/dunglas/frankenphp/pull/562, thanks to Holger!

**Comment by marsderp** [comment]
Hi sorry to necro this issue, I am having this issue in my Dockerfile. 

Could I be missing something? 

```sh
#15 [builder 6/6] RUN EMBED=dist/app/     ./build-static.sh
#15 0.245 ./build-static.sh: line 126: md5: not found
#15 ERROR: process "/bin/ash -eo pipefail -c EMBED=dist/app/     ./build-static.sh" did not complete successfully: exit code: 127
------
 > [builder 6/6] RUN EMBED=dist/app/     ./build-static.sh:
0.245 ./build-static.sh: line 126: md5: not found
------
Dockerfile:11
--------------------
  10 |     WORKDIR /go/src/app/
  11 | >>> RUN EMBED=dist/app/ \
  12 | >>>     ./build-static.sh
  13 |     
--------------------
```


```dockerfile
FROM --platform=linux/amd64 dunglas/frankenphp:static-builder-1.1 as builder

# Copy your app
WORKDIR /go/src/app/dist/app
COPY . .

RUN composer install --ignore-platform-reqs --no-dev -a

# Build the static binary, be sure to select only the PHP extensions you want
WORKDIR /go/src/app/
RUN EMBED=dist/app/ \
    ./build-static.sh


FROM alpine:latest

WORKDIR /app

COPY --from=builder /go/src/app/dist/frankenphp-linux-x86_64 exampleapp

EXPOSE 80

CMD ["./exampleapp", "php-server"]
```

**Comment by withinboredom** [comment]
Looks like you are somehow hitting this line? https://github.com/dunglas/frankenphp/pull/562/files#diff-548dba7efda4c2f29f4eeb946db1da090e10308817056d55077d71146f8ad0ebR15

Can you test that?

**Comment by juancamunoz** [comment]
Same issue here 😞

**Comment by withinboredom** [comment]
It looks like an image update was pushed [two days ago](https://hub.docker.com/layers/dunglas/frankenphp/static-builder/images/sha256-979d54c5b0305005b05624144e7648f219f653e813996454519a4af74f6c39c7?context=explore), is that the same image you are seeing an issue with?

**Comment by marsderp** [comment]
> Looks like you are somehow hitting this line? https://github.com/dunglas/frankenphp/pull/562/files#diff-548dba7efda4c2f29f4eeb946db1da090e10308817056d55077d71146f8ad0ebR15
> 
> Can you test that?

Getting the same error building locally from my WSL2 and running it on Github actions.

However when I run the following commands they seem to be returning the correct responses.
```sh
❯ docker run -it dunglas/frankenphp:static-builder-1.1 /bin/bash

644f6b4df145:/go/src/app# arch="$(uname -m)"
os="$(uname -s | tr '[:upper:]' '[:lower:]')"
md5binary="md5sum"
644f6b4df145:/go/src/app# echo $arch
x86_64
644f6b4df145:/go/src/app# echo $os
linux
644f6b4df145:/go/src/app# echo $md5binary
md5sum
```

**Comment by withinboredom** [comment]
That's a mystery...

As a work around, can you try `alias md5=md5sum` before running the script in the container. That should (theoretically) allow it to at least build until the mystery is resolved.

**Comment by HolgerDoerner** [comment]
@marsderp The image `dunglas/frankenphp:static-builder-1.1` does not have the updated `build-static.sh` script, that's why the error still pops up. @dunglas any idea why?

``` bash
$ docker run dunglas/frankenphp:static-builder-1.1 head -n15 build-static.sh
#!/bin/sh

set -o errexit

if ! type "git" > /dev/null; then
    echo "The \"git\" command must be installed."
    exit 1
fi

arch="$(uname -m)"
os="$(uname -s | tr '[:upper:]' '[:lower:]')"
if [ "${os}" = "darwin" ]; then
    os="mac"
fi
```

@withinboredom 
> That's a mystery...
> 
> As a work around, can you try `alias md5=md5sum` before running the script in the container. That should (theoretically) allow it to at least build until the mystery is resolved.

That will not work because `md5` is run with `-c`, which `md5sum` doesn't know. A more proper workaround was posted earlier: https://github.com/dunglas/frankenphp/issues/559#issuecomment-1936564041

**Comment by dunglas** [comment]
That's just because we need to create a new tag, the patch is currently only available in `main`: https://github.com/dunglas/frankenphp/commit/b60fc5c374ba4842afc61cf29a6bcf4fc20400ac
