### ISSUE TITLE
Worker mode seems to lose doctrine connection after a while

### ISSUE THREAD

**Issue by KDederichs** [dunglas/frankenphp#561]
### What happened?

I noticed that my database connections to RDS Proxy were failing for an unknown reason after a while (nothing changed in the configuration, everything was fine before).

After some digging I stumbled on people with similar issues where the DB connection wasn't alive anymore.

So after giving the container a restart, everything startet to work just fine again leading me to believe that somehow worker mode is causing the DB connection to die after a while.

It has to be noted that app I'm running is still being tested/has no live traffic so there's long stretches of no traffic hitting it for a while.

Edit: Actually it seems to loose the connection after changing security groups related to the DB

Edit2: Doesn't matter, it also happens after some time has passed, so original issue still stands.

### Build Type

Docker (Alpine)

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

aarch64

### Relevant log output

```shell
Some related errors surfaced in sentry:

Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 7 SSL connection has been closed unexpectedly" at ExceptionConverter.php line 87

Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 7 no connection to the server" at ExceptionConverter.php line 87
```

**Comment by withinboredom** [comment]
If you are using postgres, set your connection idle timeout really high in the configuration. I'm pretty sure MySQL and friends have something similar.

**Comment by dunglas** [comment]
This is a Doctrine/Symfony bug that is being fixed in https://github.com/symfony/symfony/pull/53214.

I think that there is nothing we can do about that in FrankenPHP itself.
