### ISSUE TITLE
Consider renaming DEBUG env var

### ISSUE THREAD

**Issue by withinboredom** [dunglas/frankenphp#57]
In the built-in Caddyfile, there is a built-in `DEBUG` env var injected. This is quite generic and may conflict with other frameworks or applications. Perhaps we should call it `FRANKENPHP_DEBUG`?

**Comment by dunglas** [comment]
We're already using the same variable to enable the debug mode of Caddy in Mercure, Symfony Docker and API Platform. Maybe could we use `CADDY_DEBUG` everywhere?
