### ISSUE TITLE
CPU consumption issue

### ISSUE THREAD

**Issue by htuscher** [dunglas/frankenphp#588]
### What happened?

I'm running [Shopware5](https://github.com/shopware5/shopware) with the following Dockerfile:

```
#syntax=docker/dockerfile:1.4
ARG BUILD_ENV=prod

FROM dunglas/frankenphp as build_prod
ONBUILD COPY --chown=1000:1000 ./app/shopware /app

FROM dunglas/frankenphp as build_dev
#RUN install-php-extensions xdebug


FROM build_${BUILD_ENV}
ENV COMPOSER_ALLOW_SUPERUSER=1
COPY --link frankenphp/conf.d/app.ini $PHP_INI_DIR/conf.d/
COPY --link frankenphp/Caddyfile /etc/caddy/Caddyfile
RUN install-php-extensions pdo_mysql gd intl zip opcache apcu mysqli mcrypt uuid redis @composer
ENV TIDEWAYS_VERSION=5.6.10
#RUN curl -o tideways-php.tar.gz "https://s3-eu-west-1.amazonaws.com/tideways/extension/${TIDEWAYS_VERSION}/tideways-php-${TIDEWAYS_VERSION}-x86_64.tar.gz" \
#    && tar xzvf tideways-php.tar.gz \
#    && cp ./tideways-${TIDEWAYS_VERSION}/tideways.so /usr/local/lib/php/extensions/no-debug-zts-20230831/ \
#    && echo "extension=tideways.so" >> /usr/local/etc/php/conf.d/docker-php-ext-tideways.ini
CMD [ "frankenphp", "run", "--config", "/etc/caddy/Caddyfile" ]
```

If I either enable xdebug or tideways, I observe the following behavior:

The request completed pretty fast, but the frankenphp process is consuming more and more CPU until it reaches 400% and then remains on the usage forever.

![image](https://github.com/dunglas/frankenphp/assets/5076356/19dd8c63-e30c-4d2d-9220-6426e91e21e6)

 

### Build Type

Docker (Debian Bookworm)

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

x86_64

**Comment by dunglas** [comment]
Are you using XDebug?

**Comment by dunglas** [comment]
Actually, this looks more like a Tideways bug: https://github.com/dunglas/frankenphp/issues/578#issuecomment-1966620351
