### ISSUE TITLE
per project Caddyfile SERVER_NAME override?

### ISSUE THREAD

**Issue by isimmons** [dunglas/frankenphp#59]
I am able to change `{$SERVER_NAME:localhost}` to `{$SERVER_NAME:demo.localhost}` in caddy/frankenphp/Cadyfile and it works. This way my url matches my Laravel .env APP_URL setting. 

Is is possible to have that setting pulled from a project level Caddyfile or preferably from a .env file instead of hard coded into the image?

**Comment by withinboredom** [comment]
You can mount a custom Caddyfile at `/etc/Caddyfile` in the image and have whatever Caddyfile you want, or set the `SERVER_NAME` variable in your environment if you're happy with the defaults.

**Comment by isimmons** [comment]
Thanks. I wanted to see if I can build the image once and then re-use it for quickly starting up new projects like the following process.

Say I've already built the image and tagged it "fphp-alpine"
```
cd my-code-directory
laravel new myproject
// open project in phpstorm and set .env APP_URL to https://myproject.localhost
// open terminal in phpstorm and run the docker command
```

I did not know the env variable in the docker command would override the image Caddyfile. Both caddy and go are new to me. This works great.

```
 docker run -e SERVER_NAME='demo.localhost' -v $PWD:/app -p 80:80 -p 443:443 fphp-alpine
```

Side note for Laravel 9 and vite: Vite needs to serve https for "npm run dev" and hot reloading to work since the app is being served over https.
Here is a working example config where I'm using inertia and vue, the relevant part being https: true and the mkcert plugin

vite.config.js

```javascript
import { defineConfig, splitVendorChunkPlugin } from "vite";
import vue from "@vitejs/plugin-vue";
import laravel from "laravel-vite-plugin";
import mkcert from "vite-plugin-mkcert";

const path = require("path");

export default defineConfig({
    server: { https: true },
    resolve: {
        alias: {
            "@": path.resolve(__dirname, "./resources/js"),
        },
        extensions: [".vue", ".js"],
    },
    plugins: [
        mkcert(),
        vue(),
        laravel({
            input: ["resources/js/app.js"],
            refresh: true,
        }),
        splitVendorChunkPlugin(),
    ],
});
```
