### ISSUE TITLE
Symfony redirect issue

### ISSUE THREAD

**Issue by hristonev** [dunglas/frankenphp#611]
### What happened?

Hello, and thanks for this server implementation! I'm working with Symfony and trying to redirect from the controller. Everything is fine in the Symfony dev server, but in Frankenphp something happened my request took infinite time to process, and after hitting refresh it was processed as usual.

### Build Type

Docker (Alpine)

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### Relevant log output

```shell
There is no log.
```

**Comment by dunglas** [comment]
Are you using some non-standard extensions such as XDebug, Tideways, or DataDog?

**Comment by hristonev** [comment]
Yes, I'm using XDebug. This was the source of all evil. Thank you very much!
