### ISSUE TITLE
Consider implementing fastcgi_finish_request()?

### ISSUE THREAD

**Issue by withinboredom** [dunglas/frankenphp#62]
[`fastcgi_finish_request`](https://www.php.net/manual/en/function.fastcgi-finish-request.php) is often used to perform operations after a request is completed (such as sending an email). Should FrankenPHP implement this and/or create a similar function? There are pro/cons to implementing it with the same name (it will "just work" with existing code), and a con would be that if there are any differences in behavior, then things may not work as expected or code may use the existence of that function as a sentinel that it is running in a fastcgi context and do unexpected things.

I'd be happy to tackle implementing this, whatever is decided.

**Comment by dunglas** [comment]
Maybe could we add a `frankenphp_finish_request()` function to prevent any conflict?
