### ISSUE TITLE
How to surcharge a caddyfile for secure header ?

### ISSUE THREAD

**Issue by kilwir76** [dunglas/frankenphp#621]
### Describe you feature request

I want to surchage a caddyfile for securing headers.

How do i do that ?

Best regards

**Comment by withinboredom** [comment]
I think you used an incorrect word: "surcharge" has to do with money, and you are asking how to get money from a caddyfile for headers.

**Comment by dunglas** [comment]
@kilwir76 if you're using vanilla FrankenPHP, you can just put a Caddyfile in the root directory of your project, then run `frankenphp run`. If you're using Laravel Octane, you can use the `--caddyfile` flag of the `octane:start` command.

In the `Caddyfile`, you can use [the `header` directive](https://caddyserver.com/docs/caddyfile/directives/header) to change the response headers.

@withinboredom "surcharger" means "to override" in French 😅

**Comment by withinboredom** [comment]
> "surcharger" means "to override" in French 😅

Oh, hahaha, that's awesome and thanks for the heads up!

**Comment by kilwir76** [comment]
Sorry for my disastrous English ^^, so I create my Caddyfile at the root of my project and I override the one in /etc/caddy/?

If so can I take the basic one in /etc/caddy?

If not, what more should I do?

Knowing that my application is a symfony application under the dockerfile present on your site

**Comment by dunglas** [comment]
Yes you can adapt the modify or replace the `Caddyfile` that is in `/etc/caddy`. If you're using Docker that's probably the easiest way.

**Comment by kilwir76** [comment]
Yes of course , so i can copy the existing caddyfile on /etc/caddy and the adapter for my needs
