### ISSUE TITLE
Docs: Unclickable elements above the h2 style

### ISSUE THREAD

**Issue by crazywhalecc** [dunglas/frankenphp#625]
![image](https://github.com/dunglas/frankenphp/assets/20330940/836d06af-000a-4753-9827-e0ff7679b444)

![image](https://github.com/dunglas/frankenphp/assets/20330940/46e9670d-9c5d-4438-9086-5dcfa8b7050a)

Seems `-mt-20` makes the link above the h2 title unclickable. (Second screenshot, red part is not clickable and green is good)

**Comment by dunglas** [comment]
Fixed, thanks!
