### ISSUE TITLE
Add PHP 8.1 Docker images until end of security support period

### ISSUE THREAD

**Issue by binaryfire** [dunglas/frankenphp#637]
### Describe you feature request

Hi Kevin

I've got an app running on PHP 8.1 that the customer doesn't want to update until later this year. PHP 8.1 is [supported until November](https://www.php.net/supported-versions.php) - would it be possible to add 8.1 Docker images?

**Comment by dunglas** [comment]
Unfortunately no, FrankenPHP needs PHP (internal) features that has been introduced in 8.2.

**Comment by binaryfire** [comment]
Ok no problems, thanks.
