### ISSUE TITLE
[QUESTION] Laravel + inertial + vuejs

### ISSUE THREAD

**Issue by ezekel** [dunglas/frankenphp#639]
### What happened?

Hi,  I am using Laravel + Inertia + Vuejs,  below is my dockerfile.

My questions:

1. Is it okay to install other packages like composer, nvm, supervisor, etc in 1 Dockerfile with the frankenphp image?
2. How can I run npm run dev or npm run build, when I spin a container so that I will not exec to the container just to run the command npm run dev or npm run build?

```
FROM dunglas/frankenphp:latest


# Add additional PHP extensions here:
RUN install-php-extensions \
    pdo_mysql \
    gd \
    intl \
    zip \
    opcache \
    curl

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

// Installing some other packages here like NVM , supervisor, etc...


COPY . /app

RUN npm install
```

Thank you in advance.

WORKDIR /app

### Build Type

Official static build

### Worker Mode

No

### Operating System

Other (tell us more in the description)

### CPU Architecture

x86_64

### PHP configuration

```shell
not relevant to my question
```

**Comment by sneycampos** [comment]
1. i think install composer and some dev dependencies while you are in dev process its ok, you can skip these tools in production using multi-stage docker builds

2. you can achieve this in two ways: 
    2.1 - creating a .sh file, add these commands in the .sh file and at the end of the file you call frankenphp command and change your dockerfile entrypoint to use these sh script.
    2.2 - using a caddy module, like i did in [this repository](https://github.com/sneycampos/laravel-octane-frankenphp) 
take a look at these files: [Dockerfile](https://github.com/sneycampos/laravel-octane-frankenphp/blob/master/Dockerfile) and [octane.Caddyfile](https://github.com/sneycampos/laravel-octane-frankenphp/blob/master/octane.Caddyfile)

made the same question in this [issue](https://github.com/dunglas/frankenphp/issues/643).

nb: i don't know if this way is the right nor best way "but works"

**Comment by ezekel** [comment]
@sneycampos Thank you for the reply, I will check on those links
