### ISSUE TITLE
Add non ZTS build version

### ISSUE THREAD

**Issue by tsantos84** [dunglas/frankenphp#644]
### What happened?

I'm trying to install New Relic agent but the installation process stops with the following error:

```
An unsupported PHP ZTS build has been detected. Please refer to this link:
https://docs.newrelic.com/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements/
view compatibilty requirements for the the New Relic PHP agent.
```

Newest versions of NewRelic agent no longer support PHP builds with ZTS.

I figured out that you use a `ZTS` PHP build as base image. Using `ZTS` is something mandatory to Frankenphp or can you provide builds of your image without `ZTS`?

### Build Type

Docker (Debian Bookworm)

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
N/A
```

### Relevant log output

```shell
An unsupported PHP ZTS build has been detected. Please refer to this link:
https://docs.newrelic.com/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements/
view compatibilty requirements for the the New Relic PHP agent.
```

**Comment by dunglas** [comment]
This isn't technically possible. FrankenPHP uses threads and goroutines, which require ZTS builds.

**Comment by rvanlaak** [comment]
@tsantos84  when reading your issue; you mean @newrelic dropped ZTS support and that is the main reason why their agent module doesn't allow being installed together with frankenphp / caddy anymore?

**Comment by tsantos84** [comment]
> [@tsantos84](https://github.com/tsantos84) when reading your issue; you mean [@newrelic](https://github.com/newrelic) dropped ZTS support and that is the main reason why their agent module doesn't allow being installed together with frankenphp / caddy anymore?

Hi @rvanlaak, yes. @newrelic stopped supporting ZTS as of 9.19.0.309 agent version.

**Comment by rvanlaak** [comment]
Any rationales you found on the 'why', as they themselves solely share the fact that it has been removed (e.g. ref [#233](https://github.com/newrelic/newrelic-php-agent/issues/233)).

**Comment by tsantos84** [comment]
> Any rationales you found on the 'why', as they themselves solely share the fact that it has been removed (e.g. ref [#233](https://github.com/newrelic/newrelic-php-agent/issues/233)).

No, I didn't found the reason they dropped the support for ZTS.
