### ISSUE TITLE
Cannot run artisan tinker: Call to undefined function cli_set_process_title().

### ISSUE THREAD

**Issue by sawirricardo** [dunglas/frankenphp#661]
### What happened?

After built the single binaries, we cannot execute php-cli artisan tinker
![image](https://github.com/dunglas/frankenphp/assets/37329575/c230dff1-4b02-449b-8492-dfdb976f07e6)

### Build Type

Official static build

### Worker Mode

No

### Operating System

macOS

### CPU Architecture

Apple Silicon

### PHP configuration

```shell
php comes from frankenphp
```

**Comment by dunglas** [comment]
Closing as duplicate of #587.
