### ISSUE TITLE
Prometheus / metrics

### ISSUE THREAD

**Issue by codeagencybe** [dunglas/frankenphp#668]
### Describe you feature request

**Is your feature request related to a problem? Please describe.**
I need insights metrics from the performance of Frankenphp (with Wordpress) into my Grafana dashboard. 
Does Frankenphp already expose some metrics in some way? 

**Describe the solution you'd like**
Performance metrics endpoint(s) similar to regular PHP, Nodejs, ... that is done with Prometheus, Tracing, Jaeger, ...

**Comment by dunglas** [comment]
FrankenPHP exposes all Caddy and Mercure metrics: https://caddyserver.com/docs/metrics

It could be nice (and easy) to add some PHP-realted metrics, if relevant.

**Comment by dunglas** [comment]
Closing in favor of the existing feature request: https://github.com/dunglas/frankenphp/issues/269
