### ISSUE TITLE
Auto-restart frankenphp in worker mode on file changes (for Docker local development)

### ISSUE THREAD

**Issue by binaryfire** [dunglas/frankenphp#669]
### Describe you feature request

Opening an issue for this so it doesn't get forgotten. Discussion: https://github.com/dunglas/frankenphp/discussions/556

The custom solution I implemented was using lots of CPU so I had to disable it. It'd be great to have a built in way of handling this. Currently I'm restarting the container manually every time I make a file change 😵‍💫 

Would it be difficult to add this to the container image as a `--watch` flag?

**Comment by dunglas** [comment]
It's on my todo list!

**Comment by andypost** [comment]
Is there a forceful way to reload config, looks like `php-server` is blocking AdminAPI and no `SIGHUP` supported

**Comment by andypost** [comment]
Using `frankenphp run -c Caddyfile` allows API for reload

**Comment by dunglas** [comment]
For the record, this feature is being developed in https://github.com/dunglas/frankenphp/pull/1013.

**Comment by S1ructure** [comment]
Since #1013 is merged - can this be closed here?
