### ISSUE TITLE
shmop_open() does not exist

### ISSUE THREAD

**Issue by remco-pc** [dunglas/frankenphp#689]
### What happened?

i try to run my framework which uses shared Memory for some parts and found this error 

### Build Type

Docker (Debian Bookworm)

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
could not fit...
 (There was an error creating your issue: body is too long (maximum is 65536 characters).) but default configuration
```

### Relevant log output

```shell
also the 1 at the end should not be there i guess.
```

**Comment by dunglas** [comment]
Did you install/compile the shmop extension?

**Comment by remco-pc** [comment]
How to do that? i used your latest binary in a docker debian image.

**Comment by dunglas** [comment]
If you use Docker, you don't need to download the binary, use this instead: https://frankenphp.dev/docs/docker/#how-to-install-more-php-extensions

This extension isn't bundled with the static binary we propose, but as it is supported by static-php-cli, feel free to open a PR to add it to the default list.
