### ISSUE TITLE
Unable to install php extensions 

### ISSUE THREAD

**Issue by Asociateone** [dunglas/frankenphp#697]
### What happened?

I am currently running the latest FrankenPhp in a docker container with caddy_reverse proxy routing it to the correct container:
```
FROM dunglas/frankenphp:latest

RUN install-php-extensions \
	pdo_mysql \
	gd \
	intl \
	zip \
	opcache
```

and the following compose.yaml
```
services:
  frankenphp:
    build:
      context: .
    container_name: containername
    image: dunglas/frankenphp:latest
    restart: always
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - containernetwork
      - caddy_caddy
    environment:
      SERVER_NAME: :80
```
when trying to build it with the following command:

```
docker build -t containername .
```
I am recieving the following issue:
```
 => => # install-php-extensions v.2.2.5
 => => # #StandWithUkraine
 => => # Updating channel "pecl.php.net"
 => => # Channel "pecl.php.net" is not responding over http://, failed with message: Connection to `pecl.php.net:80' failed: php_network_getaddresses: getaddrinfo for pecl.php.net failed: Temporary failure in name resolution
 => => # Trying channel "pecl.php.net" over https:// instead
 => => # Cannot retrieve channel.xml for channel "pecl.php.net" (Connection to `ssl://pecl.php.net:443' failed: php_network_getaddresses: getaddrinfo for pecl.php.net failed: Temporary failure in name resolution)

```

Its currently running on a 6$ VPS droplet from DigitalOcean

if i exec and install the extensions manually through `apt-get` it works but it is not the preferred way to do so.

When using the following item in the Dockerfile it does install something but i think it needs more configuration to make it work:

```
RUN docker-php-ext-install pdo_mysql
```

### Build Type

Docker (Debian Bookworm)

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

Other (tell us more in the description)

### PHP configuration

```shell
no need ^
```

**Comment by dunglas** [comment]
This is a network issue when contacting the PECL server (this happens sometimes). There is nothing we can do on our side. The issue can either be a temporary issue on PHP side, or a network issue on DigitalOcean side. If the problem persists, maybe should you contact the DO support.
