### ISSUE TITLE
Edge Side Include (ESI) and/or Server Side Includes (SSI) support

### ISSUE THREAD

**Issue by Crovitche-1623** [dunglas/frankenphp#700]
### Describe you feature request

Since FrankenPHP is integrated by default on the Symfony Docker environment, what is its progress status on ESI / SSI? Are these features implemented, and if so, how do you use them ?

**Comment by dunglas** [comment]
ESI are supported by adding the extra `cache-handler` Caddy module, which, under the hood, relies on Souin.

We'll add it by default when it will be more mature, but more work as to be done on Souin side first (especially, extracting the adapters to 3rd party cache systems in dedicated modules to prevent adding too many dependencies).
