### ISSUE TITLE
Cant build binary by Docker

### ISSUE THREAD

**Issue by grandrr** [dunglas/frankenphp#709]
### What happened?

So i clone latest repo:
https://github.com/dunglas/frankenphp
and as in description had try run command for build binary by Docker:
`docker buildx bake --load static-builder
docker cp $(docker create --name static-builder dunglas/frankenphp:static-builder):/go/src/app/dist/frankenphp-linux-$(uname -m) frankenphp ; docker rm static-builder`

Os vesrion:
Sonoma 14.4.1

### Build Type

Standalone binary

### Worker Mode

Yes

### Operating System

macOS

### CPU Architecture

x86_64

### PHP configuration

```shell
8.2
```

### Relevant log output

```shell
volodymyrustinov@Volodymyrs-MacBook-Pro frankenphp % docker buildx bake --load static-builder
[+] Building 0.0s (0/0)                                                                                                                                                                                                   
docker-bake.hcl:78
--------------------
  76 |     target "default" {
  77 |         name = "${tgt}-php-${replace(php-version, ".", "-")}-${os}"
  78 | >>>     matrix = {
  79 |             os = ["bookworm", "alpine"]
  80 |             php-version = split(",", PHP_VERSION)
--------------------
error: docker-bake.hcl:78,5-11: Unsupported argument; An argument named "matrix" is not expected here., and 15 other diagnostic(s)
```

**Comment by dunglas** [comment]
Closing in favor of https://github.com/crazywhalecc/static-php-cli/issues/405#issuecomment-2048059556.
