### ISSUE TITLE
{"message":"API rate limit exceeded for 149.104.118.59. (But here's the good news: Authenticated requests get a higher r (truncated...)

### ISSUE THREAD

**Issue by jorycn** [dunglas/frankenphp#722]
### What happened?

octane:install binary download error

### Build Type

Standalone binary

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
~
```

**Comment by dunglas** [comment]
It seems that you hit the GitHub API limit. There is nothing we can do on our side about this.

**Comment by jorycn** [comment]
Thank you for your prompt response
