### ISSUE TITLE
This localhost page can’t be found

### ISSUE THREAD

**Issue by skmirajbn** [dunglas/frankenphp#723]
### What happened?

I followed the insturctions from [here](https://frankenphp.dev/docs/embed/) to create self contained binary file.
I created and extracted the binary file on linux. And started the file using this command

./my-app php-server --domain localhost

But when I got to localhost on my browser got this 

![image](https://github.com/dunglas/frankenphp/assets/67829716/3a563583-bf46-4dc3-bfe8-74126df07943)

Here is my Terminal
![image](https://github.com/dunglas/frankenphp/assets/67829716/7e1c3662-3f98-4cf0-af6b-203d2ea9e7fe)

Can't figure out where is the problem and why the app is not opening.

I used latest laravel 11 fresh project to check if it is working or not. Same problem I faced with my main laravel 8 product I thought that time maybe this is my project issue so that's why I tried with latest laravel 11 fresh project but problem remain same. 

### Build Type

Standalone binary

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
Here is my Docker static build dockerfile

FROM --platform=linux/amd64 dunglas/frankenphp:static-builder

# Copy your app
WORKDIR /go/src/app/dist/app
COPY . .

# Build the static binary, be sure to select only the PHP extensions you want
WORKDIR /go/src/app/
RUN ./dist/frankenphp-linux-x86_64 version \
    export FRANKENPHP_VERSION=1.1.2 \
    EMBED=dist/app/ \
    ./build-static.sh
```

### Relevant log output

```shell
skmiraj@skmiraj-VirtualBox:~/Desktop/test-binary$ sudo ./my-app php-server --domain localhost

[sudo] password for skmiraj: 

2024/04/14 10:54:10.516	WARN	admin	admin endpoint disabled

2024/04/14 10:54:10.527	INFO	http.auto_https	server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS	{"server_name": "php", "https_port": 443}

2024/04/14 10:54:10.527	INFO	http.auto_https	enabling automatic HTTP->HTTPS redirects	{"server_name": "php"}

2024/04/14 10:54:10.532	INFO	tls.cache.maintenance	started background certificate maintenance	{"cache": "0xc0000fc400"}

2024/04/14 10:54:10.610	INFO	FrankenPHP started 🐘	{"php_version": "8.3.6"}

2024/04/14 10:54:10.831	WARN	tls	storage cleaning happened too recently; skipping for now	{"storage": "FileStorage:/root/.local/share/caddy", "instance": "497a5137-3bb8-4f23-acee-29d5c4261586", "try_again": "2024/04/15 10:54:10.831", "try_again_in": 86399.99999929}

2024/04/14 10:54:10.840	INFO	tls	finished cleaning storage units

2024/04/14 10:54:11.039	INFO	pki.ca.local	root certificate is already trusted by system	{"path": "storage:pki/authorities/local/root.crt"}

2024/04/14 10:54:11.088	INFO	http	enabling HTTP/3 listener	{"addr": ":443"}

2024/04/14 10:54:11.103	INFO	http.log	server running	{"name": "php", "protocols": ["h1", "h2", "h3"]}

2024/04/14 10:54:11.122	INFO	http.log	server running	{"name": "remaining_auto_https_redirects", "protocols": ["h1", "h2", "h3"]}

2024/04/14 10:54:11.122	INFO	http	enabling automatic TLS certificate management	{"domains": ["localhost"]}

2024/04/14 10:54:11.247	WARN	tls	stapling OCSP	{"error": "no OCSP stapling for [localhost]: no OCSP server specified in certificate", "identifiers": ["localhost"]}

2024/04/14 10:54:11.248	INFO	Caddy serving PHP app on :443

2024/04/14 10:54:11.248	INFO	tls.renew	acquiring lock	{"identifier": "localhost"}

2024/04/14 10:54:11.286	INFO	tls.renew	lock acquired	{"identifier": "localhost"}

2024/04/14 10:54:11.293	INFO	tls.renew	renewing certificate	{"identifier": "localhost", "remaining": -10890.29391022}

2024/04/14 10:54:11.300	INFO	tls.renew	certificate renewed successfully{"identifier": "localhost"}

2024/04/14 10:54:11.313	INFO	tls.renew	releasing lock	{"identifier": "localhost"}

2024/04/14 10:54:11.313	INFO	tls	reloading managed certificate	{"identifiers": ["localhost"]}

2024/04/14 10:54:11.315	WARN	tls	stapling OCSP	{"error": "no OCSP stapling for [localhost]: no OCSP server specified in certificate", "identifiers": ["localhost"]}

2024/04/14 10:54:11.315	INFO	tls.cache	replaced certificate in cache	{"subjects": ["localhost"], "new_expiration": "2024/04/14 22:54:12.000"}
```

**Comment by withinboredom** [comment]
php-server starts a server in your current directory, just like the --help says. Try `run`.

**Comment by skmirajbn** [comment]
> php-server starts a server in your current directory, just like the --help says. Try `run`.

Hello, I tried to run but not working. I opened the terminal where the binary file 

![image](https://github.com/dunglas/frankenphp/assets/67829716/b6b74dca-2793-4ebf-97e0-6eb4b1384d85)

after running this in browser local host the app is not loading

![image](https://github.com/dunglas/frankenphp/assets/67829716/c0f2e584-0ad1-4eda-80c7-a9097f6d1d65)

I can't get any way to get it worked. 

If you provide me little more details about the solution it would help me a lot. 

Sorry for bothering you.

**Comment by withinboredom** [comment]
I can see where you run `php-server` on your terminal. As stated, it won't work that way. Try `start` or `run` and if you have an issue with that command, that would possibly be a separate issue.

> Sorry for bothering you.

It's not a bother and sorry if it came across a bit short! This repo is quite active and staying on top of things takes time. FYI, this issue is also a duplicate of #714, where your issue is currently being discussed and potential solutions are being considered.
