### ISSUE TITLE
Unable to Create Self-Contained PHP Binary App: Seeking Assistance

### ISSUE THREAD

**Issue by skmirajbn** [dunglas/frankenphp#732]
### What happened?

Over the past 4-5 days, I've been attempting to create and run a self-contained PHP binary app, but I've been unsuccessful. I'm not sure if others are encountering the same issue or if it's unique to me.

I followed the instructions provided [here](https://frankenphp.dev/docs/embed/), but encountered an error stating "not a git repository." After researching, I found discussions about this problem and attempted various suggested solutions, but none have worked for me.

Even though the Git error issue is resolved, a new problem has arisen.

I even tried starting with a fresh Laravel app and a simple index.php file with just a "Hello World" message, but neither worked.

Currently, I'm using the following Dockerfile:

------------------------------
```
FROM --platform=linux/amd64 dunglas/frankenphp:static-builder as builder

WORKDIR /go/src/app/dist/app

COPY . .

# RUN composer install --ignore-platform-reqs --no-dev -a

WORKDIR /go/src/app/

RUN ./dist/frankenphp-linux-x86_64 version \
    EMBED=dist/app/ \
    ./build-static.sh

FROM alpine:3.19.0

WORKDIR /app

COPY --from=builder /go/src/app/dist/frankenphp-linux-x86_64 laravel-app

EXPOSE 80

CMD ["./laravel-app", "php-server"];
```

--------------------------

This Dockerfile successfully creates a binary, but unfortunately, when I try to access it through a browser, it doesn't load or work.

I'm feeling quite frustrated and exhausted from trying to fix this issue without success. If anyone can offer assistance, I would greatly appreciate it.

:(

### Build Type

Standalone binary

### Worker Mode

No

### Operating System

Other (tell us more in the description)

### CPU Architecture

x86_64

### PHP configuration

```shell
This docker file I used

FROM --platform=linux/amd64 dunglas/frankenphp:static-builder as builder

WORKDIR /go/src/app/dist/app

COPY . .

# RUN composer install --ignore-platform-reqs --no-dev -a

WORKDIR /go/src/app/

RUN ./dist/frankenphp-linux-x86_64 version \
    EMBED=dist/app/ \
    ./build-static.sh

FROM alpine:3.19.0

WORKDIR /app

COPY --from=builder /go/src/app/dist/frankenphp-linux-x86_64 laravel-app

EXPOSE 80

CMD ["./laravel-app", "php-server"];
```

**Comment by withinboredom** [comment]
As mentioned in other issues and the documentation, `php-server` starts "a simple php server in the current directory" which is probably not what you want to do when embedding an app. Instead, you probably want to change the last line in your dockerfile to run the embedded app.

**Comment by skmirajbn** [comment]
I both tried run and start for simple index.php and also for fresh laravel application root folder. But nothing worked for me. That's why I am seeking for help. 
I don't find where is actually the problem. 
I tried on windows using docker like this. I tried on Linux operating system using a virtual box. 
Nothing has worked for me. 
![image](https://github.com/dunglas/frankenphp/assets/67829716/cde3d9a9-d58d-45cc-b598-b7105b20e16a)

This is not worked for me. The binary is created inside the new image but when try to run it it shows it starts but nothing on localhost. 
![image](https://github.com/dunglas/frankenphp/assets/67829716/22b6b963-80b2-4e89-93f7-179733bfc8cc)
:(

**Comment by dunglas** [comment]
@withinboredom `php-server` is the recommended way for embedded apps. `run` will only work if a custom Caddyfile is provided.

**Comment by skmirajbn** [comment]
Is there any solve of this problem to just get the PHP app run here? I do need source-embedded binary. Because I have a project which needs to ship to the client's local PC without sharing the main PHP source code. I tried 4-5 days to get it worked but failed.

**Comment by dunglas** [comment]
Will take a look but there are many changes that the issue is on your side because we extensively tested this feature. If it's an urgent need, we also provide paid services and will definitely be able to fix your app.

**Comment by skmirajbn** [comment]
According to the documentation, I should be able to create a self-contained binary file of a PHP app. I'll try my project later, but first, I need to run any self-contained PHP binary app. That's why I just tested a fresh Laravel project and also just a simple index.php file to check if the feature in the documentation works or not.

If any app (or just a fresh Laravel project) can be run from the binary file from my side to check if it works, I would be happy.

**Comment by withinboredom** [comment]
> php-server is the recommended way for embedded apps. run will only work if a custom Caddyfile is provided.

Ah crap. I've been saying the wrong thing. Thanks for pointing it out!

**Comment by grandrr** [comment]
I can confirm that its not work with EMBED path. I had manage compile it and run, but it run with context file `index.php` is in `public` folder in same place where binary is located.
In documentation i am not really understand what is EMBED, its path to php app, but how this app should looks like? what is entry file, by debugging i understand it should be app in format of folder `public` with `index.php` file inside.

**Comment by grandrr** [comment]
skmirajbn
Take a look here:
https://github.com/dunglas/frankenphp/issues/748

**Comment by skmirajbn** [comment]
> [skmirajbn](https://github.com/skmirajbn) Please, take a look here: #748

Thanks a lot. It solved.
