### ISSUE TITLE
[ Feature request ] UPX seems too slow

### ISSUE THREAD

**Issue by 7system7** [dunglas/frankenphp#750]
### Describe you feature request

**Is your feature request related to a problem? Please describe.**
I do not know that, if the problem is w/ the UPX, or it is some unused parameters but while it is compressing, it works only in single-threading mode.

![image](https://github.com/dunglas/frankenphp/assets/3964568/0f009362-37af-46ac-aafc-acb7955b13f5)

I have a medium sized API Platform application, and the compression took ~15-16 min. While all unnecessary files have been deleted from the project, included the `node_modules`, `.git` and so on.

![image](https://github.com/dunglas/frankenphp/assets/3964568/d1079711-7c6a-4a03-8c4b-95dce1bb3f18)

**Describe the solution you'd like**
If is there any argument to change this behaviour to change the compression to multithreading, it should be the default. It would drastically increase compression speed. Or if it can be solved through scaling the Docker image, then it should be documented in FrankenPHP's docs.

The created file & this idea w/ PHP is awesome, but it cannot be used in CD, because it can be a neverending story i.e. on a VPS.

**Describe alternatives you've considered**
Play a chess party while it builds.

**Comment by dunglas** [comment]
UPX doesn't seem to support multithreading, and there is nothing we can do on our side about it: https://github.com/upx/upx/issues/310

If UPX is too slow, you can now disable it by setting the `NO_COMPRESS` env var to `1`. The binary will be larger, but the build time will better.

Closing as I don't see what else we can do.
