### ISSUE TITLE
[QUESTION] Can we use cloudfare with frankenphp?

### ISSUE THREAD

**Issue by kilwir76** [dunglas/frankenphp#751]
### Describe you feature request

**Can you run a project symfony with frankenphp on VPS and use cloudfare ? .**
I put an sf project into production on my vps with frankenphp.

I would like to be able to use cloudfare for the proxy server.

Is this really possible?

Because I did some tests but I crashed my server more than anything else.

Best regards

**Comment by dunglas** [comment]
Yes, it is (I do it). But please use Discussions for this kind of support questions.
Also, we'll need more detail about your crashes (logs, config...).
