### ISSUE TITLE
Cannot set/build locales

### ISSUE THREAD

**Issue by J-Cake** [dunglas/frankenphp#758]
### What happened?

For some reason, I'm required to build the locale `en_GB-UTF-8` but the necessary sources don't seem to be included in the docker image. 

```
$ locale-gen
bash: locale-gen: command not found

$ ls /usr/share/i18n
ls: cannot access '/usr/share/i18n': No such file or directory

$ dpkg-reconfigure locales
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
dpkg-query: package 'locales' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
/usr/sbin/dpkg-reconfigure: locales is not installed

$ apt install locales
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package locales is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'locales' has no installation candidate
```

### Build Type

Docker (Debian Bookworm)

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
Cannot produce
```

**Comment by withinboredom** [comment]
The frankenphp containers a based on the library PHP containers. So you'll have to do the same thing as if you were building on them.

**Comment by J-Cake** [comment]
Yes I ended up working this out. Truthfully, I ended up building my own container based on Alpine and using a prebuilt FrankenPHP version. If you want, I can write up a tutorial for that in a PR
