### ISSUE TITLE
[QUESTION] Worker script

### ISSUE THREAD

**Issue by ezekel** [dunglas/frankenphp#760]
Hi,

Can someone enlighten my mind on this what is Worker script ?

FRANKENPHP_CONFIG="worker /app/path/to/your/worker/script.php"

what is inside on it script.php ? 

I am using Laravel what should I put on the script.php ?

please give me examples

Thank you in advance

**Comment by dunglas** [comment]
If you are using Laravel, use Octane, it provides the worker script that you need: https://frankenphp.dev/docs/laravel/#laravel-octane

**Comment by ezekel** [comment]
@dunglas 

Thank you for the quick reply, the script you mean is the config/octane.php ?

**Comment by ezekel** [comment]
what script is that?

**Comment by dunglas** [comment]
This one: https://github.com/laravel/octane/blob/2.x/bin/frankenphp-worker.php

It is automatically installed and used by Laravel Octane.

**Comment by ezekel** [comment]
Thank you
