### ISSUE TITLE
404 from Caddy when running the onenliner docker run command

### ISSUE THREAD

**Issue by danwie** [dunglas/frankenphp#771]
I'm a complete beginner in frankenphp. I want to try it out. I'm using Docker Desktop on macOS Sonoma 14.4.1.

When using the oneliner `docker run -v $PWD:/app/public -p 443:443 dunglas/frankenphp`. When accessing https://localhost I get 404 Not Found. When checking the response headers I can see that server is Caddy. I've also tried changing the port to 8443 but that didn't help. I have also added my own test.txt in the $PWD directory - but accessing https://localhost/test.txt also gives 404.

I'm unable to find the caddy error log so I'm not sure how to proceed. What have I done wrong?

**Comment by dunglas** [comment]
FrankenPHP is a custom build of Caddy with a built-in PHP module, so references to Caddy in the headers are normal.

Are you using a framework such as Laravel or Symfony? In this case, the document root is usually `$PWD/public` and you should use this command: `docker run -v $PWD:/app-p 443:443 dunglas/frankenphp`.

**Comment by danwie** [comment]
Thank you @dunglas. Now I got the phpinfo() page when accessing https://localhost
