### ISSUE TITLE
[QUESTION] docker hub image tags

### ISSUE THREAD

**Issue by ezekel** [dunglas/frankenphp#799]
Hi ,

 I am confuse what is the difference of this tags , and which one should I pull to use in my dockerfile ?

> dunglas/frankenphp:static-builder-sha-73e9b64

> dunglas/frankenphp:sha-469070c-builder-php8.3-alpine

> dunglas/frankenphp:sha-e7e0dbf-php8.3-bookworm

Thank you in advance

**Comment by withinboredom** [comment]
Maybe we should update the readme in Docker hub explaining the tag formulas?

**Comment by dunglas** [comment]
We definitely need to improve the docs.

The main images (no specific variant) are FrankenPHP itself.
"builder" variants are for building FrankenPHP with custom Caddy modules: https://frankenphp.dev/docs/docker/#how-to-install-more-caddy-modules
"static-builder" variants are for creating statically compiled builds of FrankenPHP as well as embedding PHP apps in the binary itself: https://frankenphp.dev/docs/static/#linux

**Comment by aungmyatmoethegreat** [comment]
Please improve the tag name resolution; it's difficult to understand. I am in the process of formalizing all the tags in my Dockerfile.

<img width="1470" alt="Screenshot 2024-05-24 at 1 35 43 PM" src="https://github.com/dunglas/frankenphp/assets/65492233/d9182e76-250b-4a6b-8d92-cfa6184ece5e">

**Comment by dunglas** [comment]
This is ongoing. Closing in favor of https://github.com/dunglas/frankenphp/issues/776, which tracks the progress on this topic.
