### ISSUE TITLE
ImageMagick not installed

### ISSUE THREAD

**Issue by yormy** [dunglas/frankenphp#820]
### What happened?

I am trying to use ImageMagick on docker frankenphp 1.1.5, but it seems not to be installed, and when I want to install it in my docker then it breaks during "pecl install imagick"

Any idea how I can get imagick to work again ?

My previous image "FROM dunglas/frankenphp:1.0.3-php8.2" did not have this problem and I could install imagick without problems

### Build Type

Docker (Alpine)

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
.
```

### Relevant log output

```shell
.
```

**Comment by yormy** [comment]
apparently there is a bug in the upstream.
This works
```RUN install-php-extensions imagick/imagick@master```

**Comment by dunglas** [comment]
Thanks for the feedback. Closing as this is fixed upstream.

**Comment by uncaught** [comment]
Sorry to jump on here, but if this was fixed upstream already in May 2024, the last release was [April 2025](https://github.com/Imagick/imagick/releases), why is this still broken?

```Dockerfile
FROM dunglas/frankenphp:1.10.1-php8.5.0-trixie
RUN install-php-extensions imagick
```

this runs into:

```
27.00 /tmp/pear/temp/imagick/imagick.c:28:10: fatal error: ext/standard/php_smart_string.h: No such file or directory
27.00    28 | #include "ext/standard/php_smart_string.h"
27.00       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
27.00 compilation terminated.
27.01 make: *** [Makefile:226: imagick.lo] Error 1
```

However, using `RUN install-php-extensions imagick/imagick@master` works.

But I'm hesitant to use "master" anything in production.

**Comment by henderkes** [comment]
imagick does not have a release compatible with php 8.5 yet. Your only options are either using imagick@master or using php 8.4.
