### ISSUE TITLE
[QUESTION] Do we have discord ?

### ISSUE THREAD

**Issue by ezekel** [dunglas/frankenphp#823]
Hi Guyz,

Do we have discord for frankenphp ? so that all questions and help will be route to discord then issue will be here github ?

Thank you in advance.

**Comment by Seb33300** [comment]
You should use discussions for this: https://github.com/dunglas/frankenphp/discussions

**Comment by withinboredom** [comment]
I've used Discord before to maintain an open-source project, and the number of times I answered the exact same questions on a daily basis was very much above 10. Using GitHub discussions and issues makes things searchable and very easy to search. Further, it lets people/maintainers/contributors/experts respond in batches, do proper research, and respond with intent.

**Comment by ezekel** [comment]
Thank you
