### ISSUE TITLE
Xcaddy won't build

### ISSUE THREAD

**Issue by bpolaszek** [dunglas/frankenphp#825]
### What happened?

Hello there, I tried building FrankenPHP with Xcaddy but it crashes (MacOS Sonoma, Apple M1).

Copy/pasted from the docs:

```bash
CGO_ENABLED=1 \
XCADDY_GO_BUILD_FLAGS="-ldflags '-w -s'" \
xcaddy build \
    --output frankenphp \
    --with github.com/dunglas/frankenphp/caddy \
    --with github.com/dunglas/mercure/caddy \
    --with github.com/dunglas/vulcain/caddy
```

```
xcaddy version
v0.3.5 h1:XyC3clncb2Q3gTQC6hOJerRt3FS9+vAljW1f8jlryZA=
```

```
go version
go version go1.22.3 darwin/arm64
```

Any ideas?

### Build Type

Custom (tell us more in the description)

### Worker Mode

No

### Operating System

macOS

### CPU Architecture

Apple Silicon

### PHP configuration

```shell
N/A
```

### Relevant log output

```shell
2024/05/29 09:39:05 [INFO] exec (timeout=0s): /opt/homebrew/bin/go get -d -v -ldflags -w -s
2024/05/29 09:39:05 [INFO] Build environment ready
2024/05/29 09:39:05 [INFO] Building Caddy
2024/05/29 09:39:05 [INFO] exec (timeout=0s): /opt/homebrew/bin/go mod tidy -e
2024/05/29 09:39:05 [INFO] exec (timeout=0s): /opt/homebrew/bin/go build -o /opt/homebrew/bin/frankenphp -ldflags -w -s
# github.com/dunglas/frankenphp
In file included from /Users/benoit/go/pkg/mod/github.com/dunglas/frankenphp@v1.1.5/cgi.go:3:
./frankenphp.h:4:10: fatal error: 'Zend/zend_types.h' file not found
#include <Zend/zend_types.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
2024/05/29 09:39:07 [INFO] Cleaning up temporary folder: /opt/homebrew/bin/buildenv_2024-05-29-0939.1205888312
2024/05/29 09:39:07 [FATAL] exit status 1
```

**Comment by dunglas** [comment]
PHP sources are missing (they are included in the builder images we provide), otherwise you need to install them by yourself as described in the "compile form sources" docs.

**Comment by dunglas** [comment]
It looks like you didn't enable ZTS support. Did you compile PHP with these flags: https://frankenphp.dev/docs/compile/#linux ?

As FrankenPHP uses cgo (because PHP is written in C), it's more complicated to build than usual C programs. You need libphp compiled with the proper options.

**Comment by nikspyratos** [comment]
I'm having the same error of of `'Zend/zend_types.h' file not found` in the static builds (trying to build a Laravel app) instead of while building xcaddy. Also on Sonoma.
