### ISSUE TITLE
Question: why app.tar not getting zipped?

### ISSUE THREAD

**Issue by gonejack** [dunglas/frankenphp#834]
https://github.com/dunglas/frankenphp/blob/0b4a427cac1da044518ada44345bbafd98a0bc04/build-static.sh#L226

Php project could be up to hundred megabytes in my experiences expecially using composer.

It look like `tar -acf app.tar.gz -C "${EMBED}" .` would save a lot of space.

**Comment by dunglas** [comment]
@gonejack The whole binary (including the PHP files if I recall correctly) is already compressed using `upx`. Compressing the PHP files before compressing the binary will likely increase the final size.

We may add support for compression for Mac binaries however, as upx doesn't support Apple Silicon yet.
