### ISSUE TITLE
Incorrect condition in worker loop in documentation?

### ISSUE THREAD

**Issue by TimWolla** [dunglas/frankenphp#853]
### What happened?

I used the code snippet in the FrankenPHP documentation and forgot to set the `MAX_REQUESTS` environment variable.

FrankenPHP then started logging `INFO    restarting      {"worker": "/app/public/index.php"}` every millisecond and did not accept any requests.

The loop looks like this:

```php
for($nbRequests = 0, $running = true; isset($_SERVER['MAX_REQUESTS']) && ($nbRequests < ((int)$_SERVER['MAX_REQUESTS'])) && $running; ++$nbRequests) {
```

I believe it should look like this:

```php
for ($nbRequests = 0, $running = true; $running && (!isset($_SERVER['MAX_REQUESTS']) || $nbRequests < (int)$_SERVER['MAX_REQUESTS']); ++$nbRequests) {
```

allowing to handle an unlimited number of requests if the variable is not specified and taking it into account if it is, instead of not entering the loop if the variable is not specified.

-----------

In fact perhaps the following is more appropriate, given that `$_SERVER` is “reset” after handling the first request. While environment variables will be part of `$_SERVER` for both the worker request and the HTTP requests, it feels more correct to store it in a local variable instead of a superglobal.

```php
$maxRequests = (int)($_SERVER['MAX_REQUESTS'] ?? -1);
for ($nbRequests = 0, $running = true; $running && ($maxRequests < 0 || $nbRequests < (int)$maxRequests); ++$nbRequests) {
```

### Build Type

Docker (Debian Bookworm)

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
Docs issue.
```

**Comment by dunglas** [comment]
Good catch! Would you mind opening a PR?
