### ISSUE TITLE
auto Restarting the server continuously 

### ISSUE THREAD

**Issue by ahmadkakarr** [dunglas/frankenphp#869]
### What happened?

in wsl windows 11 i am tring to test the frankenphp but got this error

my caddyfile config is 
```
{
	debug

	# TLS Options
	auto_https off
	email ahmadkakarr@gmail.com
frankenphp {
		worker {
			file /var/www/example.com/index.php # Sets the path to the worker script.
		}
	}
}



localhost:80 {
	root * /var/www/example.com
	encode zstd gzip
	php_server
}
```
![image](https://github.com/dunglas/frankenphp/assets/22844883/d9611dce-8ca1-4c70-96ab-0f817ca93d0c)

### Build Type

Standalone binary

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
this command worked 

 sudo ./frankenphp php-cli /var/www/example.com/index.php

and it gave me back php.ini in cli back.
```

**Comment by AlliBalliBaba** [comment]
@ahmadkakarr Does your `index.php` only contain `phpinfo()` and nothing else? Make sure you are using `frankenphp_handle_request($handler)` like described in [the docs](https://frankenphp.dev/docs/worker/#custom-apps) when creating a custom worker. 
Otherwise the workers won't actually handle any requests and just restart over and over.

**Comment by ahmadkakarr** [comment]
@AlliBalliBaba thank you for your time and respone, my `index.php` only contained `phpinfo()`,  so i changed my `index.php` according to your guidance and little googling to  the following

```php
<?php

// Prevent worker script termination when a client connection is interrupted
while (true) {
    \frankenphp_handle_request(static function(): void {
        phpinfo();
    });
}
```
now it worked, i can see my phpinfo page..

@AlliBalliBaba can you please further guide me to resources related to creating custom workers or examples docs not seem to be very self explanatory to me.

**Comment by ahmadkakarr** [comment]
Anyhow the issue is resolved with the help of @AlliBalliBaba . thank you

**Comment by AlliBalliBaba** [comment]
I guess the general concept behind the worker mode could be better explained in the docs.
Basically it works like this:
- When Frankenphp starts it will instantiate a specified number of 'workers' (usually 2x the numbers of your CPU cores)
- Every worker process is running the worker script that you have specified in the Caddyfile
- When the worker encounters the 'magic' `frankenphp_handle_request()` function, the script will stop and wait until it receives a request from Caddy
- FrankenPHP will reset the global PHP request variables to match those from the incoming Caddy request and execute the function you have passed to `frankenphp_handle_request()` (inisde the function you can also load classes and pretty much use PHP as you would normally)
- When the worker has finished running the script, it will just run it again

Why use Workers this way?
The main reason is better performance. Everything you do during the execution of the Worker script stays in memory. This allows you to do complicated bootstrapping only once before calling `frankenphp_handle_request()` and then just reuse instantiated Objects or external connections across requests.
Be wary though that static and global variables stay in memory which can lead to memory leaks.
