### ISSUE TITLE
[HELP] OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to composer.github.io:443

### ISSUE THREAD

**Issue by ezekel** [dunglas/frankenphp#922]
Hi, 

Need some help when I spin up my container it suddenly failing , this is the image I use in my docerfile

```

FROM dunglas/frankenphp:latest 

RUN install-php-extensions \
    pdo_mysql \
    gd \
    intl \
    zip \
    opcache\
    pcntl \
    @composer

RUN apt-get update && apt-get install -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

Thank you in advance

Here is the log

`
 > [php2 builder 2/5] RUN install-php-extensions     pdo_mysql     gd     intl     zip     opcache    pcntl     @composer:
0.191 install-php-extensions v.2.2.19
0.191 #StandWithUkraine
2.090 Updating channel "pecl.php.net"
2.803 Channel "pecl.php.net" is up to date
2.984 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
3.164 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
3.231 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
3.308 Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8788 kB]
4.156 Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [13.8 kB]
4.257 Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [168 kB]
5.054 Fetched 9224 kB in 2s (4204 kB/s)
5.054 Reading package lists...
8.514 ### MARKING PRE-INSTALLED PACKAGES AS IN-USE ###
9.037 libicu72 was already set to manually installed.
9.037 ### INSTALLING REQUIRED PACKAGES ###
9.037 # Packages to be kept after installation: libabsl20220623 libaom3 libavif15 libbsd0 libdav1d6 libfreetype6 libgav1-1 libjpeg62-turbo libmbedcrypto7 libmbedtls14 libmbedx509-1 libpng16-16 librav1e0 libsvtav1enc1 libwebp7 libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 libxpm4 libyuv0 libzip4 unzip
9.037 # Packages to be used only for installation: cmake cmake-data icu-devtools libaom-dev libarchive13 libavif-dev libbrotli-dev libbz2-dev libdav1d-dev libevent-2.1-7 libexpat1 libfreetype-dev libfre
etype6-dev libgmp-dev libgmpxx4ldbl libgnutls-dane0 libgnutls-openssl27 libgnutls28-dev libgnutlsxx30 libicu-dev libidn2-dev libjpeg62-turbo-dev libjsoncpp25 libmbedtls-dev libncursesw6 libp11-kit-dev l
ibpng-dev libproc2-0 libpthread-stubs0-dev librhash0 libssl-dev libtasn1-6-dev libunbound8 libuv1 libwebp-dev libwebpdemux2 libwebpmux3 libx11-dev libxau-dev libxcb1-dev libxdmcp-dev libxpm-dev libzip-dev nettle-dev procps x11proto-dev xorg-sgml-doctools xtrans-dev zlib1g-dev
18.69 debconf: delaying package configuration, since apt-utils is not installed
18.75 Selecting previously unselected package libncursesw6:amd64.
(Reading database ... 13291 files and directories currently installed.)
18.80 Preparing to unpack .../00-libncursesw6_6.4-4_amd64.deb ...
18.81 Unpacking libncursesw6:amd64 (6.4-4) ...
18.86 Selecting previously unselected package libproc2-0:amd64.
18.86 Preparing to unpack .../01-libproc2-0_2%3a4.0.2-3_amd64.deb ...
18.86 Unpacking libproc2-0:amd64 (2:4.0.2-3) ...
18.90 Selecting previously unselected package procps.
18.90 Preparing to unpack .../02-procps_2%3a4.0.2-3_amd64.deb ...
18.92 Unpacking procps (2:4.0.2-3) ...
19.00 Selecting previously unselected package libarchive13:amd64.
19.00 Preparing to unpack .../03-libarchive13_3.6.2-1+deb12u1_amd64.deb ...
19.00 Unpacking libarchive13:amd64 (3.6.2-1+deb12u1) ...
19.06 Selecting previously unselected package libexpat1:amd64.
19.06 Preparing to unpack .../04-libexpat1_2.5.0-1_amd64.deb ...
19.06 Unpacking libexpat1:amd64 (2.5.0-1) ...
19.10 Selecting previously unselected package libjsoncpp25:amd64.
19.10 Preparing to unpack .../05-libjsoncpp25_1.9.5-4_amd64.deb ...
19.11 Unpacking libjsoncpp25:amd64 (1.9.5-4) ...
19.14 Selecting previously unselected package librhash0:amd64.
19.14 Preparing to unpack .../06-librhash0_1.4.3-3_amd64.deb ...
19.15 Unpacking librhash0:amd64 (1.4.3-3) ...
19.19 Selecting previously unselected package libuv1:amd64.
19.20 Preparing to unpack .../07-libuv1_1.44.2-1+deb12u1_amd64.deb ...
19.20 Unpacking libuv1:amd64 (1.44.2-1+deb12u1) ...
19.25 Selecting previously unselected package cmake-data.
19.25 Preparing to unpack .../08-cmake-data_3.25.1-1_all.deb ...
19.26 Unpacking cmake-data (3.25.1-1) ...
19.75 Selecting previously unselected package cmake.
19.75 Preparing to unpack .../09-cmake_3.25.1-1_amd64.deb ...
19.76 Unpacking cmake (3.25.1-1) ...
20.25 Selecting previously unselected package icu-devtools.
20.25 Preparing to unpack .../10-icu-devtools_72.1-3_amd64.deb ...
20.25 Unpacking icu-devtools (72.1-3) ...
20.30 Selecting previously unselected package libabsl20220623:amd64.
20.30 Preparing to unpack .../11-libabsl20220623_20220623.1-1_amd64.deb ...
20.30 Unpacking libabsl20220623:amd64 (20220623.1-1) ...
20.37 Selecting previously unselected package libaom3:amd64.
20.37 Preparing to unpack .../12-libaom3_3.6.0-1_amd64.deb ...
20.37 Unpacking libaom3:amd64 (3.6.0-1) ...
20.52 Selecting previously unselected package libaom-dev:amd64.
20.52 Preparing to unpack .../13-libaom-dev_3.6.0-1_amd64.deb ...
20.53 Unpacking libaom-dev:amd64 (3.6.0-1) ...
20.70 Selecting previously unselected package libdav1d6:amd64.
20.70 Preparing to unpack .../14-libdav1d6_1.0.0-2+deb12u1_amd64.deb ...
20.71 Unpacking libdav1d6:amd64 (1.0.0-2+deb12u1) ...
20.77 Selecting previously unselected package libgav1-1:amd64.
20.77 Preparing to unpack .../15-libgav1-1_0.18.0-1+b1_amd64.deb ...
20.78 Unpacking libgav1-1:amd64 (0.18.0-1+b1) ...
20.84 Selecting previously unselected package librav1e0:amd64.
20.84 Preparing to unpack .../16-librav1e0_0.5.1-6_amd64.deb ...
20.84 Unpacking librav1e0:amd64 (0.5.1-6) ...
20.92 Selecting previously unselected package libsvtav1enc1:amd64.
20.93 Preparing to unpack .../17-libsvtav1enc1_1.4.1+dfsg-1_amd64.deb ...
20.93 Unpacking libsvtav1enc1:amd64 (1.4.1+dfsg-1) ...
21.10 Selecting previously unselected package libjpeg62-turbo:amd64.
21.11 Preparing to unpack .../18-libjpeg62-turbo_1%3a2.1.5-2_amd64.deb ...
21.11 Unpacking libjpeg62-turbo:amd64 (1:2.1.5-2) ...
21.16 Selecting previously unselected package libyuv0:amd64.
21.16 Preparing to unpack .../19-libyuv0_0.0~git20230123.b2528b0-1_amd64.deb ...
21.16 Unpacking libyuv0:amd64 (0.0~git20230123.b2528b0-1) ...
21.21 Selecting previously unselected package libavif15:amd64.
21.21 Preparing to unpack .../20-libavif15_0.11.1-1_amd64.deb ...
21.21 Unpacking libavif15:amd64 (0.11.1-1) ...
21.24 Selecting previously unselected package libavif-dev:amd64.
21.24 Preparing to unpack .../21-libavif-dev_0.11.1-1_amd64.deb ...
21.25 Unpacking libavif-dev:amd64 (0.11.1-1) ...
21.28 Selecting previously unselected package libbrotli-dev:amd64.
21.28 Preparing to unpack .../22-libbrotli-dev_1.0.9-2+b6_amd64.deb ...
21.28 Unpacking libbrotli-dev:amd64 (1.0.9-2+b6) ...
21.34 Selecting previously unselected package libbsd0:amd64.
21.34 Preparing to unpack .../23-libbsd0_0.11.7-2_amd64.deb ...
21.34 Unpacking libbsd0:amd64 (0.11.7-2) ...
21.38 Selecting previously unselected package libbz2-dev:amd64.
21.38 Preparing to unpack .../24-libbz2-dev_1.0.8-5+b1_amd64.deb ...
21.38 Unpacking libbz2-dev:amd64 (1.0.8-5+b1) ...
21.41 Selecting previously unselected package libdav1d-dev:amd64.
21.41 Preparing to unpack .../25-libdav1d-dev_1.0.0-2+deb12u1_amd64.deb ...
21.41 Unpacking libdav1d-dev:amd64 (1.0.0-2+deb12u1) ...
21.45 Selecting previously unselected package libevent-2.1-7:amd64.
21.45 Preparing to unpack .../26-libevent-2.1-7_2.1.12-stable-8_amd64.deb ...
21.46 Unpacking libevent-2.1-7:amd64 (2.1.12-stable-8) ...
21.50 Selecting previously unselected package libpng16-16:amd64.
21.50 Preparing to unpack .../27-libpng16-16_1.6.39-2_amd64.deb ...
21.50 Unpacking libpng16-16:amd64 (1.6.39-2) ...
21.55 Selecting previously unselected package libfreetype6:amd64.
21.55 Preparing to unpack .../28-libfreetype6_2.12.1+dfsg-5+deb12u3_amd64.deb ...
21.56 Unpacking libfreetype6:amd64 (2.12.1+dfsg-5+deb12u3) ...
21.61 Selecting previously unselected package zlib1g-dev:amd64.
21.61 Preparing to unpack .../29-zlib1g-dev_1%3a1.2.13.dfsg-1_amd64.deb ...
21.62 Unpacking zlib1g-dev:amd64 (1:1.2.13.dfsg-1) ...
21.67 Selecting previously unselected package libpng-dev:amd64.
21.67 Preparing to unpack .../30-libpng-dev_1.6.39-2_amd64.deb ...
21.68 Unpacking libpng-dev:amd64 (1.6.39-2) ...
21.73 Selecting previously unselected package libfreetype-dev:amd64.
21.73 Preparing to unpack .../31-libfreetype-dev_2.12.1+dfsg-5+deb12u3_amd64.deb ...
21.73 Unpacking libfreetype-dev:amd64 (2.12.1+dfsg-5+deb12u3) ...
21.80 Selecting previously unselected package libfreetype6-dev:amd64.
21.80 Preparing to unpack .../32-libfreetype6-dev_2.12.1+dfsg-5+deb12u3_amd64.deb ...
21.80 Unpacking libfreetype6-dev:amd64 (2.12.1+dfsg-5+deb12u3) ...
21.84 Selecting previously unselected package libgmpxx4ldbl:amd64.
21.84 Preparing to unpack .../33-libgmpxx4ldbl_2%3a6.2.1+dfsg1-1.1_amd64.deb ...
21.85 Unpacking libgmpxx4ldbl:amd64 (2:6.2.1+dfsg1-1.1) ...
21.88 Selecting previously unselected package libgmp-dev:amd64.
21.88 Preparing to unpack .../34-libgmp-dev_2%3a6.2.1+dfsg1-1.1_amd64.deb ...
21.89 Unpacking libgmp-dev:amd64 (2:6.2.1+dfsg1-1.1) ...
21.94 Selecting previously unselected package libunbound8:amd64.
21.95 Preparing to unpack .../35-libunbound8_1.17.1-2+deb12u2_amd64.deb ...
21.95 Unpacking libunbound8:amd64 (1.17.1-2+deb12u2) ...
22.02 Selecting previously unselected package libgnutls-dane0:amd64.
22.02 Preparing to unpack .../36-libgnutls-dane0_3.7.9-2+deb12u3_amd64.deb ...
22.02 Unpacking libgnutls-dane0:amd64 (3.7.9-2+deb12u3) ...
22.07 Selecting previously unselected package libgnutls-openssl27:amd64.
22.07 Preparing to unpack .../37-libgnutls-openssl27_3.7.9-2+deb12u3_amd64.deb ...
22.07 Unpacking libgnutls-openssl27:amd64 (3.7.9-2+deb12u3) ...
22.11 Selecting previously unselected package libgnutlsxx30:amd64.
22.11 Preparing to unpack .../38-libgnutlsxx30_3.7.9-2+deb12u3_amd64.deb ...
22.12 Unpacking libgnutlsxx30:amd64 (3.7.9-2+deb12u3) ...
22.14 Selecting previously unselected package libidn2-dev:amd64.
22.14 Preparing to unpack .../39-libidn2-dev_2.3.3-1+b1_amd64.deb ...
22.15 Unpacking libidn2-dev:amd64 (2.3.3-1+b1) ...
22.18 Selecting previously unselected package libp11-kit-dev:amd64.
22.19 Preparing to unpack .../40-libp11-kit-dev_0.24.1-2_amd64.deb ...
22.19 Unpacking libp11-kit-dev:amd64 (0.24.1-2) ...
22.22 Selecting previously unselected package libtasn1-6-dev:amd64.
22.23 Preparing to unpack .../41-libtasn1-6-dev_4.19.0-2_amd64.deb ...
22.23 Unpacking libtasn1-6-dev:amd64 (4.19.0-2) ...
22.27 Selecting previously unselected package nettle-dev:amd64.
22.27 Preparing to unpack .../42-nettle-dev_3.8.1-2_amd64.deb ...
22.27 Unpacking nettle-dev:amd64 (3.8.1-2) ...
22.35 Selecting previously unselected package libgnutls28-dev:amd64.
22.35 Preparing to unpack .../43-libgnutls28-dev_3.7.9-2+deb12u3_amd64.deb ...
22.35 Unpacking libgnutls28-dev:amd64 (3.7.9-2+deb12u3) ...
22.45 Selecting previously unselected package libicu-dev:amd64.
22.45 Preparing to unpack .../44-libicu-dev_72.1-3_amd64.deb ...
22.46 Unpacking libicu-dev:amd64 (72.1-3) ...
22.94 Selecting previously unselected package libjpeg62-turbo-dev:amd64.
22.94 Preparing to unpack .../45-libjpeg62-turbo-dev_1%3a2.1.5-2_amd64.deb ...
22.94 Unpacking libjpeg62-turbo-dev:amd64 (1:2.1.5-2) ...
23.00 Selecting previously unselected package libmbedcrypto7:amd64.
23.00 Preparing to unpack .../46-libmbedcrypto7_2.28.3-1_amd64.deb ...
23.00 Unpacking libmbedcrypto7:amd64 (2.28.3-1) ...
23.06 Selecting previously unselected package libmbedx509-1:amd64.
23.07 Preparing to unpack .../47-libmbedx509-1_2.28.3-1_amd64.deb ...
23.07 Unpacking libmbedx509-1:amd64 (2.28.3-1) ...
23.11 Selecting previously unselected package libmbedtls14:amd64.
23.11 Preparing to unpack .../48-libmbedtls14_2.28.3-1_amd64.deb ...
23.11 Unpacking libmbedtls14:amd64 (2.28.3-1) ...
23.15 Selecting previously unselected package libmbedtls-dev:amd64.
23.15 Preparing to unpack .../49-libmbedtls-dev_2.28.3-1_amd64.deb ...
23.16 Unpacking libmbedtls-dev:amd64 (2.28.3-1) ...
23.23 Selecting previously unselected package libpthread-stubs0-dev:amd64.
23.23 Preparing to unpack .../50-libpthread-stubs0-dev_0.4-1_amd64.deb ...
23.23 Unpacking libpthread-stubs0-dev:amd64 (0.4-1) ...
23.26 Selecting previously unselected package libssl-dev:amd64.
23.26 Preparing to unpack .../51-libssl-dev_3.0.13-1~deb12u1_amd64.deb ...
23.27 Unpacking libssl-dev:amd64 (3.0.13-1~deb12u1) ...
23.44 Selecting previously unselected package libwebp7:amd64.
23.44 Preparing to unpack .../52-libwebp7_1.2.4-0.2+deb12u1_amd64.deb ...
23.45 Unpacking libwebp7:amd64 (1.2.4-0.2+deb12u1) ...
23.50 Selecting previously unselected package libwebpmux3:amd64.
23.50 Preparing to unpack .../53-libwebpmux3_1.2.4-0.2+deb12u1_amd64.deb ...
23.50 Unpacking libwebpmux3:amd64 (1.2.4-0.2+deb12u1) ...
23.54 Selecting previously unselected package libwebpdemux2:amd64.
23.54 Preparing to unpack .../54-libwebpdemux2_1.2.4-0.2+deb12u1_amd64.deb ...
23.54 Unpacking libwebpdemux2:amd64 (1.2.4-0.2+deb12u1) ...
23.58 Selecting previously unselected package libwebp-dev:amd64.
23.58 Preparing to unpack .../55-libwebp-dev_1.2.4-0.2+deb12u1_amd64.deb ...
23.58 Unpacking libwebp-dev:amd64 (1.2.4-0.2+deb12u1) ...
23.64 Selecting previously unselected package libxau6:amd64.
23.64 Preparing to unpack .../56-libxau6_1%3a1.0.9-1_amd64.deb ...
23.65 Unpacking libxau6:amd64 (1:1.0.9-1) ...
23.68 Selecting previously unselected package libxdmcp6:amd64.
23.68 Preparing to unpack .../57-libxdmcp6_1%3a1.1.2-3_amd64.deb ...
23.69 Unpacking libxdmcp6:amd64 (1:1.1.2-3) ...
23.72 Selecting previously unselected package libxcb1:amd64.
23.72 Preparing to unpack .../58-libxcb1_1.15-1_amd64.deb ...
23.73 Unpacking libxcb1:amd64 (1.15-1) ...
23.77 Selecting previously unselected package libx11-data.
23.77 Preparing to unpack .../59-libx11-data_2%3a1.8.4-2+deb12u2_all.deb ...
23.78 Unpacking libx11-data (2:1.8.4-2+deb12u2) ...
23.84 Selecting previously unselected package libx11-6:amd64.
23.85 Preparing to unpack .../60-libx11-6_2%3a1.8.4-2+deb12u2_amd64.deb ...
23.85 Unpacking libx11-6:amd64 (2:1.8.4-2+deb12u2) ...
23.93 Selecting previously unselected package xorg-sgml-doctools.
23.93 Preparing to unpack .../61-xorg-sgml-doctools_1%3a1.11-1.1_all.deb ...
23.93 Unpacking xorg-sgml-doctools (1:1.11-1.1) ...
23.96 Selecting previously unselected package x11proto-dev.
23.96 Preparing to unpack .../62-x11proto-dev_2022.1-1_all.deb ...
23.96 Unpacking x11proto-dev (2022.1-1) ...
24.03 Selecting previously unselected package libxau-dev:amd64.
24.04 Preparing to unpack .../63-libxau-dev_1%3a1.0.9-1_amd64.deb ...
24.04 Unpacking libxau-dev:amd64 (1:1.0.9-1) ...
24.07 Selecting previously unselected package libxdmcp-dev:amd64.
24.07 Preparing to unpack .../64-libxdmcp-dev_1%3a1.1.2-3_amd64.deb ...
24.07 Unpacking libxdmcp-dev:amd64 (1:1.1.2-3) ...
24.10 Selecting previously unselected package xtrans-dev.
24.11 Preparing to unpack .../65-xtrans-dev_1.4.0-1_all.deb ...
24.11 Unpacking xtrans-dev (1.4.0-1) ...
24.14 Selecting previously unselected package libxcb1-dev:amd64.
24.15 Preparing to unpack .../66-libxcb1-dev_1.15-1_amd64.deb ...
24.15 Unpacking libxcb1-dev:amd64 (1.15-1) ...
24.19 Selecting previously unselected package libx11-dev:amd64.
24.19 Preparing to unpack .../67-libx11-dev_2%3a1.8.4-2+deb12u2_amd64.deb ...
24.19 Unpacking libx11-dev:amd64 (2:1.8.4-2+deb12u2) ...
24.27 Selecting previously unselected package libxpm4:amd64.
24.27 Preparing to unpack .../68-libxpm4_1%3a3.5.12-1.1+deb12u1_amd64.deb ...
24.28 Unpacking libxpm4:amd64 (1:3.5.12-1.1+deb12u1) ...
24.30 Selecting previously unselected package libxpm-dev:amd64.
24.30 Preparing to unpack .../69-libxpm-dev_1%3a3.5.12-1.1+deb12u1_amd64.deb ...
24.31 Unpacking libxpm-dev:amd64 (1:3.5.12-1.1+deb12u1) ...
24.35 Selecting previously unselected package libzip4:amd64.
24.35 Preparing to unpack .../70-libzip4_1.7.3-1+b1_amd64.deb ...
24.35 Unpacking libzip4:amd64 (1.7.3-1+b1) ...
24.39 Selecting previously unselected package libzip-dev:amd64.
24.39 Preparing to unpack .../71-libzip-dev_1.7.3-1+b1_amd64.deb ...
24.39 Unpacking libzip-dev:amd64 (1.7.3-1+b1) ...
24.44 Selecting previously unselected package unzip.
24.44 Preparing to unpack .../72-unzip_6.0-28_amd64.deb ...
24.45 Unpacking unzip (6.0-28) ...
24.50 Setting up libexpat1:amd64 (2.5.0-1) ...
24.51 Setting up libaom3:amd64 (3.6.0-1) ...
24.52 Setting up libabsl20220623:amd64 (20220623.1-1) ...
24.53 Setting up libxau6:amd64 (1:1.0.9-1) ...
24.54 Setting up libgnutls-openssl27:amd64 (3.7.9-2+deb12u3) ...
24.55 Setting up libarchive13:amd64 (3.6.2-1+deb12u1) ...
24.56 Setting up libzip4:amd64 (1.7.3-1+b1) ...
24.57 Setting up unzip (6.0-28) ...
24.60 Setting up libsvtav1enc1:amd64 (1.4.1+dfsg-1) ...
24.63 Setting up libpthread-stubs0-dev:amd64 (0.4-1) ...
24.64 Setting up librav1e0:amd64 (0.5.1-6) ...
24.65 Setting up libaom-dev:amd64 (3.6.0-1) ...
24.66 Setting up xtrans-dev (1.4.0-1) ...
24.67 Setting up libgmpxx4ldbl:amd64 (2:6.2.1+dfsg1-1.1) ...
24.68 Setting up libuv1:amd64 (1.44.2-1+deb12u1) ...
24.69 Setting up libjpeg62-turbo:amd64 (1:2.1.5-2) ...
24.70 Setting up libmbedcrypto7:amd64 (2.28.3-1) ...
24.71 Setting up libx11-data (2:1.8.4-2+deb12u2) ...
24.72 Setting up libjpeg62-turbo-dev:amd64 (1:2.1.5-2) ...
24.73 Setting up libgnutlsxx30:amd64 (3.7.9-2+deb12u3) ...
24.74 Setting up libproc2-0:amd64 (2:4.0.2-3) ...
24.75 Setting up libssl-dev:amd64 (3.0.13-1~deb12u1) ...
24.78 Setting up libpng16-16:amd64 (1.6.39-2) ...
24.79 Setting up libevent-2.1-7:amd64 (2.1.12-stable-8) ...
24.80 Setting up libjsoncpp25:amd64 (1.9.5-4) ...
24.81 Setting up icu-devtools (72.1-3) ...
24.82 Setting up libgav1-1:amd64 (0.18.0-1+b1) ...
24.83 Setting up libncursesw6:amd64 (6.4-4) ...
24.84 Setting up libdav1d6:amd64 (1.0.0-2+deb12u1) ...
24.85 Setting up libidn2-dev:amd64 (2.3.3-1+b1) ...
24.86 Setting up libwebp7:amd64 (1.2.4-0.2+deb12u1) ...
24.87 Setting up zlib1g-dev:amd64 (1:1.2.13.dfsg-1) ...
24.88 Setting up librhash0:amd64 (1.4.3-3) ...
24.89 Setting up procps (2:4.0.2-3) ...
24.93 Setting up xorg-sgml-doctools (1:1.11-1.1) ...
24.94 Setting up cmake-data (3.25.1-1) ...
24.95 Setting up libtasn1-6-dev:amd64 (4.19.0-2) ...
24.96 Setting up libwebpmux3:amd64 (1.2.4-0.2+deb12u1) ...
24.97 Setting up libbsd0:amd64 (0.11.7-2) ...
24.98 Setting up libyuv0:amd64 (0.0~git20230123.b2528b0-1) ...
24.99 Setting up libicu-dev:amd64 (72.1-3) ...
25.00 Setting up libbrotli-dev:amd64 (1.0.9-2+b6) ...
25.01 Setting up libp11-kit-dev:amd64 (0.24.1-2) ...
25.02 Setting up libbz2-dev:amd64 (1.0.8-5+b1) ...
25.03 Setting up x11proto-dev (2022.1-1) ...
25.04 Setting up libxdmcp6:amd64 (1:1.1.2-3) ...
25.05 Setting up libzip-dev:amd64 (1.7.3-1+b1) ...
25.06 Setting up libxcb1:amd64 (1.15-1) ...
25.07 Setting up libgmp-dev:amd64 (2:6.2.1+dfsg1-1.1) ...
25.08 Setting up libxau-dev:amd64 (1:1.0.9-1) ...
25.09 Setting up libavif15:amd64 (0.11.1-1) ...
25.10 Setting up libmbedx509-1:amd64 (2.28.3-1) ...
25.11 Setting up libmbedtls14:amd64 (2.28.3-1) ...
25.12 Setting up nettle-dev:amd64 (3.8.1-2) ...
25.13 Setting up libwebpdemux2:amd64 (1.2.4-0.2+deb12u1) ...
25.14 Setting up libpng-dev:amd64 (1.6.39-2) ...
25.15 Setting up libmbedtls-dev:amd64 (2.28.3-1) ...
25.16 Setting up libxdmcp-dev:amd64 (1:1.1.2-3) ...
25.17 Setting up libwebp-dev:amd64 (1.2.4-0.2+deb12u1) ...
25.18 Setting up libunbound8:amd64 (1.17.1-2+deb12u2) ...
25.19 Setting up libfreetype6:amd64 (2.12.1+dfsg-5+deb12u3) ...
25.20 Setting up libdav1d-dev:amd64 (1.0.0-2+deb12u1) ...
25.21 Setting up libavif-dev:amd64 (0.11.1-1) ...
25.23 Setting up cmake (3.25.1-1) ...
25.24 Setting up libx11-6:amd64 (2:1.8.4-2+deb12u2) ...
25.25 Setting up libgnutls-dane0:amd64 (3.7.9-2+deb12u3) ...
25.26 Setting up libxcb1-dev:amd64 (1.15-1) ...
25.27 Setting up libxpm4:amd64 (1:3.5.12-1.1+deb12u1) ...
25.28 Setting up libx11-dev:amd64 (2:1.8.4-2+deb12u2) ...
25.30 Setting up libfreetype-dev:amd64 (2.12.1+dfsg-5+deb12u3) ...
25.31 Setting up libxpm-dev:amd64 (1:3.5.12-1.1+deb12u1) ...
25.32 Setting up libgnutls28-dev:amd64 (3.7.9-2+deb12u3) ...
25.33 Setting up libfreetype6-dev:amd64 (2.12.1+dfsg-5+deb12u3) ...
25.34 Processing triggers for libc-bin (2.36-9+deb12u7) ...
25.43 Processing triggers for mailcap (3.70+nmu1) ...
25.48 ### INSTALLING composer ###
26.82 curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to composer.github.io:443
------
failed to solve: process "/bin/sh -c install-php-extensions     pdo_mysql     gd     intl     zip     opcache    pcntl     @composer" did not complete successfully: exit code: 35
`

**Comment by AlliBalliBaba** [comment]
I don't think this is a FrankenPHP issue, it looks like you are having having trouble with establishing a secure connection with https://composer.github.io from your local machine, thus the docker image fails at installing composer. You can try running `curl -v https://composer.github.io` and see if it still throws the same error. Are you maybe using a VPN?
