### ISSUE TITLE
@withinboredom use frankenphp builder images ?

### ISSUE THREAD

**Issue by g-ra** [dunglas/frankenphp#947]
@withinboredom use frankenphp builder images ? 
https://github.com/dunglas/frankenphp/issues/944

_Originally posted by @g-ra in https://github.com/dunglas/frankenphp/issues/946#issuecomment-2262212919_

**Comment by g-ra** [comment]
Forgive me but I'm looking for workarounds to get around the problem with installing the module, it's critically important for us to do this now, https://github.com/dunglas/frankenphp/issues/944 the first problem is related to the installation according to the documentation and this solution does not workhttps://github.com/dunglas/frankenphp/issues/944 the second problem is related to the workaround and an attempt to build everything from source  https://github.com/dunglas/frankenphp/issues/946 PLEASE, Let me know if you have any useful information that will help to close these problems! 01.08.2024, 20:00, "Silvio Ney" ***@***.***>: Please close the issue since you already have one about this...—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>  -- С уважением Dmitry Gerasin

**Comment by sneycampos** [comment]
And think spamming the issues will help?

**Comment by sneycampos** [comment]
Try taking a look at this [Dockerfile](https://github.com/sneycampos/laravel-octane-frankenphp/blob/master/Dockerfile)

**Comment by withinboredom** [comment]
I've always thought it would be nice to have an issue named after me...

However, it seems counterproductive to create a new issue when there's already one that you've linked to and commented on in other issues. If you're looking for a faster response, you can find my email on GitHub, my blog, or my Hacker News profile. That said, you don't necessarily need a response from me specifically. Several people have already tried to assist you, and creating additional issues or repeatedly posting can make it harder for others to help.

It looks like a few people have already provided the answer you're looking for, so I'll be closing this issue as resolved.
