### ISSUE TITLE
Support curl-impersonate

### ISSUE THREAD

**Issue by dzasa** [dunglas/frankenphp#949]
### Describe you feature request

Is there a plan to support curl-impersonate https://github.com/lwthiker/curl-impersonate/tree/main ?
 
I managed to run manually php commands with curl impersonate, but not with frankenphp

**Comment by dunglas** [comment]
I don't see how it's related to FrankenPHP. If it works with a standard PHP build, it should work with FrankenPHP as well. If it's not the case, could you provide a reproducer (if possible a minimal Docker image) and the related logs?

Thanks.

**Comment by dzasa** [comment]
Thanks @dunglas for fast response :). It might not be improvement, I thought so it was, but more like "I dont know how to implement it with frankenphp".

This is instruction how to make it work with PHP
https://github.com/lwthiker/curl-impersonate/blob/main/docs/03_LIBCURL_IMPERSONATE_PHP.md

And as I take frankenphp in dockerfile 
`FROM dunglas/frankenphp:1-php8.3 AS php_upstream`

I managed to make it work with php with
```
RUN git clone https://github.com/lwthiker/curl-impersonate.git
WORKDIR curl-impersonate
RUN mkdir build
WORKDIR build
RUN ../configure
RUN make chrome-build
RUN make chrome-install
RUN ldconfig
WORKDIR /app/curl-impersonate
RUN rm -Rf build

RUN patchelf --set-soname libcurl.so /usr/local/lib/libcurl-impersonate-chrome.so
RUN echo "/usr/local/lib/libcurl-impersonate-chrome.so" > /etc/ld.so.preload
```

And when I run
```
php -r 'print_r(curl_version());'
```

It gives me
```
[ssl_version] => BoringSSL
```

But when I make http request which is handled by frankenphp it does not return info via libcurl-impersonate, but via original libcurl

**Comment by withinboredom** [comment]
Can you please share a dockerfile that reproduces the issue and shows what you're trying to do? Trying to piece together one from your post is error-prone.

Is this a docker file that reproduces the issue?

```dockerfile
FROM dunglas/frankenphp:1-php8.3 AS php_upstream
RUN git clone https://github.com/lwthiker/curl-impersonate.git
WORKDIR curl-impersonate
RUN mkdir build
WORKDIR build
RUN ../configure
RUN make chrome-build
RUN make chrome-install
RUN ldconfig
WORKDIR /app/curl-impersonate
RUN rm -Rf build

RUN patchelf --set-soname libcurl.so /usr/local/lib/libcurl-impersonate-chrome.so
RUN echo "/usr/local/lib/libcurl-impersonate-chrome.so" > /etc/ld.so.preload
RUN php -r 'print_r(curl_version());'
RUN frankenphp # some script?
```

**Comment by dunglas** [comment]
That's surprising that you need a full rebuild.

Could you try if this cleaning the ldconfig cache works instead?

```
rm /etc/ld.so.cache
ldconfig
```

**Comment by dzasa** [comment]
That worked, thank you :).
