### ISSUE TITLE
Slow performance with Docker instalation on Windows.

### ISSUE THREAD

**Issue by JakubJV** [dunglas/frankenphp#953]
Hi, I'm trying to integrate Laravel with FrankenPHP and Octane into a fresh Laravel project on a Windows operating system. I'm following the Laravel documentation and creating a Docker image for FrankenPHP as described. The container is created and starts successfully, but the performance with FrankenPHP is worse than when I run the project using php artisan serve. I’m a bit new to this and am unsure if I'm doing something wrong. Could someone help me?

This is request with FrankenPHP 
![franken](https://github.com/user-attachments/assets/8bd94a10-d9af-4493-a365-9322ea53e2bb)

This is request when php artisan serve is running without Franken.
![artisan-serve](https://github.com/user-attachments/assets/b8135684-285d-4ad9-b861-3f397ec8e3d2)
Thanks in advance! :)

**Comment by dunglas** [comment]
If you are using a Docker volume, this is expected (and unrelated with FrankenPHP). Docker volumes on Windows slow down IO a lot because the data must be copied between two different file systems.

Closing as this is a Docker issue, unrelated with FrankenPHP.

**Comment by JakubJV** [comment]
So it´s unusable on Windows with docker. Okay, thanks for respond🙂

**Comment by dunglas** [comment]
You can use WSL instead of Docker. You can also dramatically improve the performance of Docker for Windows by sharing only what is strictly needed in the volume. But this is out of scope of this repository. Take a look to https://github.com/dunglas/symfony-docker for an example that works well on Windows using Symfony and FrankenPHP.

**Comment by JakubJV** [comment]
> You can use WSL instead of Docker. You can also dramatically improve the performance of Docker for Windows by sharing only what is strictly needed in the volume. But this is out of scope of this repository. Take a look to https://github.com/dunglas/symfony-docker for an example that works well on Windows using Symfony and FrankenPHP.

Thanks for advice! :)
