### ISSUE TITLE
Standalone binaries with Caddy cache-handler

### ISSUE THREAD

**Issue by laurent-bientz** [dunglas/frankenphp#956]
### Describe you feature request

Hello,

**Is your feature request related to a problem? Please describe.**

We're using [frankenphp standalone binaries](https://github.com/dunglas/frankenphp/releases/latest/download/frankenphp-linux-x86_64) with api platform and we want to test the new recommended [http cache module](https://api-platform.com/docs/core/performance/#integrations) instead of Varnish.

It seems that cache module is not packaged in the Caddy web server.

**Describe the solution you'd like**

* Include [cache-handler](https://github.com/caddyserver/cache-handler) in the default caddy instance packaged in the binaries?
* Generate binaries with/without HTTP Cache?

**Describe alternatives you've considered**

[Create static binary](https://frankenphp.dev/docs/static/) ourselves (or using the [shell script](https://github.com/dunglas/frankenphp/blob/main/build-static.sh)) but we don't see any Docker ARG (env variables) to enable Caddy's http cache module.

**Comment by dunglas** [comment]
We follow Caddy's (@mholt, @francislavoie) and Souin's (@darkweak) strategy here.
Currently, Caddy doesn't include Souin by default because the lib has many external dependencies.

For this reason, we'll not include this module by default either, until it is bundled in upstream Caddy.
